src/capi.ts
src/server/server.ts
src/types/result.ts

Regardless of the response CAPI has been returning to us on an article request, we have been attempting to parse it as though it were successful. This has led to some unhelpful error messages, and made it harder to debug issues.
This PR adds some more granular handling of CAPI responses, and (hopefully) some more descriptive error messages. Depending on how this goes, I'm hoping to expand this method of error handling to other parts of the codebase.
- Deleted the `Capi` type.
- Created some error types to handle different CAPI response structures.
- Wrote some parsing code to handle different CAPI responses, and migrated some logic to keep all CAPI handling code to one file (should make it easier to define what's used in DEV vs PROD once MAPI handles CAPI requests).
- Created new types to …

CAPI Error Handling

---

src/components/immersive/immersiveStandfirst.tsx
src/components/liveblog/liveblogBlock.tsx
src/components/news/articleStandfirst.tsx
src/styles.ts

Dotcom and the current templates use special link styles. I'm not sure of the origin or reason behind this but it looks to improve readability.
This PR uses the same styling.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71197854-6dbaa080-228a-11ea-9631-8bbab6a1dc7e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71197862-71e6be00-228a-11ea-874d-072e116811a5.png" width="300px" /> |

link style

---

src/components/immersive/immersiveStandfirst.tsx
src/components/liveblog/liveblogByline.tsx
src/components/liveblog/liveblogStandfirst.tsx
src/components/news/articleByline.tsx
src/components/news/articleStandfirst.tsx
src/components/opinion/opinionHeadline.tsx
src/renderBlocks.ts

Replace all uses of `dangerouslySetInnerHtml` and reuse the jsdom code inside of `renderBlocks`.
We can reuse this `componentFromHtml` function whenever we receive individual html fields from capi.

Create components rather than set html

---

src/components/opinion/opinionHeadline.tsx
src/styles.ts

Header needed updating and fixing the return type of `linkStyles` fixed a few style issues.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71253366-9c368b00-231f-11ea-8978-9d2d593be6aa.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/71253383-a5bff300-231f-11ea-9921-e27661796a4a.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/11618797/71253400-b3757880-231f-11ea-9c72-fedf2ef87c5e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/71253405-bb351d00-231f-11ea-94a0-026ecb34f695.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/11618797/71253457-e0299000-231f-11ea-8e69-02b71dba153d.png" width="300" /> | <img …

Opinion dark mode fixes

---

src/components/immersive/immersiveArticle.tsx
src/styles.ts

Dark mode fixes on immersive articles. There was a white background in the wide breakpoint.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71266406-3c9ca780-2340-11ea-9c88-7d0063cd0275.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71266419-46260f80-2340-11ea-8a92-67137059dd16.png" width="300px" /> |

Immersive article dark styles

---

src/components/liveblog/liveblog.stories.tsx
src/components/shared/Tags.test.tsx
src/components/shared/shared.stories.tsx
src/components/shared/tags.tsx

- Liveblog story
- Shared story
- Simplify props for `Tags` component
New stories deployed to [GitHub pages](https://guardian.github.io/apps-rendering)

shared and liveblog stories

---

src/styles.ts

Blockquotes have a default margin in browsers like Chrome. The current templates design don't have this margin so this PR removes the default style.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71673415-acfbed80-2d70-11ea-8b82-1f849b1a89bb.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71673430-b8e7af80-2d70-11ea-8f53-8353cab7ccfe.png" width="300px" /> |

Remove blockquote left margin

---

src/components/news/articleStandfirst.tsx
src/renderBlocks.ts

- Add the remaining text, this was getting cut off if the lastChild node was a text element..
- Removed the unnecessary transform in standfirst (as it now happens inside `componentFromHtml`)
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71674120-58f20880-2d72-11ea-947d-554403cc4227.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71674134-614a4380-2d72-11ea-9721-e5368c4693c6.png" width="300px" /> |

missing byline text

---

src/components/immersive/immersiveArticle.tsx
src/components/shared/articleBody.tsx

These styles move the immersive article designs closer to dotcom and the current templates.
- Drop cap styles after section-rules
- Style first-child letters not first-of-type (see gu.com/world/2020/jan/03/visual-guide-airstrike-that-killed-qassam-suleimani-us-iran) 
- Special immersive headline styles
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71730780-f87ace00-2e3a-11ea-8b59-7dfbe44f9cea.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71730784-fe70af00-2e3a-11ea-8627-f76668f887bf.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/71730790-04ff2680-2e3b-11ea-88a9-ab594a8a1ed7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71730 …

Immersive design updates

---

src/ads.test.ts
src/ads.ts
src/asset.ts
src/block.ts
src/components/immersive/immersiveArticle.tsx
src/components/liveblog/liveblogBody.tsx
src/components/news/article.tsx
src/components/opinion/opinionArticle.tsx
src/components/shared/articleBody.tsx
src/components/shared/page.tsx
src/types/result.ts

I was starting to hit the limitations of the current approach in `renderBlocks`. The parsing of content from CAPI was too interleaved with the rendering layer. This was only causing minor problems server-side, but client-side we need to maintain state independent of the view and deal with updates to that state.
This splits out parsing and rendering so that they happen independent of one another. Both pieces of functionality are located in the new `block` module, written around the `Block` type. This may change later.
Currently this does not touch the liveblogs, as this PR is already pretty large. Changes there will happen in a future PR.
I've moved some styles around; I *think* everything looks OK, but please shout if you spot any problems.
- Created new `block.ts` file to handle parsing …

Re-write Blocks Rendering

---

src/server/server.ts

New developers may be unaware of webpack dev server running on port 8080

Log dev server port

---

src/block.ts
src/components/blocks/image.ts

Set a min height on images (with a background colour) to avoid content jumping when the images load.
This is not the same ratio as before. e.g. removing these styles will show a smaller image... maybe this calc needs changing or we pass another height param to the fastly image resizer?

Set height on images

---

src/article.ts
src/capi.ts
src/components/immersive/immersiveArticle.tsx
src/components/liveblog/liveblogArticle.tsx
src/components/liveblog/liveblogByline.tsx
src/components/news/article.tsx
src/components/opinion/opinionArticle.tsx
src/components/shared/Keyline.test.tsx
src/components/shared/keyline.tsx
src/components/shared/page.tsx

I think all articles are described by two key pieces of information. First is the `Pillar`, which we have an existing type for. Second is a less well-defined concept that I've called "layout". This is basically a description of the various ways articles vary in design based on a number of factors:
- Is it an opinion piece?
- Is it an analysis?
- Does it have the feature tone?
- Is it a liveblog?
- Does it have the 'immersive' `displayHint`?
etc.
I've attempted to define a sum type called `Layout` to capture these differences, which can be derived from the fields available in the CAPI response.
A given article will fall in the set created by taking the product of `Pillar` and `Layout`, as any article layout can theoretically fall under any of the Pillars. Therefore I've created the …

Article Type - Encapsulate Pillar and Layout

---

src/block.ts
src/lib.ts

This will let us use hex colours from the design system with opacities. Updates link styles to match current templates.
- Add opacity to Anchor hex values

Hex to rgba function

---

src/components/standard/article.tsx
src/components/standard/articleHeadline.tsx

Reduce props sent to headline component using `Article` type. Follow-up to #129.
- Dropped individual props from headline component and derived them instead from `Article`.

Use Article In Headline

---

src/ads.test.ts
src/article.ts
src/components/immersive/article.tsx
src/components/liveblog/byline.tsx
src/components/opinion/article.tsx
src/components/shared/Keyline.test.tsx
src/components/shared/articleBody.tsx
src/components/shared/articleSeries.tsx
src/components/shared/keyline.tsx
src/components/shared/page.tsx
src/components/standard/article.tsx
src/components/standard/byline.tsx
src/components/standard/standfirst.tsx
src/renderer.ts

This solves a few problems:
- The code to parse the data coming in from CAPI is separate from the view code.
- The parsing code lives in one place, `article.ts`, so any changes (for example if the data structure is modified or expanded) should result in minimal code changes.
- Usage of `JSDOM` no longer breaks storybook/client-side code because a) it happens higher up the stack at the parsing stage, not inside React components, and b) its usage has been abstracted into a generic "document parser", which can be replaced by `DOMParser` on the client if needs be.
FYI @oliverlloyd @gtrufitt you may be interested in the `article.ts`, `page.tsx` and `renderer.ts` files.
- Added fields to `Article` to include all data needed to render article
- Moved CAPI parsing code from `block.ts` into …

Expand Article Type

---

src/components/shared/page.tsx

I think this makes more sense as the default for now. However, as we have several variations of English content (thinking about US and AU here), perhaps we want to do one of the following as an alternative:
1. Use `en` to specify English generically, without tying it to a specific region.
2. Editionalise this attribute, so it specifies `en-GB`, `en-US`, `en-AU` etc. for different editions.
As far as I can tell, dotcom seem to do option 1. Is this correct @gtrufitt @shtukas @nicl ?
- Updated the html `lang` attribute to use `GB` instead of `US`.

Language: en-US -> en

---

src/components/opinion/article.tsx
src/components/opinion/byline.tsx
src/components/opinion/cutout.tsx
src/components/opinion/headline.tsx
src/components/shared/author.tsx
src/components/shared/page.tsx
src/components/standard/byline.tsx

This brings the changes made to the 'Standard' article over to Opinion. It also makes `Author` a standalone shared component. It's mostly renaming and re-ordering.
- Updated file structure
- Updated naming conventions
- Extracted Author into shared component
- Removed need to pass CAPI object to Opinion

Refactor Opinion To Match Standard

---

src/components/immersive/article.tsx
src/components/immersive/byline.tsx
src/components/immersive/headerImage.tsx
src/components/immersive/headline.tsx
src/components/immersive/series.tsx
src/components/immersive/standfirst.tsx
src/components/shared/page.tsx

Continuing the work from #138 and #145, this tidies up the immersive article and migrates it over to use the new `Article` type.
**Note:** This is likely to reinstate the bug fixed in #122. As this PR is blocking #146, we've decided to fix that in a follow-up.
- Used new `Article` type
- Improved type hinting for `HeaderImage`
- Removed need to pass `Capi` type to immersives
- Tidied structure and naming of immersive components

Refactor Immersive Article

---

src/ads.test.ts
src/article.ts
src/components/shared/page.tsx
src/renderer.ts

I named the `Block` type poorly, as it doesn't match up with the data structure in the blocks API. This is likely to cause confusion, particularly on the liveblog. This PR renames that type to more accurately reflect its usage in the API.
- Renamed `Block` type to `BodyElement`.
- Updated terminology across the codebase to match.

Rename Block to BodyElement

---

src/article.ts
src/components/immersive/article.tsx
src/components/liveblog/article.tsx
src/components/liveblog/block.tsx
src/components/liveblog/body.tsx
src/components/liveblog/byline.tsx
src/components/liveblog/headline.tsx
src/components/liveblog/keyEvents.tsx
src/components/liveblog/liveblog.stories.tsx
src/components/liveblog/loadMore.tsx
src/components/liveblog/series.tsx
src/components/liveblog/standfirst.tsx
src/components/opinion/article.tsx
src/components/shared/articleRating.tsx
src/components/shared/page.tsx
src/components/standard/article.tsx
src/components/standard/headline.tsx

To bring the liveblog in line with changes made in #138, #145, #147. This should also help to simplify the work @webb04 is doing in #151.
This refactors the `Article` type to narrow it in certain situations:
- Review articles - we *know* that Review articles have a `starRating` field, because the presence of that field is how we define an article as Review. This PR removes the need to pass `starRating` down through the component tree as an optional property: either we're working with a Review article and `starRating` exists, or we're not and we need not include the field.
- Liveblogs - For most article types the blocks API provides a single block for the body, from which we take the `elements` to render the body of the article. However, liveblogs are actually lots of little articles …

Use Article Type on Liveblog

---

src/article.ts
src/components/shared/Keyline.test.tsx
src/components/shared/keyline.tsx
src/components/shared/shared.stories.tsx

Articles with the tags "tone/comment" and "tone/letters" should be rendered as Opinion types (compare dotcom and current app to master with the following article).
http://localhost:8080/australia-news/2020/jan/17/if-the-bushfires-wont-force-climate-policy-change-we-need-to-circumvent-scott-morrison
This logic lives in MAPI: ```def isComment = tagExistsWithId(TagConstants.CommentIsFreeTone) || tagExistsWithId(TagConstants.LettersTone)```
- Refactored `Keyline` to determine styles based on `Layout` rather than a combination of layout and pillar

handle articles with opinion tags

---

src/components/opinion/headline.tsx
src/components/standard/standfirst.tsx

Some changes to closer match the current templates.
- Remove underline in opinion headlines
- Use feature font in standfirst
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/72810776-298a3980-3c56-11ea-884a-de40775a915e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72810784-327b0b00-3c56-11ea-9dfe-4f61d0bd5eaa.png" width="300px" /> |

Opinion styles

---

src/article.ts
src/capi.ts
src/components/immersive/byline.tsx
src/components/immersive/headerImage.tsx
src/components/immersive/standfirst.tsx
src/components/liveblog/block.tsx
src/components/liveblog/byline.tsx
src/components/liveblog/keyEvents.tsx
src/components/liveblog/standfirst.tsx
src/components/opinion/byline.tsx
src/components/shared/author.tsx
src/components/shared/headerImage.tsx
src/components/standard/byline.tsx
src/components/standard/standfirst.tsx
src/renderer.ts
src/server/ssmConfig.ts
src/styles.ts
src/types/functor.ts
src/types/option.ts
src/types/result.ts

Rename the functor `map` function to `fmap`. This lets us:
1. Easily distinguish between types, standard JavaScript arrays and `Option`, `Result` etc
2. Remove ESLint warnings and rule suppression comments throughout the codebase
Would be interested in your opinions on this... we're using functor `map` a lot more with the new CAPI types.

Rename functor map to fmap

---

src/article.ts

Made use of `andThen` to remove an `any` type.
- Rewrote `parseImage` to remove use of any.

Remove Explicit Any

---

config/cloudformation.yaml
src/server/aws.ts
src/server/server.ts

Because it wasn't working in CODE
- use `i` instead of `I` in the SSM configuration (Not in this PR, fixed in the SSM console)
- missing `/` at the end of the SSM path to authorise the loading of keys
- use `EC2MetadataCredentials` instead of `ECSCredentials`. `ECSCredentials` is for lambdas
- better error handling
- access log
| --- | --- |

Mss 1413 more logs

---

config/cloudformation.yaml

So that the app knows what environment it's in at runtime.
I also created a missing SSM parameter

Exporting the environment variables

---

.storybook/preview-head.html
src/client/parser.ts
src/components/standard/article.tsx
src/components/standard/byline.stories.tsx
src/components/standard/headline.stories.tsx
src/components/standard/headline.tsx

The headline stories were failing to build because the type of `Article` had changed (I think this happened in the transition from JSON to Thrift for CAPI types, possibly in in #168). This fixes that problem by correctly mocking the new article. It also fixes a problem where storybook was 404ing for some fonts due to an incorrect path.
In addition it adds some stories for the standard byline, and includes a new client-side parser derived from [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser), which we may use in the future for pages like liveblogs.
- Fix `Article` mocking for headline stories
- Fix font loading for storybook
- Added Byline stories
- Added client-side parser

Fix Storybook and Add Standard Stories

---

src/components/shared/page.tsx
src/renderer.ts
src/server/server.ts

Added a new `Link` http header to show what scripts and css files the apps need to prefetch. Hopefully the caching layers they use or the webview will do this automatically like browsers do. If not, the http header can still be used to manually fetch the resources so that they're available offline.
App requests a standard article and receives the header: 
`Link: <assets/article.js>; rel=prefetch`
We should then assume this JavaScript file is available when the user opens the article (atleast from a home front) and is available offline
- We need to forward these headers in mapi to the apps
- This will change when we serve assets from a more suitable place like s3 (naming of files with hashes and the location)

link prefetch header

---

src/renderer.ts

The Rich link font is too large, use a smaller header and reduce the link font size.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/74332297-59c48400-4d8d-11ea-8511-aacd592161ce.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/74332322-63e68280-4d8d-11ea-983a-cd3e893e6f2e.png" width="300px" /> |

reduce rich link font size

---

package-lock.json
package.json
src/client/article.ts
src/components/standard/byline.tsx
src/date.ts

Re-render dates client side to change to user's timezone.
- Remove moment library
- Added client side code to detect times in the DOM and re-calculate them using `new Date()`. This should reflect their timezone
- We'll need the JavaScript available to avoid a weird change of date (this might be confusing)
- Maybe we should add the user's timezone after the date. A user recently questioned us about this and dotcom show it.

get local times on client

---

.github/workflows/nodejs.yml
.gitignore
.storybook/webpack.config.js
README.md
config/tsconfig.client.json
config/tsconfig.test.json
package-lock.json
package.json
src/components/shared/avatar.test.tsx
src/components/shared/keyline.test.tsx
src/components/shared/tags.test.tsx
src/renderer.test.ts
src/renderer.ts
tsconfig.json
webpack.config.js

It's part of our health OKR to have 75% test coverage on our core parsing logic.
-----
To run: `npm run test`
I've added `renderer.ts` but we can include more files with parsing logic.
The threshold is currently 15% so that the builds don't fail but we should increase this as we add tests.

code coverage

---

config/.eslintrc.js
src/ads.test.ts
src/capi.test.ts
src/capi.ts
src/components/immersive/article.tsx
src/components/immersive/headerImage.tsx
src/components/liveblog/article.tsx
src/components/liveblog/body.tsx
src/components/liveblog/byline.tsx
src/components/liveblog/keyEvents.tsx
src/components/opinion/article.tsx
src/components/shared/headerImage.test.tsx
src/components/shared/headerImage.tsx
src/components/shared/keyline.test.tsx
src/components/shared/keyline.tsx
src/components/shared/page.tsx
src/components/shared/shared.stories.tsx
src/components/standard/article.tsx
src/components/standard/byline.tsx
src/components/standard/headline.tsx
src/components/standard/standfirst.tsx
src/item.ts
src/renderer.ts

Part of the motivation for this work is to standardise how we define the design of content. The concept of a [`DesignType`](https://github.com/guardian/content-api-scala-client/blob/9e249bcef47cc048da483b3453c10dd7d2e9565d/client/src/main/scala/com.gu.contentapi.client/utils/DesignType.scala) has existed for a while, and is used in frontend. We're using a [`Layout`](https://github.com/guardian/apps-rendering/blob/66f93cf1832e7cb1d6f26d8af4579edcb653216b/src/article.ts#L14) type in apps-rendering. These both attempt to solve a similar problem, but are incomplete and are not compatible with one another.
Therefore dotcom-rendering and apps-rendering are attempting to co-ordinate their approaches by introducing a new type (terminology may change):
```ts
interface Format {
pillar: Pillar; …
```

Format and Item Types

---

.storybook/preview-head.html

Storybook was loading italic and/or bold versions of fonts regardless of whether they were specified or not. This meant components were appearing with italic or bold text even when neither of these properties were set.
The problem was that `font-style` and `font-weight` declarations were being given string values inside `font-face` rules, which are not valid. This resulted in the browser picking the incorrect fonts to download.
- Removed quotes from font-style and font-weight

Storybook Italic/Bold Bug

---

src/components/immersive/article.tsx
src/components/immersive/headerImage.tsx
src/components/liveblog/article.tsx
src/components/opinion/article.tsx
src/components/shared/headerImage.test.tsx
src/components/shared/headerImage.tsx
src/components/standard/article.tsx
src/item.ts
src/renderer.test.ts
src/renderer.ts

http://localhost:8080/food/2020/jan/31/bong-bongs-manila-kanteen-london-e2-grace-dent-restaurant-review
It's possible to receive html in image captions. Instead of always returning a string, we should parse the content and render the correct tags.
| --- | --- |
| <img src="" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/74652874-e781e400-517e-11ea-96ad-c0d5d90f3fbf.png" width="300px" /> |

captions can be html

---

config/cloudformation.yaml
src/server/appIdentity.ts

The application name was defaulting to "apps-rendering" when the `App` tag of the ec2 instance is "mobile-apps-rendering".
This misalignment prevented the app from loading the configuration.
This fixes it.

Fix the application name, and the cloudformation

---

src/server/aws.ts

After having a chat with @JamieB-gu we realised the slow start was due to the AWS credentials testing if the code is running within EC2, and timing out.
Now we're looking at if the service is running locally, and if so, directly using the local credentials rather than waiting for the EC2 on to timeout.

Fix slow start

---

package-lock.json
package.json
src/client/article.ts

Content can change on articles like atoms opening, when this happens we should report the placeholder positions to the native layer.
It might be possible to combine video placeholder positions too in this API...

update advert positions

---

src/native/thrift/nativeConnection.ts

To make the Thrift native communication work on Android (in conjunction with this Android PR: https://github.com/guardian/android-news-app/pull/5856
- Changed the definition/names of the bridge functions
- Called the android bridge function with separate params

Change name of the Android bridge function

---

src/components/liveblog/block.tsx

Highlights on liveblogs were cutting off descenders.
- Tweaked padding on highlight
| --- | --- |
| ![before](https://user-images.githubusercontent.com/53781962/74864437-78a3b700-5347-11ea-8499-7da47d14c339.png) | ![after](https://user-images.githubusercontent.com/53781962/74864449-7f322e80-5347-11ea-9df9-8c85cc87ee6d.png) |

Fix Liveblog Highlights

---

src/components/opinion/headline.tsx

Current styles look very weird when some authors don't have a link.
Haven't touched the font sizes as they will probably change when updating the root pixels.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/75043194-8d9f5800-54b7-11ea-96e5-c94dc08ff737.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/75043208-96902980-54b7-11ea-96e4-866bcf556491.png" width="300px" /> |

opinion headline styles

---

src/server/server.ts

We currently filter out content in MAPI so we can remove these additional checks.
It does the best possible job of rendering an article e.g. this article is rendered with a missing atom http://localhost:8080/sport/2020/feb/21/redefining-the-strong-man-tyson-fury-praised-for-openness-on-mental-health

remove support checks as they are now upstream

---

src/native/thrift/nativeConnection.ts
src/native/thrift/protocols.ts

With service name to identify the desired service
Thrift has a meta-protocol that supports serving multiple services across a single link.  Adding support for it will allow us to split the interface that the native layer provide into logically separate services without needing to create a different webview<->native postMessage connection.  
The Thrift spec allows an arbitrary string to identify a service, but we are choosing to use the service name as defined in the `thrift` file.

Use multiplexed thrift

---

.github/workflows/nodejs.yml
artifact.json
config/cloudformation.yaml
package-lock.json
package.json
src/components/shared/page.tsx
src/server/assets.ts
src/server/server.ts
tsconfig.json
webpack.config.js

Use `contenthash` to be able to invalidate cached JavaScript bundles on device.
This does require client content being built before the server is started...
- Adds content hash to generated JavaScript files
- Creates json mapping from script to hashed script name
- Reads mapping on server launch and passes it into the rendering logic

Hashed JavaScript bundles

---

.storybook/preview-head.html
src/components/headline.tsx
src/components/shared/page.tsx

Previously we set the root font size to `62.5%`. This undoes that to allow the font size to revert to the browser default. This should make it easier to integrate with designs and the design system, and possibly simplify work being done to adjust the font size in the native layers.
This also removes font size rules that were being applied globally to the body. We would like to make our CSS more granular and apply this at the component level.
I've also updated the universal headline component introduced in #202 to use the correct design system sizes, which now work correctly with our root font size.
**Note:** This will break some of the scaling on articles until I can migrate the remainder of our components across to the design system scaling.
FYI @SiAdcock @jeanlauliac 
- Removed font …

Reset Root Font Size

---

src/components/headline.stories.tsx
src/components/standard/byline.stories.tsx
src/components/standfirst.stories.tsx
src/components/starRating.stories.tsx

A missing field in the mock item was causing storybook to crash.
**Note:** I'm aware that this mock is repeated a lot. Will be extracting it out soon 🙂
- Added mock for `shouldHideReaderRevenue` field

Fix Storybook Crash

---

package.json

Improving the storybook experience. Relevant docs [here](https://storybook.js.org/docs/configurations/cli-options/).
- Specified a consistent port (previously it was randomised)
- Prevented it from opening browser windows

Configure Storybook

---

src/components/headline.tsx
src/components/shared/epic.tsx
src/components/standfirst.tsx
src/components/starRating.tsx
src/styles.ts

For a while we've been using a couple of functions to convert design system spaces (in px) to rems. We recently [pushed this upstream](https://github.com/guardian/source/pull/236) to the design system. Now we can use the design system implementation.
**Note:** This is reliant on #218.
- Deleted `pxToRem` and `spaceToRem`
- Updated all uses of `spaceToRem` to `remSpace`
- Tidied up epic imports

Migrate To REM Space 🌌

---

src/components/headline.tsx
src/components/shared/epic.tsx
src/components/standfirst.tsx
src/components/starRating.tsx
src/styles.ts

*Redo of #219, this time against master!*
For a while we've been using a couple of functions to convert design system spaces (in px) to rems. We recently [pushed this upstream](https://github.com/guardian/source/pull/236) to the design system. Now we can use the design system implementation.
**Note:** This is reliant on #218.
- Deleted `pxToRem` and `spaceToRem`
- Updated all uses of `spaceToRem` to `remSpace`
- Tidied up epic imports

Migrate To REM Space... Again 🌌

---

src/components/paragraph.stories.tsx
src/components/paragraph.tsx
src/renderer.ts

Give the `Paragraph` component its own file. This helps to scope styles directly on the component, and fits in with our other component conventions, including storybook.
- New file for Paragraph
- Added styles directly to para component, w/ design system fonts
- Updated pxToRem to use 16px as root font size
- Added stories for Paragraph

Paragraph Component

---

src/components/author.stories.tsx
src/components/standard/byline.stories.tsx
src/components/standfirst.stories.tsx
src/lib.test.ts
src/lib.ts
src/types/result.test.ts
src/types/result.ts

I've written conversions from `Result` to `Option` using `either` at least three times. Therefore I've decided to create a `toOption` method on `Result` to handle this.
I've also written out a test file to cover `Result`. In writing these tests I found a use for the `identity` function, so I've added that to `lib` and included some tests there too.
cc @gtrufitt 
- Added a `toOption` method to `Result`
- Migrated some usages of `either` to `Option`
- Added `identity` function and corresponding tests
- Added tests for `Result`

toOption Method On Result

---

src/styles.ts

This adds an additional URL with a custom URL scheme, `font://`, to the `font-face` element. This allows iOS to handle the custom URL scheme and return a local font. See https://theguardian.atlassian.net/browse/GLA-1776.
- Added the new `font://` URL before the relative URL

Add a local font URL for iOS

---

src/client/article.ts

We're inserting ads before checking if the user is premium. This PR stops that happening.
- Removed a call to insert ads before checking if a user is premium

Don't insert ads until after checking premium status

---

package-lock.json
package.json
src/client/article.ts
src/native/nativeApi.ts

Create new npm package with a more consistent name to other repos (bridget and bridget-swift)
I've made the changes to publish the TypeScript files to `bridget-typescript` inside the `bridget` repo.

rename npm package

---

src/client/article.ts

Sometimes the ad positions change without a DOM mutation e.g. fonts loading. This should correctly reposition ads.

update ads when fonts loaded

---

src/client/article.ts
src/components/bodyImage.tsx
src/components/image.ts
src/components/paragraph.tsx
src/components/shared/articleBody.tsx
src/renderer.test.ts
src/renderer.ts

Creating standalone components for images in general, and the `BodyImage` in particular. This also encompasses greater integration with the design system.
**Note:** The tests are probably going to fail because of this error: `"global" coverage threshold for branches (75%) not met: 74.92%`... They are actually all passing, it's just the coverage that's unhappy.
cc @SiAdcock I've created a new SVG for the triangle on image captions: around line 62 in `BodyImage`.
- Removed `BodyImage` and `FigureElement` from `renderer`
- Created new components: `Image` and `BodyImage`
- Migrated image helpers (e.g. `srcset`) into component
- Updated `Paragraph` to handle text padding directly

Image and BodyImage Components

---

package-lock.json
package.json

node-riffraff-artifact had a small bug that lead to the assets being uploaded to a path on s3 prefixed by whatever local structure we have.
This didn't prevent us to move forward but it's not very clean to have our local directory structure being reflected on s3.
So I've fixed the bug in [node-riffraff-artifact](https://github.com/guardian/node-riffraff-artifact/pull/16), @AWare released it, and this now the PR to upgrade to the latest version.
I've also updated the fastly config in PROD and CODE even though this isn't merged because YOLO.

Upgrade node riffraff artifact to the latest version

---

src/components/immersive/byline.tsx
src/components/liveblog/byline.tsx
src/components/liveblog/headline.tsx
src/components/liveblog/series.tsx
src/components/liveblog/standfirst.tsx
src/components/opinion/byline.tsx
src/components/shared/commentCount.tsx
src/components/shared/headerImageCaption.tsx
src/components/shared/tags.tsx
src/components/standard/byline.tsx

Updating the root element font size caused some UI 
- Byline dates
- Liveblog (headline, series)
- Tags
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/76334377-e3169a00-62ea-11ea-8654-24e505080b4d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76334443-f9245a80-62ea-11ea-8c46-01f05068a60e.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76334485-04778600-62eb-11ea-8021-98ea80566382.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76334512-0ccfc100-62eb-11ea-8003-c9edebdaf7fb.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76334548-18bb8300-62eb-11ea-92f6-2ae0eb60c505.png" width="300px" /> | …

various font size updates

---

.storybook/preview-head.html
src/components/shared/page.tsx

Our headline font was named differently to the one in the design system, which meant it wasn't loading and we were falling back to Georgia instead. For more information see [this design system PR](https://github.com/guardian/source/pull/291).
- Renamed "Guardian Headline" to "GH Guardian Headline" for the app and for storybook
| --- | --- |
| ![headline-before](https://user-images.githubusercontent.com/53781962/77410162-64256500-6db2-11ea-8057-2df74605ca87.jpg) | ![headline-after](https://user-images.githubusercontent.com/53781962/77410154-62f43800-6db2-11ea-9f2e-7836950629fb.jpg) |

Rename Headline Font Family

---

src/item.ts

I've never seen an Opinion article with news pillar styles. It is possible to use sports pillar colours: http://localhost:8080/football/commentisfree/2019/dec/18/mesut-ozil-china-row-western-brands-be-warned-self-censorship-wont-protect-you
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/77451581-c26f3980-6dec-11ea-9e44-9ba18676b056.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/77451616-ce5afb80-6dec-11ea-80f9-8b8e6ad240a2.png" width="300px" /> |

default to opinion when news pillar used

---

src/components/paragraph.tsx
src/components/shared/articleBody.tsx
src/components/standfirst.tsx
src/renderer.test.ts
src/renderer.ts

Some paragraphs outside of the article body have their styles overridden by component styles.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/77767446-fe96da00-7038-11ea-89b3-5ec583b071ad.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/77767470-08204200-7039-11ea-8a9b-85c5e762c9e6.png" width="300px" /> |

make paragraph styles specific to body

---

src/capi.test.ts
src/capi.ts

Request only what we need from Capi. This is only for local development but it should match prod in Mapi (PR in progress)

only request necessary CAPI fields

---

src/renderer.ts

Adding underlines will make links more accessible. This grey is the same used on dotcom.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78162468-d21afd80-743e-11ea-81f2-924216c5f4c3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78162492-d9420b80-743e-11ea-959e-e888e5183eeb.png" width="300px" /> |

add underlines to anchors

---

src/components/bodyImageThumbnail.tsx
src/components/image.ts

Thumbnail images can have captions too. This will probably conflict with the gallery work and we might be able to refactor it afterwards.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78157630-1787fc80-7438-11ea-8dfe-dd20c7ce4eda.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78157673-279fdc00-7438-11ea-9c04-12126cfdad00.png" width="300px" /> |

add figcaptions to thumbnail images

---

package-lock.json
package.json
src/renderer.ts

- Less space between bullet and text
- bullet points slightly closer (matches dotcom)
- Small increase to line-height in standfirst (matches dotcom)
- Smaller h2 font size (matches dotcom)
- Replace all bullets in transform. Some article use bullet points as article breaks http://localhost:8080/world/2020/apr/01/golden-eagles-us-dying-why
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78140967-b7d32680-7422-11ea-8ac0-1d36c4a75097.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78140985-befa3480-7422-11ea-8c67-e661d5613ea2.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/78141008-c6b9d900-7422-11ea-9b20-522dabf4511b.png" width="300px" /> | <img …

line height tweaks

---

package-lock.json
package.json

GH reported an issue w/ `acorn`, a transitive dependency of `storybook-deployer`. This bumps the latter to deal with the former.
- Bumped `storybook-deployer` to latest

Bump storybook-deployer

---

src/components/opinion/cutout.tsx
src/components/shared/keyline.tsx

Cutout images were low quality compared to dotcom and templates. Also added some more space between the top of the cutout and the headline.

increase cutout image width

---

config/.eslintrc.js
src/components/byline.tsx
src/components/shared/epic.tsx
src/components/shared/leftColumn.tsx
src/components/shared/page.tsx
src/item.ts
src/renderer.ts

It allows the linter to do more for us: keeping our code style more consistent and catching possible bugs. It also brings our lint rules more in line with DCR.
**Note:** It might be helpful to look through this commit-by-commit to break out refactorings from actual changes. Each of the points in the section below below corresponds to a specific commit.
- Tidied up the `eslintrc` file
- Added the ESLint recommended rules and fixed errors
- Added a type-checked version of the recommended rules and fixed errors

Expand ESLint Ruleset

---

src/components/avatar.tsx
src/components/byline.tsx
src/components/commentCount.tsx
src/components/follow.test.tsx
src/components/follow.tsx
src/components/headline.tsx
src/components/shared/keyline.test.tsx
src/components/shared/keyline.tsx
src/components/shared/page.tsx
src/components/standfirst.tsx
src/components/starRating.tsx
src/format.ts
src/item.test.ts
src/item.ts

Breaking `Format` out into its own module. There are a few reasons why:
- Improve code clarity
- Less reason to import the entire `item` module in rendering code, which may reduce client bundle sizes
- Preparation for future changes, including integration with the [guardian/types](https://github.com/guardian/types) repo
- Pulled `Format` type into its own module
- Updated imports
- Dropped `SpecialReport` and `GuardianLabs` from `Design` since we don't think they're used

Separate Format Module

---

src/components/shared/page.tsx
src/item.ts
src/renderer.test.ts
src/renderer.ts

Chrome lighthouse suggested two accessibility improvements. 
- Add title to interactive iframes
- Increase maximum scale to recommended amount
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/79335935-c3dae000-7f1a-11ea-9b11-e12ea2faea4f.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/79335967-d1906580-7f1a-11ea-80a4-3dd4c779eaa5.png" width="300px" /> |
I'm wondering if we might have to revert the maximum scale as it might loose the native feel.

add title to interactive iframes and increase maximum scale

---

src/capi.test.ts
src/capi.ts

We need `displayHint` to tell us if an article is immersive.
- Added `displayHint` to list of fields requested from CAPI.

Add displayHint To Fields

---

package-lock.json
package.json

Keeping TypeScript up-to-date. The release notes are [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html).
- Bumped TypeScript to 3.8.3

TypeScript 3.8

---

src/types/option.ts
src/types/result.ts

Used JSDoc to provide documentation for our data types: `Option` and `Result`. This is picked up by VSCode via Intellisense and *should* also work in IntelliJ (although I haven't tested it).
Derived from [this issue](https://github.com/guardian/types/issues/5).
- Added JSDoc comments to `Option`
- Added JSDoc comments to `Result`

Document Data Types

---

src/ads.test.ts
src/components/byline.stories.tsx
src/components/commentCount.stories.tsx
src/components/follow.stories.tsx
src/components/follow.test.tsx
src/components/headline.stories.tsx
src/components/liveblog/liveblog.stories.tsx
src/components/shared/headerImage.test.tsx
src/components/standfirst.stories.tsx
src/components/starRating.stories.tsx
src/item.ts
src/pillar.ts
src/renderer.test.ts
src/storybookHelpers.ts
src/styles.test.ts

Although CAPI still refers to it as "arts", the Pillar is really called "culture". It's called this in the nav and a number of other places, including [DCR](https://github.com/guardian/dotcom-rendering/blob/ff97d314f091c57dd297ca5e8f8bced078b672a9/src/lib/pillars.ts#L25).
Also, the convention for types in general and [enums in particular](https://www.typescriptlang.org/docs/handbook/enums.html) is to use titlecase. This brings us into line with the [types repo](https://github.com/guardian/types/blob/3e70de6fb9443650ec14f9e8c9d99a31e5d1f078/Format.ts).
- Migrated "arts" to "culture"
- Made Pillars titlecase

Arts To Culture And Titlecase Pillars

---

package-lock.json
package.json
src/format.ts

It would be good to start using the centralised [types repo](https://github.com/guardian/types) that we created. This does that, and it seems to work! What do people think about this?
**Note:** Long term we'd want to get rid of the `format` module and import this directly. I've done this for now to try it out.
- Added `@guardian/types` as a dependency
- Replaced the types in the `format` module with imports from the types repo

Use @guardian/types

---

src/components/shared/page.tsx

When a webview containing an article first loads, we need to know if the user has specified an alternate font size for the content. In order for this to be performant and reliable (i.e. to happen quickly, before first paint but without noticeable delaying it, and consistently on every article render) we've decided it's best not to rely on JavaScript (via the native comms layer). Therefore we're going to make a (render-blocking) request for a very small stylesheet in the `<head>`, which we expect the native layers to intercept and use to return a stylesheet of the form:
```css
html {
font-size: 16px;
}
```
We've used the custom `native://` protocol for this because [`WKWebView`](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/2875766-seturlschemehandler) doesn't …

Native Stylesheet

---

src/pillarStyles.ts
src/styles.test.ts

Brings the news colours into line with the other pillar palettes.
- Used `news[800]` rather than `neutral[97]` for news `soft`
Before | After
-|-

Consistent News Colours

---

src/ads.test.ts
src/client/liveblog.ts
src/components/liveblog/article.tsx
src/components/liveblog/body.tsx
src/components/liveblog/metadata.tsx
src/components/liveblog/standfirst.tsx
src/components/media/byline.tsx
src/components/shared/page.tsx
src/components/standfirst.tsx
src/renderer.test.ts
src/renderer.ts

The functions in the renderer now take the wider `Format` type instead of just `Pillar`. This reflects the fact that `Format` describes everything that's needed to express the design of a piece of content. It also paves the way for some upcoming work that relies on this fact.
- Updated `renderer` functions to take `Format`
- Updated corresponding components to take `Format`

Renderer Takes Format

---

src/capi.ts
src/components/bodyImage.tsx
src/components/bodyImageHalfWidth.tsx
src/components/bodyImageThumbnail.tsx
src/components/standfirst.tsx
src/image.ts
src/item.ts
src/renderer.ts

- Support new image role "halfWidth"
- Remove old anchor styles on immersive articles
- Render as immersive if an article contains a displayHint of "photoEssay"
- Abstract `bodyImageProps`
`HalfWidthBodyImage`

support photo essay articles

---

src/components/anchor.tsx
src/components/figCaption.stories.tsx
src/components/figCaption.tsx
src/components/shared/page.tsx
src/renderer.test.ts
src/renderer.ts

Consolidating the caption rendering code in the `FigCaption` component and simplifying the `renderer` module. Also brings the media captions more in line with dotcom. This change is possible in part due to the splitting out of captions and credits in #288.
- Migrated caption rendering functions to `FigCaption`
- Updated media caption styles to match dotcom
- Pulled `Anchor` component into own module
- Allowed `renderAll` to handle media content
| --- | --- |
| ![before](https://user-images.githubusercontent.com/53781962/80228802-698efd00-8647-11ea-8255-84e583780bad.jpg) | ![after](https://user-images.githubusercontent.com/53781962/80228785-6431b280-8647-11ea-9b76-6e57888a13a7.jpg)

Consolidate Caption Rendering In FigCaption

---

src/server/decoders.ts
src/server/server.ts

Abstracted the decoding of Thrift types into TypeScript types into a `decoders` module. This will hopefully make them easier to re-use in some upcoming changes, and keep the `server` module more tightly focused on the "request-response" cycle.
- Wrapped Thrift decoding into `decoders` module

Thrift Decoders

---

src/components/anchor.tsx
src/components/figCaption.tsx

- Improve contrast of anchors on media pages 
- Use strong elements to keep inline display
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/80586372-c2c2ac00-8a0c-11ea-9d26-26037e152433.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/80586445-e2f26b00-8a0c-11ea-9501-515f2a236370.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/80586473-ebe33c80-8a0c-11ea-9035-8e5d1de4cc05.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/80586500-f4d40e00-8a0c-11ea-8129-73f25945b2c5.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/80586524-fbfb1c00-8a0c-11ea-8e95-759476fecb57.png" width="300px" /> | <img …

use inverted colour for anchors on dark backgrounds

---

src/components/advertisementFeature/article.tsx
src/components/byline.stories.tsx
src/components/byline.tsx
src/components/figCaption.tsx
src/components/follow.tsx
src/components/headline.stories.tsx
src/components/headline.tsx
src/components/paragraph.stories.tsx
src/components/paragraph.tsx
src/components/shared/articleBody.tsx
src/components/shared/page.tsx
src/components/standfirst.tsx
src/renderer.ts
src/styles.ts

Render AdvertisementFeatures. Also known as Guardian Labs.
- Use textSans font
- Use labs colours rather than pillar colours
- Remove tags and follow options
- Added lab stories

render advertisementFeatures

---

.github/workflows/snyk.yml

Schedules Snyk to run every day at 10am UTC. This is an experiment to see how this works for us, and what the alerting is like.
If this works well we might consider using this _instead_ of the PR check. Reported failures are often for dependencies also present in `master` (due to a new issue in the Snyk database) rather than PR changes.
**Note:** For an example of the Snyk check failing for PRs with no dependency changes, see the checks on _this_ PR.
- Added a schedule trigger for Snyk every day at 10am UTC

Snyk On A Schedule - GitHub Actions

---

.github/workflows/snyk.yml

Making use of GitHub Actions to run [`snyk monitor`](https://support.snyk.io/hc/en-us/articles/360003919937-Getting-started-with-the-CLI), which will update our dashboard. This brings our setup into line with recent [changes on MAPI](https://github.com/guardian/mobile-apps-api/pull/1591).
It solves a problem where Snyk would report issues against a PR even when there were no alterations to dependencies. In these cases it's more accurate to treat this as a problem on `master` and act accordingly.
**Note:** @webb04 this probably covers the changes in #309.
- Removed Snyk from PR checks, now runs on schedule
- Used checkout action v2
- Used monitor with org and project
- Set timeout

Snyk Monitor With GitHub Actions

---

src/ads.test.ts
src/bodyElement.ts
src/capi.ts
src/components/liveblog/body.tsx
src/components/liveblog/keyEvents.tsx
src/components/shared/page.tsx
src/item.test.ts
src/item.ts
src/liveBlock.ts
src/renderer.test.ts
src/renderer.ts
src/types/docParser.ts

The `Item` module is quite large and unfocused. This splits out some of the data types into more tightly focused modules of their own.
These changes will help to enable some upcoming work on the liveblog API.
- Created `bodyElement` module
- Created `liveBlock` module
- Created `docParser` module to house the `DocParser` type
- Migrated the CAPI date parser to the `capi` module
- Updated imports

Split Up Item Module

---

.github/workflows/nodejs.yml

We only target Node v12.
- Removed Node.js version matrix

Remove Node.js Matrix In Validate Action

---

.github/workflows/chromatic.yml
.github/workflows/nodejs.yml

Supposedly faster and won't alter `package-lock.json`. Documentation found [here](https://docs.npmjs.com/cli/ci.html).
FYI @gtrufitt @oliverlloyd @liywjl @SiAdcock 
- Updated validation job to use `npm ci`
- Updated Chromatic job to use `npm ci`

Use 'npm ci' For GitHub Actions

---

src/components/anchor.stories.tsx

Removing the `<span>` as it isn't needed
@JamieB-gu sorry I only read your comment after I had merged

AR-18: Remove span from anchor component

---

src/components/headline.tsx
src/editorialPalette.ts
src/editorialStyles.ts

A speculative PR based on our conversation about an editorial colour palette. I'm not sure about the API here so I'd appreciate some feedback 🙂
This creates some simple functions to lookup headline font and background colours, and the border colour based on the `Format` type. I've also added some functions to generate the next level above this, i.e. CSS declarations for font and background colour based on the `Format` type.
- Created editorialPalette module
- Functions to get headlineFont, headlineBackground and border colours
- Functions to apply color and background declarations
- Applied new palette functions to `Headline` component

Editorial Palette

---

src/components/opinion/article.tsx
src/components/standfirst.tsx
src/renderer.ts

- Removed extra headline padding
- Increased thinHeadline standfirst font size (now matches dotcom)
- Removed underlines in standfirst
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82079610-07239c80-96db-11ea-8920-4e0047b66e49.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82079626-0e4aaa80-96db-11ea-8ef8-623d9b0bd9c0.png" width="300px" /> |

opinion style updates

---

src/components/blockquote.tsx
src/renderer.ts

The current apps and dotcom have some specific blockquote styles to make them stand out. We can convert the icon to an SVG when the existing ticket gets picked up.
| Before | After light mode | After dark mode |
| --- | --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82461613-8ab20480-9ab2-11ea-8253-86c142a2c283.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82461662-97cef380-9ab2-11ea-911c-0d4af082b470.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82461707-a3221f00-9ab2-11ea-9b00-abb398f6c2b2.png" width="300px" /> |

add blockquote component with styles

---

src/components/bodyImage.tsx

Recommended by lighthouse best practices audit.
Would be good to try out the latest audits in version 6 https://web.dev/lighthouse-whats-new-6.0/.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82471463-a3c0b280-9abe-11ea-9607-6be801bc9efd.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82471471-a6230c80-9abe-11ea-9d13-b0bdff5363e8.png" width="300px" /> |

use object fit to keep aspect ratio of images

---

src/item.ts

This interface extends the `Fields` interface above, which already includes the `shouldHideReaderRevenue` property.
- Removed duplicate `shouldHideReaderRevenue` field

Remove Redundant Interface Field

---

src/renderer.ts

We were providing invalid anchors without href attributes.

add href to standfirst link

---

src/bodyElement.ts
src/components/atoms/interactiveAtom.tsx
src/date.ts
src/item.ts
src/lib.ts
src/liveBlock.ts
src/renderer.test.ts
src/renderer.ts
src/server/paramParser.ts
src/server/server.ts
src/types/jsonSerialisable.ts
src/types/option.ts

This adds an endpoint for retrieving liveblog updates, at `/<articleId>/live-blocks`, with a JSON response of the form:
```ts
type LiveUpdates = {
newBlocks: LiveBlock[];
updatedBlocks: LiveBlock[];
}
```
Currently the endpoint will only work for `GET` requests in local development; I haven't added a `POST` equivalent for MAPI to hit yet. The client also hasn't been updated to use this endpoint. Both of these changes will come in later PRs.
FYI @oliverlloyd @gtrufitt 
- Introduced `JsonSerialisable` type
- Added converter to make `BodyElement` `JsonSerialisable`
- Migrated `isElement` to `lib` for reuse
- Added converter to make `LiveBlock` `JsonSerialisable`
- Added functions to `liveBlock` to retrieve recent updates
- Made JS in `InteractiveAtom` an `Option`
- Added module for parsing …

Liveblog Updates Endpoint

---

src/renderer.test.ts
src/renderer.ts

- We were missing the attribution on blockquotes
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82903399-cc322c00-9f58-11ea-8ab3-ccc31ef1464d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82903421-d48a6700-9f58-11ea-8412-4576b39ba095.png" width="300px" /> |

add cite to blockquote

---

src/renderer.ts

- Makes whole grey box linkable
- Removes kicker colour on link (closer to current apps) as the related content may be a different pillar to the current article @benwuersching

wrap related content in anchor

---

src/styles.ts

This is the only suggestion from lighthouse to reach 100% performance.
It will display system fonts until our fonts have loaded.

use font display swap

---

src/components/byline.tsx

`bylineHtml` only provides us with a relative profile url. Changing to the absolute path ensures iOS and Android can correctly link to profile pages.

format byline links

---

src/bodyElement.ts
src/capi.ts
src/client/liveblog.ts
src/components/liveblog/article.tsx
src/components/liveblog/body.tsx
src/components/shared/page.tsx
src/date.ts
src/liveBlock.ts
src/server/server.ts

This begins the work to request new live blocks on the client. These changes are quite contained: on page load the JS will make a request to get the most recent 7 blocks (which matches what the server has rendered for the page). It will then put the liveblog body under the control of client-side React, using the blocks retrieved as the data.
This is a follow-on from #335, and fixes the client-side rendering that was temporarily disabled in that PR. It also temporarily removes client-side hydration, hardcoding the `Format` and total blocks for now. A fix for *this* will come in a further PR; it requires some restructuring that would balloon the size of these changes.
**Note:** I'm not particularly happy with the conversions from JSON applied here; they create the potential for runtime …

Live Blocks On Client

---

src/components/figCaption.tsx
src/components/headerImage.tsx
src/components/headline.tsx
src/components/series.tsx
src/components/standfirst.tsx
src/editorialPalette.ts

- Opinion colour for Opinion headline
- Only use heading caption styles for media articles
- Immersive headline left padding on wide breakpoint
- Reduce height of header image so that the bottom navbar doesn't block the top of the headline
- Reduce immersive standfirst font size slightly and use `renderStandfirstText`
- Add min height to immersive headlines to handle short headlines
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82557506-c3f67d00-9b63-11ea-9416-5360c948ca6e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82557580-e1c3e200-9b63-11ea-982e-4bf9f5c53182.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/82557598-eab4b380-9b63-11ea-8906-d6d9b5c5b1df.png" …

style tweaks for immersive articles

---

src/styles.ts

This may improve performance slightly but there is a noticeable jump on every article load.
If we cache fonts and pre-warm the cache this shouldn't be necessary.
There's other options too but I think they'll still cause layout jumps for most pages https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

remove font display swap

---

src/editorialPalette.ts

This matches the logic in `page.tsx`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/83250488-18bb7880-a1a0-11ea-974d-b4bd557aa29c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83250645-61733180-a1a0-11ea-96f6-c3de4538501d.png" width="300px" /> |

use opinion background for all comment designs

---

package-lock.json
package.json

I was seeing a weird issue where the build crashed on Node 12.17.0 due to an exports problem. Possibly related to the issue @nicl was seeing in [this PR](https://github.com/guardian/contributions-service/pull/138) (read the commit history). Updating `babel` fixed this.
- Bumped `babel` dependencies to `7.10.x`

Babel 7.10.x

---

package-lock.json
package.json
src/server/csp.ts
src/server/page.tsx
src/server/server.ts
webpack.config.js

CSP's are important for security; they limit what resources (scripts, styles, iframes etc.) are accepted by your page. For a more detailed explanation see [this MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
This implements a CSP using the `<meta>` tag, as I'm not sure the HTTP header will play well with the way iOS inserts the HTML string into the webview (happy to be told otherwise though @faresite).
There are a few techniques used here:
- I've set [`default-src` to `'self'`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Example_1), so any resources not explicitly described in the policy will only be accepted from our domain (MAPI)
- The interactives domain is allowed to load styles, scripts and fonts, and make AJAX requests (via …

Add Content Security Policy

---

src/renderer.ts

This is the current behaviour in dark mode apps. There must be some JavaScript setting inline padding styles for some interactive atoms, so I've needed to use `!important` there.
- Adds a white background to interactive atoms on standard articles (not type: Interactive) in dark mode
- Adds white background to embeds in dark mode
- adds .5rem padding to these elements in dark mode
| Embed | Interactive atom on standard article |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82997295-19b4a480-9ffe-11ea-90b5-3b38228511ad.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82997322-20431c00-9ffe-11ea-83b4-97fbd782e440.png" width="300px" /> |
Dark mode is now supported in both Android and iOS live apps. This fallback ensures …

add white background and padding to interactive atoms and embeds in dark mode

---

src/server/csp.ts

Updates the CSP to allow images from multiple subdomains of `guim.co.uk`; interactives make use of these, as flagged by @webb04.
- Updated CSP to allow images from `https://*.guim.co.uk`
| --- | --- |
| ![guim-before](https://user-images.githubusercontent.com/53781962/83628100-e2ab3980-a58f-11ea-9b48-a974ad15523a.png) | ![guim-after](https://user-images.githubusercontent.com/53781962/83628092-dfb04900-a58f-11ea-97c7-b837e11c9469.jpg) |

Image From *.guim.co.uk

---

src/renderer.ts

https://www.theguardian.com/world/2020/jun/03/covid-19-surgisphere-who-world-health-organization-hydroxychloroquine
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/83635107-8d752500-a59b-11ea-8dfe-58baab08317c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83635121-949c3300-a59b-11ea-86cb-c6f7f3e87a92.png" width="300px" /> |

handle long words and following ul elements

---

src/components/headline.stories.tsx
src/components/standfirst.stories.tsx
src/components/starRating.stories.tsx
src/fixtures/item.ts

Reduces duplication in our storybook files. Some inspiration taken from DCR's use of fixture files.
- New fixtures file to generate `Item` data structures
- Updated `headline`, `standfirst` and `starRating` to use `Item` fixtures

Introduce Fixture Module For Item

---

tsconfig.json

We've been bitten a few times by macOS's filesystem case insensitivity. This option *should* solve that problem.
See [the docs](https://www.typescriptlang.org/v2/en/tsconfig#forceConsistentCasingInFileNames) for more information.
FYI @oliverlloyd @SiAdcock @jonathonherbert @gtrufitt 
- Enabled `forceConsistentCasingInFileNames` in `tsconfig.json`

TS Consistent Filename Casing

---

src/components/avatar.tsx
src/components/liveblog/avatar.test.tsx
src/components/metadata.tsx
src/components/opinion/cutout.tsx
src/contributor.ts

Use the `<Img />` component for cutout and avatar images. This way we can get the benefits of the picture element, the srcset and dpr queries.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/83642359-a59e7180-a5a6-11ea-8165-c7adbe5c5a89.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83642382-ae8f4300-a5a6-11ea-8f11-856cf353b474.png" width="300px" /> |

Use image component for avatar and cutout images

---

package-lock.json
package.json

Keeps our dependencies up-to-date.
- Bumped `webpack` to v4.43.0
- Bumped `webpack-cli` to v3.3.11
- Bumped `webpack-dev-server` to v3.11.0

Bump Webpack To v4.43.0

---

src/components/img.ts
src/components/liveblog/avatar.test.tsx
src/contributor.ts
src/image.test.ts
src/image.ts
src/renderer.test.ts

We only want body and header images in the native slideshows.

Remove launch slideshow class from contributor images

---

src/components/media/article.tsx
src/components/media/byline.tsx
src/renderer.ts

We probably want to reuse some of the parsing logic and components used in article bodies at some stage.
This fixes some current style issues.
- Align headline with series and standfirst
- Use white colour in byline
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84037099-04446080-a996-11ea-9d76-bfa14909a930.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84037131-0d353200-a996-11ea-8a46-f7a5d7a1f781.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/84053913-8048a380-a9aa-11ea-8126-fbe16820c538.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/84053928-876fb180-a9aa-11ea-8bd2-b0795d3d023f.png" width="300" /> |

media style fixes

---

src/components/avatar.tsx
src/components/bodyImage.tsx
src/components/bodyImageHalfWidth.tsx
src/components/bodyImageThumbnail.tsx
src/components/figCaption.tsx
src/components/headerImage.tsx
src/components/img.ts
src/components/standfirst.tsx
src/image.ts
src/renderer.ts

- Pass `format` into image component to use a dark background on media pages
- Reuse bullet point sizes on gallery articles
- Make headers `display: block`

Dark image backgrounds on media pages

---

src/server/page.tsx

This is recommended by lighthouse for accessibility but we have other features like text size increasing and galleries (pinch and zoom)
At the moment you can pinch and zoom, this will misalign adverts and other native content.

disable increasing scale

---

src/components/liveblog/headline.tsx
src/components/liveblog/standfirst.tsx

- Use headline font for liveblog standfirsts
- Add margin underneath liveblog headline
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84642503-7831bc00-aef4-11ea-8267-276b2779c9c2.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84642521-8089f700-aef4-11ea-8884-360128df87cd.png" width="300px" /> |

match standfirst font used on other articles

---

src/client/article.ts
src/client/nativeCommunication.ts
src/styles.ts

Use click instead of touchstart. Touchstart is more performant and fires quicker but it's easy to trigger when scrolling down the article.
If we detect any slowness related to the Bridget APIs we should probably optimise the thrift message handling code on iOS/Android and apps-rendering.

use click rather than touchstart

---

src/components/img.ts

- Thumbnail images can be round avatars so we shouldn't add a background colour
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84642813-e8404200-aef4-11ea-823f-011958020e5f.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84643106-4bca6f80-aef5-11ea-912a-87210ddad3f9.png" width="300px" /> |

remove background colour on thumbnail images

---

package.json

This is pretty handy, saves you running the entire test suite repeatedly whenever you're writing tests 🙂.
- Added `test:watch` script

Jest Watch

---

src/components/img.ts
src/components/liveblog/avatar.test.tsx
src/contributor.ts
src/image.test.ts
src/image.ts
src/renderer.test.ts

Only show images in the lightbox/slideshow if their width is greater than `620`. Brings AR into line with the [logic on dotcom](https://github.com/guardian/frontend/blob/2f8b53c7bac3a9c1933837d93a54809661499064/common/app/model/content.scala#L514).
- Applied the slideshow class for `width > 620`
- Removed the `launchSlideshow` property from `Image`

Filter Lightbox/Slideshow By Width

---

src/renderer.ts

Profile links in immersive standfirsts (bylines can be inside) go to https://mobile.guardianapis.com/profile/steve. If we rewrite the relative links to be absolute dotcom links, the apps can handle them and display the author pages.
This might be a bit brittle, so we could:
- Redirect to dotcom in MAPI
- Add logic on iOS/Android to recognise `/profile/<NAME>` links
- Clean all the html from capi (what happened to sharing the cleaner with dotcom?)
http://localhost:8080/society/2020/jun/11/we-locked-down-a-week-early-the-scottish-care-home-with-no-coronavirus-cases

handle another case of linking to author profiles

---

src/server/page.tsx
src/server/server.ts

To enable the native side of the apps to access to the targeting data.
- Use the RenderingRequest type in the `page` function
- Dump the targeting params in a script tag
No change (promise!)

Dump the ad targeting params into a script tag

---

package-lock.json
package.json
src/client/nativeCommunication.ts
src/lib.ts
src/server/page.tsx

To pass all the required ad targeting data to render the ads
- Bump Bridget (no one got hurt)
- Parse the targeting data and send it to the native layer
I've "memoised" the function that loads the ad targeting data such that if it's called a second time it doesn't need to parse the JSON again.
Hasn't changed!

Pass the targeting data to the native side

---

src/components/shared/tags.tsx

The tags on this article were overflowing, causing a white space to the right of the article.
This PR uses ellipsis for long tags.
https://www.theguardian.com/environment/2020/jun/22/uk-arts-leading-figures-join-call-for-green-recovery-from-coronavirus-crisis
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/85272012-81320880-b473-11ea-9a80-98a0614446d1.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/85272126-aa529900-b473-11ea-887d-69baffeceb99.png" width="300px" /> |

use ellipsis for overflowing tags

---

src/capi.ts
src/components/advertisementFeature/article.tsx
src/components/advertisementFeature/logo.tsx
src/fixtures/item.ts
src/item.ts
src/server/csp.ts

- `<Logo />` component for AdvertisementFeatures
- Enable images from `https://*.guardian.com`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/85399935-86648580-b54f-11ea-96af-cb31447eca5d.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/85399956-8f555700-b54f-11ea-841d-92c2715df001.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/11618797/85399971-98debf00-b54f-11ea-9f95-182420a9989e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/85399990-a1cf9080-b54f-11ea-99c9-f323f06931c9.png" width="300" /> |

show paid content logo on advertisement features

---

api-models/thrift/src/main/thrift/appsRendering.thrift

This data is needed to render logos on articles such as this https://www.theguardian.com/cities/2020/jan/13/guardian-cities-farewell-from-the-editor.
We have an `alt` logo for dark backgrounds that we can make use of in dark mode.

add branding to apps rendering request

---

src/components/liveblog/article.tsx
src/components/liveblog/body.tsx
src/components/media/article.tsx
src/components/media/byline.tsx
src/components/standfirst.tsx
src/renderer.ts

- Full height on media pages
- Media page font
- Liveblog tags and load more padding
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/85432752-516e2800-b57b-11ea-98d4-df16a79565fb.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/85432789-60ed7100-b57b-11ea-9b33-dcdd03c0771a.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/85432827-719de700-b57b-11ea-94b9-8101cca52f04.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/85432874-7fec0300-b57b-11ea-9c7c-5408660cb30c.png" width="300px" /> |

style updates

---

src/atoms.ts
src/bodyElement.ts
src/client/liveblog.ts
src/client/parser.ts
src/components/byline.stories.tsx
src/components/standfirst.stories.tsx
src/item.test.ts
src/liveBlock.ts
src/server/server.ts
src/types/result.test.ts
src/types/result.ts

`Result` moves from an [ES6 class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) to a simpler [discriminated union](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions).
This PR is the companion to #404; the reasons for doing this are described in full there.
FYI @SiAdcock @gtrufitt @dskamiotis
- Removed the use of ES6 classes for `Result`; now simple objects
- Migrated `Result` methods to plain functions
- Refactored codebase to use new `Result`

Functional Result

---

src/server/page.tsx

Removes the white line seen at the bottom of articles in dark mode.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/86006513-fa020900-ba0d-11ea-820e-e729d9b70c64.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/86006539-05edcb00-ba0e-11ea-8d36-ebbce0597c70.PNG" width="300px" /> |

transparent body background in dark mode

---

src/atoms.ts

PRs #430 and #397 taken together have broken `master`. This fixes the problem by migrating uses of the `Err` and `Ok` classes to the `err` and `ok` functions.
- Migrated `Err` and `Ok` to `err` and `ok`

Fixed Deprecated Use Of Err and Ok

---

src/renderer.ts

Live blog in dark mode was not displaying listItem bullet points clearly, changed value to make lighter in colour and clearer to see.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/85757806-ad65b780-b707-11ea-8436-4888b9b19dd6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/85757904-c40c0e80-b707-11ea-8dc8-4a5558466869.png" width="300px" /> |

LiveBlog dark mode list items

---

src/client/metrics.test.ts
src/client/metrics.ts
src/client/setup.ts
src/native/nativeApi.ts

This uses Bridget to send performance metrics ("first paint", "first contentful paint", "fonts") to the native layers. Based on the work done in [this Bridget PR](https://github.com/guardian/bridget/pull/49).
- Refactored `metrics` module to use Bridget types
- Used metrics client in `setup`
- Created metrics client

Send Performance Metrics With Bridget

---

src/client/setup.ts
src/native/nativeApi.ts

Two separate issue with the metrics client introduced in #444... sadly the compile-time checks didn't pick up either of them 😔:
1. The default import of the metrics client isn't valid, we need to do `import * as...`
2. Using the `sendMetrics` method required binding it to `metricsClient` rather than `null` because it makes use of `this`. Rather than do this I've moved to the slightly less elegant option of just nesting function calls, as I think it's probably easier to follow at a glance.
- Use `import *` instead of default imports for `metricsClient`
- Stopped using unbound `sendMetrics` method

Fix Metrics Client

---

api-models/thrift/src/main/thrift/appsRendering.thrift

I've tried to map the campaign (callout) fields so we'll be able to render these forms inside articles.

add fields to rendering request for callout forms

---

src/server/page.tsx

We've got an open PR to change this for Android but it's causing a csp issue for beta users so maybe we remove it until it's needed?

remove unused font resize link

---

src/components/byline.tsx
src/renderer.ts

The first link in the standfirst on this article links to a tag page with `/latest` at the end of the path. The current behaviour in apps rendering is to open up theguardian.com as it's not recognised as a valid tag.
Removing the `/latest` part of the url will link to a valid tag page and keep the users in app.
https://www.gu.com/stage/2020/jul/08/77-per-cent-comedy-venues-in-uk-face-closure-survey-emergency-arts-funding-coronvirus

handle latest tags

---

src/renderer.ts

This ensures we stay inside the recursive `renderStandfirst`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/87141010-482ecc00-c29a-11ea-8f73-78a3fce7b899.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/87141045-57157e80-c29a-11ea-8fe7-db54e9ee4f12.png" width="300px" /> |

render strong tags in standfirsts

---

src/components/headline.tsx

The thinner underline is closer to the templates and dotcom.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/87413737-9c9bb980-c5c2-11ea-8a27-6065c98c07fe.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/87413780-aa513f00-c5c2-11ea-8a78-ddc578a5af2d.png" width="300px" /> |

thinner analysis underlines

---

src/image.ts

Previously we needed this parameter because we didn't have access to the `salt` for signing image URLs at the point when we set the `width` parameter. However, since #326 this is no longer the case.
**Note:** This will require a config change to use a different salt.
- Removed `sig-ignores-params` and started signing URLs with their query params

Remove sig-ignore-params For Images

---

src/client/nativeCommunication.ts

Beta feedback has flagged that lightbox images are no longer working. This is a short-term fix for that problem.
This was a side-effect of the changes in #506, in which we started signing the query params of images, rather than just the path. Because we were altering the `width` parameter of lightbox images on the fly, depending on the device size, the URL passed to the lightbox no longer matched its signature.
**Note:** This may result in slightly lower resolutions for images in the lightbox. I'm going to do some additional work to remedy that in a later PR.
- Stopped altering lightbox image sources

Fix Lightbox Images

---

src/components/commentCount.tsx

Comment count in dark mode was not the same colour scheme as keyline colour

Fixed comment count colour in dark mode

---

src/client/nativeCommunication.ts
src/components/advertisementFeature/article.tsx
src/components/headerVideo.tsx
src/components/img.ts
src/components/liveblog/article.tsx
src/components/media/article.tsx
src/components/media/articleBody.tsx
src/components/opinion/article.tsx
src/components/opinion/cutout.tsx
src/components/shared/articleBody.tsx
src/components/shared/shared.stories.tsx
src/components/shared/tags.test.tsx
src/components/shared/tags.tsx
src/components/standard/article.tsx
src/renderer.test.ts
src/renderer.ts
src/styles.ts

Some of the contrast of background elements were not clear enough on opinion/comment articles, this PR changes the background colour from `neutral.97` to `neutral.86`
This is for:
- header images
- header videos
- body images
- body videos
- adverts
- tags
- rich links
Paired with @dskamiotis 
Header
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19835654/87774029-e8956b00-c81b-11ea-85e4-007d5bb03339.png" width="500px" /> | <img src="https://user-images.githubusercontent.com/19835654/87774074-fb0fa480-c81b-11ea-837c-964933cc5a5a.png" width="500px" /> |
Body
| Before | After (with Advert too) |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19835654/87780751-424f6280-c827-11ea-8cf2-7c9d7f880aae.png" width="500px" /> | <img …

AR-84: Change background colour for elements on opinion/comment articles

---

src/server/csp.ts

CSP issue, atom relying on an s3 bucket was not whitelisted
Added s3 link to accepted URL in csp.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/87932675-cd2c9900-ca83-11ea-8fd9-ea0ec1920b05.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/87932598-af5f3400-ca83-11ea-83d3-268d84f601a4.png" width="300px" /> |

AR-97: Added s3 to csp

---

README.md
api-models/scala/version.sbt
api-models/thrift/src/main/thrift/appsRendering.thrift

When attempting to generate the Scala and TypeScript packages I get an error about using a reserved keyword "required".
It's a shame to lose the name "required" as it's commonly used to describe required fields in callouts throughout the targeting tool, dotcom and the callout React components that we hope to share with dotcom. For example: https://github.com/guardian/frontend/blob/master/common/app/model/dotcomrendering/pageElements/CalloutExtraction.scala
Would using French thrift allow this?

replace reserved keyword with mandatory

---

.github/workflows/chromatic.yml

We're currently running Chromatic on all branches, regardless of what has changed. This should filter out branches that do not directly impact components or version updates e.g. from Source.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
cc @gtrufitt @SiAdcock

Stop running Chromatic on unnecessary PRs

---

riff-raff.yaml

An ec2 instance's disk might contain private data e.g. application secrets or user data. Therefore it's preferable to use an encrypted AMI.
- Request an encrypted copy of our AMI, as per [the RiffRaff docs](https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation).

Use encrypted copy of xenial-mobile-node AMI

---

package-lock.json
package.json

Switching over to using [semver values](https://docs.npmjs.com/cli/install) for the `guardian/types` dependency.
This allows you to specify semver values for git repos, similar to how you can specify them for packages on the npm registry. The semver range is specified in `package.json`, and the exact commit that corresponds to the currently resolved version is recorded in `package-lock.json`. As far as I can tell, when looking up the target repository, the npm CLI uses a combination of the `version` specified in `package.json` and git tags to select a given commit. This mechanism also works with the [`npm update`](https://docs.npmjs.com/cli/update) command when it's time to bump your dependency.
FYI @guardian/client-side-infra 
- Used semver to specify `guardian/types` dependency
- …

guardian/types Semver

---

.github/workflows/nodejs.yml

This should speed up CI builds slightly; it seems to shave ~10 seconds off the `install` step (based on the limited testing I've done so far).
- Add dependency caching, as per [GitHub example](https://github.com/actions/cache/blob/main/examples.md#node---npm).

Cache dependencies for CI builds

---

src/components/bullet.stories.tsx
src/components/bullet.tsx
src/renderer.ts

To de-clutter the `renderer` module. Also, introducing more stories for our components make it easier to develop on them, and allows us to be more confident of catching UI bugs via Chromatic.
- Extracted `Bullet` into standalone component
- Added stories for `Bullet` component

Extract Bullet

---

package-lock.json
src/components/media/articleBody.tsx
src/components/shared/card.tsx

Gallery cards have no formatting to signify them as gallery cards. Formatting needed to _only_ be applied to gallery cards.
- Gallery cards formatted consistent with DC, added background colour to card.
- Inverted the background colour of the card.
- This is applied only when the type of card is Gallery
- Also included the camera svg within new tags (aligned with date/time) adding appropriate formatting as per DC.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/90160261-75830400-dd89-11ea-8c99-44fb5d12828a.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/90160514-c72b8e80-dd89-11ea-9418-f29e9bd0dc28.png" width="300px" /> |

LIVE-420: Added css styles to gallery cards with svg icon

---

.eslintignore
src/components/comment/article.tsx

`node_modules` are being linted unnecessarily when running `npm run lint`. This adds about a minute to the running time.

stop linting node_modules

---

src/components/shared/card.tsx
src/components/shared/relatedContent.tsx
src/date.ts
src/item.ts
src/styles.ts

Appropriate formatting needed for audio and video cards need in related content, as well as svg and duration of audio/video for cards not displaying.
- Added audio, video cards, the duration and also fixed the appearance on media pages (gallery, video, audio)

Live-418: audio and video cards

---

src/editorialPalette.ts
src/editorialStyles.ts

Based on @SiAdcock's description [here](https://github.com/guardian/apps-rendering/pull/313#discussion_r423839454), the dark mode version of a "primary" colour should be `primaryInverse` rather than just `inverse`.
- Updated the palette API to use the correct inverse name
- Updated `editorialStyles` to reflect name changes

Correct Naming Convention For Inverse Colours

---

src/components/shared/card.tsx
src/components/starRating.tsx
src/pillarStyles.ts
src/styles.test.ts

- Live cards in related content
- Review cards in related content
- Added new field to pillarStyles for dark mode pillar colour

review and live cards

---

src/capi.test.ts
src/capi.ts
src/components/shared/card.tsx

Styling needed for comment related cards to be consistent with headline and svgquote.
Date added is not rendering within the card also. 
- Added background colour, font headline small, added co;our and size for quotation svg.
- Adde pillar styles for border-top to be active
- Rendered a new component tag `quotationComment` to be generated only when its a comment card
- Added specific styling for commentIconStyle to make quotation inline with headline text
- added endpoint for lastModified date in capi.ts to get date from capi (lastModified)
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/91160831-d1228b00-e6c1-11ea-8f5f-c87b5c2413e9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/91191762-15775080-e6ed-11e …

Live:416 - added styling for comment cards and added capiendpoint for date

---

src/components/dateline.stories.tsx
src/components/dateline.tsx
src/components/liveblog/metadata.tsx
src/components/media/byline.tsx
src/components/metadata.tsx
src/components/shared/card.tsx

Contrast of dateline colour needs to be clearer upon rendering to stand out on background.
- Changed dateline colour to neutral.20
- Omitted text from import - deprecated 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/91309283-4e283000-e7a8-11ea-9036-0fffd18403cc.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/91309353-65ffb400-e7a8-11ea-8cab-6b8ffcd0c29c.png" width="300px" /> |

Live-125: Changed dateline colour neutral.20

---

src/components/shared/logo.tsx

Currently when offline the alt text defaults to the HTML blue.
We would like the alt text to be consistent with the Pillar colour, as well as inverted when in dark mode.
- Added kicker colour from Pillar, for text to render when offline/missing logo
- Included inverted colour for dark mode
- Included format prop in Logo component to read Pillar type
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/91844845-127de200-ec50-11ea-88e7-8c8ced166e15.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/91844891-26c1df00-ec50-11ea-8bc3-2b716992306b.png" width="300px" /> |

Live:353- Sponsor offline links colour as kicker

---

src/components/advertisementFeature/article.tsx
src/components/comment/article.tsx
src/components/comment/cutout.tsx
src/components/follow.tsx
src/components/headerVideo.tsx
src/components/interactive/article.tsx
src/components/liveblog/article.tsx
src/components/liveblog/avatar.tsx
src/components/liveblog/block.tsx
src/components/liveblog/body.tsx
src/components/liveblog/commentCount.tsx
src/components/liveblog/headline.tsx
src/components/liveblog/keyEvents.tsx
src/components/liveblog/loadMore.tsx
src/components/liveblog/metadata.tsx
src/components/liveblog/series.tsx
src/components/liveblog/standfirst.tsx
src/components/media/article.tsx
src/components/media/articleBody.tsx
src/components/media/articleSeries.tsx
src/components/media/byline.tsx
src/components/media/tags.tsx
src/components/shared/articleBody.tsx
src/components/shared/card.tsx
src/components/shared/keyline.tsx
src/components/shared/leftColumn.tsx
src/components/shared/relatedContent.tsx
src/components/shared/tags.tsx
src/components/standard/article.tsx
src/headerMedia.tsx

Currently many react components are constructed using JSX.Element with the type definition in the parameter. There is inconsistency across the code base in the way components are constructed.
- Used FC<Props> to replace JSX.Elements
- imported FC within React in imports

Live -454: refactored components from JSX to FC

---

package-lock.json

Keeping dependencies up-to-date.
- Bumped lodash (transitive dep) to 4.17.20

Lodash 4.17.20

---

package-lock.json
package.json
src/client/article.ts
src/components/shared/card.tsx

Matches feature in template articles where cards are faded if a user has already read them.
- Uses `filterSeenArticles` api
- Updates min-height style to ensure cards are same height
The last two cards here have been viewed previously, the current opacity of .7 can be tweaked.
| Light | Dark |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/92386461-bf060b00-f10b-11ea-9e44-b297164215e0.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/92386536-df35ca00-f10b-11ea-8215-4139a042c9c5.png" width="300px" /> |

Seen article styles

---

package.json
src/components/pullquote.tsx
src/renderer.test.ts
src/renderer.ts

Currently pullquotes are using icons which cause issues when rendering in certain browser and ios/android versions, with strange fallback icons when not loading (square box).
Issues regarding Icons and how SVg are more desirable:
- Icon _Accessibility_: do not support screen readers,  SVG's, however are accessible to a screen reader (they are treated as images)
- Font icons are not as _scalable_ as they are font sized as opposed to vector based.
- In terms of _performance_ icons can increase HTTP server requests.for caching
- Icons are vulnerable to _anti-aliasing_ techniques causing blurring
In addition svg's allow for a  high degree of modifications without triggering additional server requests so can have a performance advantage
We could provide PNG icons as fallback, but since we have …

created pullquote component in new file updating icon with svg

---

package-lock.json
package.json
src/atoms.ts
src/bodyElement.ts
src/pillarStyles.ts
src/renderer.test.ts
src/renderer.ts

Implement guide atoms using component from atoms-rendering.
The like/dislike event handlers rely of client side rehydration and also the Ophan tracking work so that hasn't been implemented so far.
Users can still open and close the expandable box. 
Guide atoms: http://theguardian.com/sport/blog/2020/sep/08/talking-horses-racing-with-pride-launched-as-racings-lgbt-network
QA atoms: http://theguardian.com/environment/2020/aug/25/the-aliens-to-watch-how-the-humble-earthworm-is-altering-the-arctic-aoe
I've made a PR to atoms-rendering to avoid a style issue currently seen in dark mode https://github.com/guardian/atoms-rendering/pull/62.
- Bump atoms-rendering to 1.9.0 - Had some issues with 1.10.0 which are being looked into
- Render guide atoms
- Render qa atoms

Guide and QandA atoms

---

src/components/headerImageCaption.tsx
src/renderer.test.ts

Currently Header Image Caption renders an icon of a camera using icons which cause issues when rendering in certain browser and ios/android versions, with strange fallback icons when not loading (square box).
Issues regarding Icons and how SVG are more desirable:
Icon Accessibility: do not support screen readers, SVG's, however are accessible to a screen reader (they are treated as images)
Font icons are not as scalable as they are font sized as opposed to vector based.
In terms of performance icons can increase HTTP server requests.for caching
Icons are vulnerable to anti-aliasing techniques causing blurring
In addition svg's allow for a high degree of modifications without triggering additional server requests so can have a performance advantage
We could provide PNG icons as fallback, …

Live 603 icon svg headerimagecaption

---

src/server/csp.ts
src/server/page.tsx

So that the Android native layer can intercept this request for `fontSize.css` and provide the correct "base" font size for the page.
@JamieB-gu I think putting `/fontSize.css` should cause the request to go to the MAPI domain as we discussed?
- Add a stylesheet link to the head of all pages.
This PR is a replacement for #346

Add link to fontSize.css

---

src/server/server.ts

In local development we were requesting `/fontSize.css` from CAPI. This is only a relevant resource when running in the Android client (see #703). We should serve a `404` for this from our dev server, as we do for the favicon.
- Serve 404 for Android `fontSize.css` stylesheet

Don't Ask CAPI For 'fontSize.css`

---

src/components/starRating.tsx

Currently Star Rating is using icons which cause issues when rendering in certain browser and ios/android versions, with strange fallback icons when not loading (square box).
Issues regarding Icons and how SVg are more desirable:
Icon Accessibility: do not support screen readers, SVG's, however are accessible to a screen reader (they are treated as images)
Font icons are not as scalable as they are font sized as opposed to vector based.
In terms of performance icons can increase HTTP server requests.for caching
Icons are vulnerable to anti-aliasing techniques causing blurring
In addition svg's allow for a high degree of modifications without triggering additional server requests so can have a performance advantage
We could provide PNG icons as fallback, but since we have SVG's as part of …

Live:104 - converted star rating icon to svg

---

src/components/follow.test.tsx
src/components/headerImageCaption.test.tsx
src/components/liveblog/avatar.test.tsx

- Continuation of PR:  https://github.com/guardian/apps-rendering/pull/731 to upgrade more unit tests within the AR code base
- Currently testing with Enzyme adds a layer of complexity to testing in terms of its API
- Particularly when testing components for CSS with CSS Emotion
- Integrates well with Jest
- Jest configured incorrectly and not working with CSS Emotion
- Upgraded tests for `Follow` and `HeaderImageCaption` components
- used `import { render, unmountComponentAtNode } from 'react-dom';` to implement tests to easily check for text content within `Follow` component
Paired with @JamieB-gu

Live: Continued upgrade from Enzyme testing to avatar, follow and headerimgcap

---

api-models/scala/version.sbt
api-models/thrift/src/main/thrift/appsRendering.thrift
package-lock.json
package.json
src/components/shared/bylineCard.tsx
src/components/shared/card.tsx
src/components/shared/relatedContent.tsx

- Creates a new `BylineCard` component as `Card` was getting a bit large and confusing
- Shows byline on comment cards
- Shows byline image on comment cards
- bumps `apps-rendering-api-models` up to `0.11.0` to receive byline and bylineImageUrl
Icon misalignment seen when running apps-rendering and mapi locally.
| Light | Dark |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/93459735-15c4cf00-f8da-11ea-98ef-87e2b89b8a64.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/93459754-1f4e3700-f8da-11ea-89c9-0df0f2bdd702.png" width="300" /> |

Byline card

---

src/native/thrift/nativeConnection.ts

This check is needed to render the Epic component server side in node.js where the `window` object isn't available.
This should stop a number of errors seen in the server console.

check for window type rather than catching exception

---

.github/workflows/screenshots.yml

This PR adds functionality for automatically capturing screenshots from a running version of each pull-request branch and comparing them with screenshots captured from the main branch. It builds upon the work started in https://github.com/guardian/apps-rendering/pull/684, which allows us to run the application within the GitHub Actions infrastructure.
During my [original experiment](https://github.com/guardian/apps-rendering/pull/754) I was planning to replace the PR deployment workflow with this new one, but I noticed that a few people are [already using PR deployments](https://github.com/guardian/apps-rendering/pulls?q=is%3Apr+label%3A%22PR+Deployment%22+) in their current form (🎉). Perhaps it is useful to keep both as they have slightly different use-cases. …

Add screenshots workflow

---

config/.eslintrc.js

Applied `typescript-eslint` naming conventions. Not too strict as yet, so shouldn't cause any problems for our existing codebase. Docs [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md).
- Functions are `camelCase` or `PascalCase`
- Variables are `camelCase`, `UPPER_CASE` or `PascalCase`
- Types, including enum members, are `PascalCase`

Enforce Naming Conventions

---

src/ads.tsx
src/client/nativeCommunication.ts
src/components/standard/article.tsx

Adverts can overflow the main article body and cover the related content section. This PR adds client side JavaScript to detect when ads are overflowing and removes them from the DOM before the Bridget request is made to populate them. This should only be required on iPad articles when the adverts are absolutely positioned.
TODO:
- add `js-article` to all article types with adverts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/95746768-43115c80-0c8f-11eb-90cc-46df71b77cf6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/95746786-4b699780-0c8f-11eb-9eb8-9238fdd666a1.png" width="300px" /> |

remove adverts overflowing article body

---

src/components/shared/epic.tsx

- Match the designs by using a brighter font colour in dark mode
- Align SVG icons in epic buttons. A newer src-icons version has fixed the alignment
Design:
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/95857773-022f4b80-0d54-11eb-88f0-f8db1c1e5b57.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/95857797-0f4c3a80-0d54-11eb-9c2d-106034618eee.png" width="300px" /> |

align epic button

---

src/server/server.ts

Our current `serveArticle` and `serveArticlePost` functions do similar things. However I noticed a discrepancy in #821, where one of them wasn't setting a `charset`.
This change pulls the common code into a shared `serveArticle` function, so that DEV and PROD use the same code wherever they're doing the same thing. This should make DEV and PROD as similar as possible.
- Renamed previous `serveArticle` function to `serveArticleGet`
- Created new `serveArticle` function to share common DEV and PROD code

Refactor serveArticle

---

src/ads.test.ts

Readability: typo in ad test for articles with 15 paragraphs

Correct the typo in 15 paragraphs test

---

package-lock.json
src/client/article.ts

At the moment two footers are being rendered on the Android platform, the SS as well as the native.
Max has asked to disable the footer component for Android
So we need the footer to still render for iOS by default
- created a function to read whether the platform is Android and as a result run the isCcpa function which renders the ccpa link 
| --- | --- |

added function for android presence check

---

config/jest.config.js

Suggestion from @mxdvl, as described [here](https://github.com/guardian/apps-rendering/pull/844#discussion_r510870646).
FYI @gtrufitt @SiAdcock @sndrs 
- Simplify Jest ignore pattern for `guardian` modules

Simplify Jest Ignore Pattern For Guardian Modules

---

src/components/horizontalRule.stories.tsx
src/components/horizontalRule.tsx
src/renderer.ts

Migrated `HorizontalRule` to standalone component. I'm trying to narrow the focus of the `renderer` file, and also introduce stories for components that don't have them.
- Moved `HorizontalRule` to standalone file
- Added stories

HorizontalRule Component

---

package-lock.json
package.json

The apps-rendering team city job is failing frequently due to a preinstall script in the image-rendering project.
This should hopefully enable successful builds in team city, which is required for riff-raff and deploying apps-rendering to production.
image-rendering fix: https://github.com/guardian/image-rendering/pull/107

update to image rendering 3.0.2

---

src/item.test.ts
src/item.ts

Match reports should look like standard articles, render them in the same way as other articles.
Article: `football/2020/nov/03/atalanta-liverpool-champions-league-group-d-match-report`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/98258544-e5fc8400-1f78-11eb-8fb7-64ed7531eeab.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/98258568-ed239200-1f78-11eb-9938-a51d38a2c9ca.png" width="300px" /> |

render match reports as standard articles

---

src/components/shared/footer.tsx

The footer is not supported in dark mode. also the width of the text is not contained within the border of the article.
Additional Privacy settings link not needed
- Removed the privacy settings link
- Included Border `width: ${breakpoints.wide}px;` to container css
- Added dark mode to css for container css as well as anchor css
| Dark Default | Dark with Ccpa |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/98833004-6cabd800-2435-11eb-8eab-9482502620cd.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/49187886/98832791-2787a600-2435-11eb-8e7b-85ec83928563.png" width="300px" /> |

updated footer for dark mode and privacy links

---

src/server/editionsPage.tsx

Added a Content Security Policy for the Editions page. This will restrict the resources, such as styles, images and scripts, that we allow on pages used by the Editions project. For more information on CSPs see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). Go [here](https://emotion.sh/docs/ssr#advanced-approach) for more information about the Emotion APIs.
- Used Emotion critical to extract styles into single tag
- Hashed style tags in CSP
- Allowed some image domains

Editions CSP

---

.github/workflows/screenshots.yml

All the open pull requests are failing builds because of the screenshot action.
I saw a warning message on Friday saying `set-env` would be removed and actions wouldn't run if they used it after the 16th November.
Luckily it appears the action we're using to take screenshots has been updated to use the suggested environment files.
https://github.com/lannonbr/puppeteer-screenshot-action/commit/ecc08ce649f3aa4ff689388f903d38d83eccfc22

update screenshot action to avoid using set env

---

src/components/img.ts
src/contributor.ts
src/image.test.ts
src/image.ts
src/renderer.test.ts
src/renderer.ts

Image-rendering has provided nicer exports via an `index.ts` file for [a while](https://github.com/guardian/image-rendering/pull/74). This PR stops reaching into the `src` directory and switches to using these exports directly.
- Used top-level exports from image-rendering index file

Image-Rendering Top-Level Exports

---

src/components/meta.tsx

To ask Twitter widgets not to track users, as documented by Twitter [here](https://developer.twitter.com/en/docs/twitter-for-websites/privacy).
- Add DNT `<meta>` tag for Twitter

Twitter DNT

---

src/components/headerImage.tsx

All images should use Image-Rendering if possible.
- Stopped using AR's internal `Img` component in favour of the Image-Rendering version

Migrated HeaderImage To Image-Rendering

---

src/bodyElement.ts
src/components/editions/article.tsx
src/renderer.test.ts
src/renderer.ts

We use a `render` function to render blocks, now that some designs will diverge for ER (pullquote for example). We need two separate renderers, however a lot of the element renderers have been refactored out so we don't have to duplicate their code if the element is the same.
- Refactor out element renderers that are > 1 line
- Created `renderEditions` and `renderEditionsAll`
- typed three elements: `Text`, `Embed` and `Instagram`

LIVE-1250: Split out AR and ER renderers

---

src/capi.ts

We would like to avoid `unsafe-inline`, it [sidesteps most of](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#Unsafe_inline_styles) the security benefits provided by the CSP.
- Disable `unsafe-inline` by hardcoding `requiresInlineStyles` to `false`

Disable "unsafe-inline"

---

src/server/csp.ts
src/server/editionsPage.tsx

The CSP is somewhat broken on editions-rendering. The inline styles weren't working and embeds (like YouTube for example) were also broken. I have decided to get inspired by the way it works on AR and use a similar but custom function to render ER's head. 
- Change CSP generation
- upgraded `renderHead`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/12860328/102203022-f715aa80-3ebf-11eb-9fd9-b4f77dbc8af9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/12860328/102203056-03016c80-3ec0-11eb-8873-d658290ddadf.png" width="300px" /> |

LIVE-1282: Editions-Rendering CSP

---

package-lock.json
package.json
src/contributor.ts
src/image.test.ts
src/image.ts

We've moved the code to generate image sources upstream to Image-Rendering. See https://github.com/guardian/image-rendering/pull/152 for more details.
FYI @paperboyo
- Updated image-rendering to `v4.1.0`
- Removed code to generate image sources from `image.ts`
- Updated imports to use new types and functions for image sources

Migrated To Image-Rendering For Image Sources

---

.github/workflows/screenshots.yml

Labs pieces get taken down over time, which breaks our screenshots. In the PR comment for screenshots labs rows end up blank with an error message - this generates noise so I think it's easier just to turn the screenshots off for labs articles. To see the problem look at any PR opened within the last couple of weeks (from the time of opening of this PR).
- Remove labs article screenshots

Remove Labs Article Screenshots

---

.github/workflows/chromatic.yml

Our other workflows (e.g. [nodejs](https://github.com/guardian/apps-rendering/blob/3ee405708fedbed4ce8bc799d86e6b419edc701c/.github/workflows/nodejs.yml) and [screenshots](https://github.com/guardian/apps-rendering/blob/3ee405708fedbed4ce8bc799d86e6b419edc701c/.github/workflows/screenshots.yml)) are using the [cache action](https://github.com/actions/cache) to cache npm dependencies.
**Note:** The chromatic workflow is currently failing on other PRs on the `npm ci` step. This is the only difference I can see between them so I thought I'd add it (because it's useful in general), but I don't see why it would fix the problem 🤔.
- Add cache action to chromatic CI

Add Cache Action To Chromatic CI

---

config/jest.config.js

The `tsConfig` field has been renamed to `tsconfig`.
- Renamed deprecated `ts-jest` field

Renamed Deprecated ts-jest Field

---

src/components/meta.tsx

Duplicate PR of [this PR](https://github.com/guardian/apps-rendering/pull/1066) because CI was unreasonable failing.
There is bug in iOS with swiping the articles. It is not yet fully known if the behaviour is caused by the iOS app, apps-rendering or both. This change doesn't hurt our UX however as our apps default behaviour is not to allow users to zoom/pinch. As far as I understand, iOS doesn't allow this on iOS safari however it does allow it on WKWebView.
@JamieB-gu : Are there any a11y concerns with preventing users zooming in? Or are we already preventing zooming in by setting maximum-scale=1?
@faresite : The reason user-scalable=no causes accessibility issues is because the user can no longer help themselves to zoom and read for example, our app has its own mechanism to do this …

Disable user-scalable

---

package-lock.json
package.json

Keeps the dependency up-to-date and prevents compiler errors now that image-rendering is `v1.1.0`.
- Bumped `@guardian/types` to `v1.1.0`

Bump guardian/types To v1.1.0

---

src/components/headerImageCaption.tsx

there's currently a bug on prod where the styles of the icon container scale up with rem. The icon should stay the same.
@aoifemcl15 and I believe there's a good chance the icon is the culprit with the iOS swipe bug. Hoping this might shed some light on this too.
| before | after |
| ------ | ----- |
| <img src="https://user-images.githubusercontent.com/12860328/104446065-d2c9ee00-5591-11eb-982b-358473ece4c5.png" width="300" /> | <img src="https://user-images.githubusercontent.com/12860328/104446111-df4e4680-5591-11eb-935a-5f384f799a6a.png" width="300" /> |

LIVE-1370: camera caption icon fix

---

src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/header.tsx
src/components/editions/lines.tsx
src/components/editions/standfirst.tsx

Creates new `Header` component to contain switch for different article template options in `Editions/Article` component. 
- adds `Header` component
- adds switch and subcomponents for individual layouts
- updates margins and widths to roughly match existing figma designs (aware these may well change after Ben's audit)
- creates editions specific `lines` component to control width
We still need to incorporate Fares` byline` updates and include line / outlines as in Figma.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/104594241-c82e5800-5668-11eb-8ebe-34acc1e2f54d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/104594333-eac07100-5668-11eb-89a4-c8ff65139741.png" width="300px" /> |

feat(editions-article): add article showcase header component

---

package-lock.json
package.json

NPM is ignoring semver ^ and pulling version 1.2.0 which currently has breaking changes for AR, and the version lock in  package-lock is also being ignored. To temporarily sidestep this, we are locking @guardian/types to 1.1.0 in the package.json

Lock @guardian/types to 1.1.0

---

src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/headline.tsx
src/components/editions/lines.tsx
src/components/editions/series.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts

Adds borders to Editions Article template headers.
- Creates new width variable and applies to all required header components
- Adds borders where needed according to figma designs: https://www.figma.com/file/AgfOrrLI78asahmA3Z9Env/AUS%2FUS-xtra-designs?node-id=1713%3A0
A separate ticket add borders to the Editions Article body components is here:
https://theguardian.atlassian.net/browse/LIVE-1388
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/104727735-c11d4d80-572d-11eb-96a9-6713b7e8ccc1.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/104727797-dd20ef00-572d-11eb-9c68-de82244dc64f.png" width="300px" /> |

feat(editions-article): add border to header components

---

src/components/editions/byline.tsx
src/components/editions/headline.tsx
src/components/editions/lines.tsx
src/components/editions/series.tsx
src/components/editions/standfirst.tsx
src/renderer.ts

Removes links from Standfirst in Editions
- create new render function without links
- replace vertical margins with padding so borders are continuous
- add padding-right so text is padded from borders
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/104936208-1a8eb200-59a4-11eb-8123-c839bbd02d2c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/104936242-28dcce00-59a4-11eb-8935-13b95e812065.png" width="300px" /> |

feat(editions-standfirst): render standfirst without links

---

src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/header.tsx
src/components/editions/headline.tsx
src/components/editions/lines.tsx
src/components/editions/series.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts
src/editorialPalette.ts

Adds border to article body, fixes existing borders on header and fixes margins to match new designs.
Updates title colours styles.
@abeddow91 I ended up moving the Review background colour up a level and getting the headline colour from the palette as I couldn't make it work as it was with the margins, open to suggestions though if I've missed something there :)  Think it makes sense to get the headline colour from the pillar styles for all articles if possible.
Also aware we need to fix the header image size, have created a new ticket for that here:
https://theguardian.atlassian.net/browse/LIVE-1426
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105161454-4c6d5900-5b09-11eb-89cc-93ed48147966.png" width="300px" /> | <img …

feat(editions-article): fix borders and template layout

---

src/bodyElement.ts
src/components/interactive.tsx
src/item.test.ts
src/renderer.test.ts
src/renderer.ts

The `renderer.ts` file is dealing with multiple concerns, which makes it hard to understand. I plan to start breaking it up into more focused modules. This should allow us to reason more clearly about the structure of our code, which will in turn help us with the embeds and Editions work (I hope).
- Moved `Interactive` component out of renderer
- Changed an optional field to an `Option` (preferable type in this codebase)

Migrate Interactive Component To Own File

---

src/components/editions/headline.tsx
src/editorialPalette.ts

As Editions has specific styling, there shouldn't be Editions styles in the Editorial Palette as it may affect AR articles. 
- Moves Editions Review style back into Headline component
- Refactor headline styles

Live 986 headline styles

---

src/components/editions/standfirst.tsx

The editions standfirst has default font styling at mobile and mobile-medium. The font weights are not included in the source standard sizes
- add default font styling at mobile and mobile-medium breakpoints 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/105198495-9f5d0580-5b35-11eb-984c-a666507cc359.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105198298-6f156700-5b35-11eb-90a4-331509d1bf0c.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/105198505-a126c900-5b35-11eb-8922-64dd6fc3ac1c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105198323-763c7500-5b35-11eb-93d0-a63a0c8a90a9.png" width="300px" /> |

Add default font styles to standfirst

---

src/components/editions/headerImage.tsx
src/components/editions/styles.ts

Updates Image widths to reflect designs.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105207608-9ec96c80-5b3f-11eb-851c-edeab3b46bd9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/105207655-ac7ef200-5b3f-11eb-8c12-ee93fdeaa038.png" width="300px" /> |

feat(editions-header-image): update widths to match designs

---

src/components/editions/headline.tsx

Quick-fix to add responsive styles for standard article headline fonts.

feat(editions-headline): add generic font styling

---

src/item.ts

Sometimes content has multiple tone tags and this happens frequently with interview and feature. In this circumstance, AR should follow CAPIs lead and prioritise Interview over Feature.
- Move Interview above Feature when deriving the Format type.
NB - Most interviews used to fall under the Feature format type. As this is now not the case, interviews will not render on AR as this content format is not built at present.

FIX: Prioritise Interview tag over Feature

---

src/components/editions/byline.tsx
src/components/editions/header.tsx
src/components/editions/headline.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts

Adds Analytics template specific styles to existing Editions article subcomponents.
- Add `large` prop to `Byline` component to allow for Analytics font size.
- Add `AnalysisHeader` to `Header` component to change subcomponent ordering
- Add `ShareIcon` to `Standfirst` with optional prop
- Add optional `shareIcon` prop to `Byline` component
- Add `Analysis` to background-colour picker.
Apologies this is a more bloated PR than I'd intended 😞  Still needs the Standfirst text styles but I'll save that rather than adding more noise here.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105390331-d2c09280-5c10-11eb-9554-f18a6def1842.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/105390374-df44eb00-5c10-11eb-96f …

feat(editions-analysis): add template specific styles

---

src/components/editions/header.tsx
src/components/editions/standfirst.tsx

The Interview template has full width Header Image and Headline on mobile. This PR removes the padding from the header and adds it into Standfirst
- Remove padding from header
- Add padding to standfirst
- Add style switch for template type
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/105505217-964c6f80-5cc0-11eb-9f1d-5741a7021da7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105504766-12928300-5cc0-11eb-978a-c498889292e0.png" width="300px" /> |

Live 1407: Interview Standfirst Padding

---

src/components/editions/headerImage.tsx
src/components/editions/headline.tsx
src/components/editions/series.tsx

The Editions Interview template has the Series component on the Header Image. This PR makes that change
- Add Series/Kicker to header image if it's type Interview
- Add interview specific styling to series
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/105704868-54f9d100-5f07-11eb-8e62-476352255b3d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105704875-56c39480-5f07-11eb-8765-1c671794dde6.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/105704871-55926780-5f07-11eb-9aee-2d9d631830d4.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105704872-562afe00-5f07-11eb-9129-7b6543f799cb.png" width="300px" /> |

Live 1406: interview series

---

src/components/editions/article.tsx
src/components/editions/header.tsx
src/components/editions/styles.ts

Adds coloured background for Interview template to headline and standfirst only as per designs. 
NB To reduce the PR size, this PR breaks styling on the image, byline and lines component. These will be resolved in separate pulls.
| --- | --- |
| <img src="" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106125148-b3b38a80-6153-11eb-843a-2023954f5992.png" width="300px" /> |
| <img src="" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106124840-70591c00-6153-11eb-977a-1c74c358541d.png" width="300px" /> |

Live 1408: Interview Header Background Colour

---

src/components/editions/headerImage.tsx

Some templates require a full width image in the header. This PR add styles to the image, container, and caption for rendering a full width image.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/106135014-3f7ee400-615f-11eb-857d-8868295e30fb.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106133968-d8146480-615d-11eb-8381-21dd26646d8b.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/106135002-3beb5d00-615f-11eb-939a-7f9aeb05e4cd.png" width="300px" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106133954-d480dd80-615d-11eb-95e2-686f35630cfa.png" width="300px" /> |

LIVE 1408: Interview Image

---

src/components/editions/series.tsx

Add left space to the series on tablet and wide devices as per interview designs.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/106149510-42cf9b00-6172-11eb-94f6-8cacc6a7cded.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106149263-f97f4b80-6171-11eb-9ce7-07c7f55fa74a.png" width="300px" /> |

LIVE 1408:  Interview Series

---

config/cloudformation.yaml

Change the InstanceType from being a parameter to a mapping so we can make sure version control is in place, this is because we want to update apps-rendering to use the new ARM instance type so this first step will make sure we are changing everything in the right place.
This has been tested on CODE

Add Instance Type to the cloudformation mappings

---

src/client/editions.ts
src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/galleryImage.tsx
src/components/editions/header.tsx
src/components/editions/headerImage.tsx
src/components/editions/headline.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts
src/renderer.ts
src/server/editionsPage.tsx

This PR implements the Editions gallery template ([Figma file](https://www.figma.com/file/7BWzTDoChAGQKCM4iC27aC/Article-Type-Picker?node-id=1%3A9)) and includes a few extras:
- header caption fixes for full width header images
- fix styled jsx in renderer
- full height article body
- When the caption description gets very long on tablet/wide, I've implemented the first figma design where the caption pushes the next image down. Until design can decide how exactly it needs to be implemented.
- The designs don't include credit, will follow up with design about those but shouldn't be a blocker for this PR.
| Mobile |
| --- |
| <img src="https://user-images.githubusercontent.com/12860328/106439340-7d398080-646f-11eb-9f51-8c0a716c63f5.png" width="500px" /> |
| Tablet | Wide |
| --- | --- |
| …

LIVE-1473: Editions Gallery

---

src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/header.tsx
src/components/editions/headerImage.tsx
src/components/editions/headline.tsx
src/components/editions/lines.tsx
src/components/editions/series.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts

Updates the majority of styles for the immersive template. Have added a list of outstanding tasks below screenshots.
- Add `Immersive` to to list of templates with no wrapper styles
- Add white text option to Byline Italics
- Add `Immersive` to list of fullwidth image templates
- Add  standfirst styling
- Add  headline styling
- Add series styling
- Add background colour
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/106485493-8f83e080-64a8-11eb-8687-dbfee23483ad.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/106485525-9874b200-64a8-11eb-9738-461e2e5b78c0.png" width="300px" /> |
- Lines (triple-line) component needs padding
- Headline needs pillar colours for white bg variant
- Standfirst needs pillar …

LIVE-997: immersive basic styles

---

.github/workflows/chromatic.yml

Chromatic is currently running on every branch that's pushed. We probably only want to run it in one of two cases:
1. A PR is opened against `main`
2. A PR is merged to `main` (we want to run against `main` once the PR is merged)
This should limit our usage of the Chromatic API.
- Only run chromatic on merges to `main` or PRs to `main`

Limit Chromatic Runs To main And PRs

---

src/components/editions/article.tsx
src/components/editions/byline.tsx
src/components/editions/header.tsx
src/components/editions/headline.tsx
src/components/editions/standfirst.tsx
src/components/editions/styles.ts

Fixes Immersive layout and moves Immersive above Interview type in pecking order.
- Make all background-colour blacks `neutral[7]`
- Move `Immersive` about `Interview` in terms of priority
- Update margins, widths etc to fit layout.
- Remove all `Immersive` white backgrounds until we receive clarity from design
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/106749119-07274c00-661e-11eb-9175-0953fe286142.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/106749158-14443b00-661e-11eb-900f-6bec1ee9ca84.png" width="300px" /> |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/106749187-1e663980-661e-11eb-8972-14bb28ed7ac7.png" width="300px" /> | <img …

LIVE-997: update widths

---

src/components/editions/headerImageCaption.tsx
src/components/editions/headerMedia.tsx

Creates an Editions specific HeaderImageCaption component with editions styling.
- fix svg positioning
- fix caption height
- fix caption text layout
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/106887896-b9721880-66dd-11eb-8f01-c1d6aeadcec8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/106887937-c858cb00-66dd-11eb-97ed-f1a137c179cb.png" width="300px" /> |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/106888000-db6b9b00-66dd-11eb-97b8-cc28653e111a.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/106888044-e58d9980-66dd-11eb-9446-7f05498686ac.png" width="300px" /> |

LIVE-1547: add editions specific caption component

---

src/image.ts

Images should be parsed ideally using `secureFile` from assets, upon call to CAPI.
Currently image parsing only constructs the image URL using the `file` property.
- Prioritised the parsing to be based on `secureFile`
- Included `file` url as a back up in case https for secureFile is unavailable (null/undefined) using Nullish coalescing
NOTE: in checking on local host articles return `undefined` for secureFile

parse image with secureFile as priority

---

src/components/editions/article/article.stories.tsx
src/components/editions/article/index.tsx
src/components/editions/header/index.tsx
src/components/editions/headerMedia/headerMedia.stories.tsx
src/components/standfirst.stories.tsx
src/fixtures/item.ts

Adds Editions article templates to Storybook. 
Note: does not include article bodies at this stage.
- Add mock data for stories to `item.tsx`
- Remove duplication of mock data elsewhere
- Move files to folders within Editions folder.
Run storybook and look under Editions tabs.

LIVE-1573: create article header stories

---

src/server/csp.ts
src/server/editionsPage.tsx

I've committed an unnecessary unsafe CSP change. While at it, I noticed that twitter embeds weren't fully working so fixed that one up too.

No unsafe-inline (and editions twitter bug fix)

---

src/client/editions.ts
src/components/editions/byline/index.tsx
src/components/editions/shareIcon/index.tsx
src/components/editions/shareIcon/shareIcon.stories.tsx
src/components/editions/standfirst/index.tsx

Adds ShareIcon story for Editions.
- Make ShareIcon a default export inline with other components
- Add story and implement pillar colour selector in wrapper

LIVE-1578: add shareIcon stories and make default export

---

config/jest.config.js
package-lock.json
package.json
src/__snapshots__/storyshots.test.ts.snap
src/storyshots.test.ts

Investigating the addition of snapshot testing using the Storybook addon "Storyshots" and Jest.
For anyone who hasn't come across this before there's more info here:
https://www.npmjs.com/package/@storybook/addon-storyshots
The setup is very simple, we've had to update the Storybook config files to use their new conventions but otherwise all this requires is a `storyshots.test.ts` file that initialises the tests .
Each time we run the test script now Jest will create a snapshot for every file that has a `*.stories.tsx` file - giving us a way to monitor for changes in the UI.
Creating the snapshots adds around 2.5 seconds to the time the test script takes to run and currently generates 65 snapshots, all contained within one file.
If a snapshot has been changed Jest will flag it as below: …

LIVE-1662: investigate adding Storyshots snapshot testing

---

config/jest.config.js

In [this PR](https://github.com/guardian/apps-rendering/pull/1172) the new threshold for the coverage seems to be just on the edge and it's failing on .5% now. Lowering it as a more reasonable initial option.

Reasonable initial coverage threshold

---

package-lock.json
package.json
src/lib.test.ts
src/lib.test.tsx
src/lib.ts

This is a subtask of our [Increase test coverage](https://theguardian.atlassian.net/browse/LIVE-1684?atlOrigin=eyJpIjoiOThiNWJlMmI2NDJhNGQ0OGEzZDBkOGNhYzY3NjEyNjUiLCJwIjoiaiJ9) health ticket.
NB. The `whatwg-fetch` module was added to mock a fetch response in the jest environment.
| | Before | After |
| - | ------ | ----- |
| Statements | 49.66% | 50.95% (+1.29%)|
| Branches | 37.73% | 39.13% (+1.4%)| 
| Functions | 46.45% | 48.94% (+2.49%) |
| Lines | 49.55% | 50.72% (+1.17%) |

LIVE-1689: Lib.ts tests

---

.storybook/preview.js
src/__snapshots__/storyshots.test.ts.snap
src/components/editions/article/index.tsx
src/components/editions/byline/index.tsx
src/components/editions/header/index.tsx
src/components/editions/headerImageCaption.tsx
src/components/editions/headerMedia/index.tsx
src/components/editions/pullquote/index.tsx
src/components/editions/styles.ts

Quick fix for a styling bug where in some situations the tablet header image would be wider than the viewport.
Also introduces `from.desktop` rather than `from.wide` for Editions components to correspond with Storybook viewport sizes.
@faresite I've butchered the `HeaderMedia` component, apologies. Please say if I've removed anything that needs to be there, particularly height values. When testing I couldn't find any need for them but I might be wrong. 
- Make tablet image width dynamic
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/108537131-26d49a80-72d5-11eb-8e55-eb1c57304ec0.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/108537156-2fc56c00-72d5-11eb-937c-f116500f768e.png" width="300px" /> |

LIVE-1709: removed fixed widths on tablet

---

config/cloudformation.yaml
riff-raff.yaml

After Simon's tech time talk about upgrading our instances to ARM-64 we are trying it out for Apps Rendering.
- We baked a new recipe in AMIgo, based on a clone of the current Apps Rendering AMI
- We changed the instance type to be `t4g.micro` from `t3a.micro`
We tested on CODE first to make sure everything was fine. This PR updates the same for PROD, and uses the new recipe. We may choose to delete the old recipe after this has been in production, to clear up after ourselves.
Paired with @marjisound and @dskamiotis

Add Graviton 2 ARM instance type

---

package-lock.json
package.json
src/client/nativeCommunication.ts
src/components/shared/epic.tsx

In the latest release ([PR](https://github.com/guardian/bridget/pull/71)) We have renamed:
- `FrictionScreenReason` -> `PurchaseScreenReason`
- `launchFrictionScreen` -> `launchPurchaseScreen` 
Since we have removed the old types this basically could count as a breaking change, but we're not in production yet, and this shouldn't break it for beta users either (basically they won't get the purchase screen pop up). 
I've considered this better than using the `nativeThriftPackageVersion` and peppering our codebase with if and else before going to prod.

LIVE-1659: Update to Bridget 1.8.0

---

src/atoms.test.ts
src/atoms.ts

Subtask of the [increase coverage ticket](https://theguardian.atlassian.net/browse/LIVE-1684)
| | Before | After |
| - | ------ | ----- |
| Statements | 50.95% | 60.82% (+9.87%)|
| Branches | 39.13% | 55.72% (+16.59%)| 
| Functions | 48.94% | 55.67 (+6.73%) |
| Lines | 50.72% | 60.09% (+9.37%) |

LIVE-1686: atoms.ts tests

---

src/components/editions/header/index.tsx
src/components/editions/headline/index.tsx

In Dotcom, users are able to add `display.showcase` on top of `design.comment` to trigger a different article header layout. However, in Editions we only have a single `comment` design so we need to ensure `design.comment` comes above `display.showcase` anywhere that's effected.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/109662723-44babe80-7b63-11eb-8114-08c6764bdf4c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/109662951-7f245b80-7b63-11eb-8159-d848f2f61c26.png" width="300px" /> |

LIVE-1834: move design.comment above display.showcase

---

src/components/editions/headline/index.tsx

Showcase styles should not be applied to interviews.
- Move Interview styles above Showcase styles in hierarchy
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/109673784-43db5a00-7b6e-11eb-9628-ff3b8b5b3a8f.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/109673738-39b95b80-7b6e-11eb-970e-e2c2fad2536b.png" width="300px" /> |

LIVE-1837: move interview above showcase in heirarchy

---

.github/workflows/screenshots.yml

The screenshot github action was depending on `ubuntu-latest` which in turn was depending on a 1.x version of AWS cli. 
The cli version we needed ships with ubuntu-18, however GH actions are phasing out an update to their `ubuntu-latest` tag as `ubuntu-20` which must have happened for us yesterday afternoon. This in turn uses aws cli 2.x which broke the s3 copy command.
Locking it at `ubuntu-18` instead of `latest` fixes this, 18 is still supported so it's ok for us to keep it for now. We might want to think of a health ticket in the future to update the screenshot job to use `ubuntu-20`.
Thanks to @jacobwinch and @frankie297 for helping out.

Lock screenshot action at ubuntu-18

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/series/index.tsx

Fixes a bug where sometimes the kicker split over two lines.
- remove `content-fit` css property
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/110334787-0f0e4d80-801b-11eb-919b-8c1bcef69154.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/110334844-1cc3d300-801b-11eb-80de-34b6b4fcd8ab.png" width="300px" /> |

LIVE-1901: remove content-fit

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/standfirst/index.tsx

Standfirst has a flex direction of row. This PR changes it to column. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/109955471-70ac8000-7cda-11eb-8083-2fc5803a8183.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/109955503-799d5180-7cda-11eb-841d-d2feb510356b.png" width="300px" /> |

Live 1851 - Standfirst Alignment

---

package-lock.json
package.json
src/client/article.ts
src/themeStyles.ts

[Jira ticket](https://theguardian.atlassian.net/browse/LIVE-1889)
Precursor to the emotion 11 updates. 
Updating to discussion-rendering 4.6.1 just before a major types update. 
Once discussion-rendering was updated, the `@guardian/types` were clashing with the main dependency and  image-rendering's dependency.
`image-rendering` is declaring `@guardian/types` as both dependency and as a peer dependency, which was causing a ts compiler conflict (even though the types were identical 🤔). 
This PR uses this commit https://github.com/guardian/image-rendering/commit/6ad32f87e66a794c2d385cf9e82d605fb9e8b35c which is based off image-rendering 5.0.2 but removing `types` as a peer dependency. 
This update is intermediary so both discussion and image rendering should be updated further up with the …

LIVE-1889: discussion-rendering v4.6.1

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/article/index.tsx

Adds missing vertical padding to body on devices below tablet.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/110456189-2bfd5c00-80c1-11eb-90b8-bbf00d8b7ed2.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/110456205-2ef84c80-80c1-11eb-8f39-1c7c7a341293.png" width="300px" /> |

LIVE-1895: Body Spacing

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headerImageCaption.tsx
src/components/editions/headerMedia/index.tsx
src/components/headerImageCaption.tsx

In Chrome 89, it seems there must have been a change that realigns with the spec. This in turn broke the caption icon, the way it has been broken on firefox for ages.
This PR fixes it so it works in chrome (older versions and 89) and safari (thanks @mxdvl)
Also I noticed there was some strange padding in the editions caption on wider viewports which I don't understand so I removed it. If anyone knows why it was there in the first place, do give a shout.
| before | after |
| -- | -- |
|![Screenshot 2021-03-09 at 12 38 20](https://user-images.githubusercontent.com/12860328/110471875-966bc780-80d4-11eb-9ac9-6362f0271d39.png) | ![Screenshot 2021-03-09 at 12 38 30](https://user-images.githubusercontent.com/12860328/110471909-9cfa3f00-80d4-11eb-900a-95f65fac4f1d.png) |
| before | after |
| -- | …

LIVE-1919: fix broken caption icon

---

src/components/anchor.tsx
src/renderer.ts

The live apps supports dark mode but Editions doesn't. This PR adds a useDarkMode prop to allow us to disable dark mode styles on body anchor links.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/110497577-7cd77980-80ee-11eb-88b8-5664acd8ccc1.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/110496256-36cde600-80ed-11eb-8fa1-fdb3ea956144.png" width="300px" /> |
| AR | 
| --- | 
| <img src="https://user-images.githubusercontent.com/20416599/110496317-45b49880-80ed-11eb-9171-43dd076cdf1c.png" width="300px" /> |

LIVE-1894: Add useDarkMode prop for link styling

---

src/components/atoms/interactiveAtom.tsx

In a majority of cases atoms should have a white background in dark mode on apps. However we are now creating interactive atoms with a styleset that allows them to have dark mode styles which should be shown on the default dark background. 
In this atoms I want to be able to override the `background: white;` in the atom CSS. Only atoms where there are special dark mode styles will do this. Currently I can't override it because of the `!important` on the style rule here. 
The styles here run after the styles from the atom so if they are more powerful or have the same power these styles win out.
So interactives atoms that have dark mode styles can have a dark background and not a white background in apps.

Remove '!important' from atom bg CSS

---

src/bodyElement.ts

Callouts without campaigns were rendering as generic embeds. This PR instead throws an error if no campaign is present.
** We might need to check if this is the correct behaviour - if callouts can exist without campaigns this will need ammending.
- add separate conditional to check if campaigns exist
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/110649372-70682500-81b1-11eb-8004-6142ba5d196a.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/110649416-7958f680-81b1-11eb-924b-2d38e16a36c9.png" width="300px" /> |

LIVE-1903: don't render callout as generic embed

---

config/cloudformation.yaml

Stolen from Phil's [PR](https://github.com/guardian/amigo/pull/544) but explains it quite clearly:
This PR aims to resolve https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation by making HTTPTokens 'required' when using the EC2 metadata service. Essentially amazon has released a more secure way of fetching metadata and they think that it should be enforced on all instances as the previous approach presented a security risk.
For more details on the metadata options see here https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-config.html#launch-configurations-imds

Use IMDSv2 metadata service

---

api-models/scala/version.sbt
src/item.test.ts
src/item.ts

Published a new scala package for apps-rendering-api-models 0.11.2
You can find the package in 
https://oss.sonatype.org/#nexus-search;quick~apps-rendering-api-models
and
https://repo1.maven.org/maven2/com/gu/apps-rendering-api-models_2.12/
**Other changes**: The tag for a match report is `tone/matchreports` but in Item we were checking for `tone/matchreport` and as a result the item was not created with football content. The tag checking was updated in this PR.
Test result: 
https://mobile.code.dev-guardianapis.com/rendered-items/football/2020/jun/23/tottenhams-harry-kane-back-on-target-to-deepen-west-hams-misery

Publish a new scala package for apps-rendering-api-models

---

src/client/article.ts
src/components/shared/epic.tsx
src/components/shared/epicContent.tsx
src/components/standard/article.tsx

Since merging emotion 11, client runtime styles are being blocked by CSP, this affected the footer and epic so far. The big mystery is why wasn't emotion blocking them before 🤔 Or maybe something else is happening, which we will need to investigate, but for now we need to fix the styles as they're user facing (even if just for beta users).
The fix here is not very nice and will need to think of something better .. Moving the styles up to the wrapper (like in https://github.com/guardian/apps-rendering/pull/1236). This mostly worked, except for the buttons. The `Epic` component uses `Source`'s `Button` component which is rendered client side.
I've kept the Source button for now however copied its styles up so they can be rendered server side, while we think of a better solution.
- changed …

LIVE-2093: Fix epic styles

---

package-lock.json
package.json
src/components/body.tsx
src/components/editions/article/index.tsx
src/components/editions/header/index.tsx
src/components/headerImage.tsx
src/components/headerVideo.tsx
src/components/shared/tags.tsx
src/fixtures/item.ts
src/item.test.ts
src/item.ts
src/renderer.ts
src/server/csp.ts
src/server/page.tsx

We need to be on `@guardian/types` v4.0.0 so we can work on the Letter templates, however types is already on v6.0.0 so updating this in one go.
Initially we thought we will have to wait until these v5.1.0 (opened before 6 was released) are merged:
- https://github.com/guardian/atoms-rendering/pull/232 (merged now)
- https://github.com/guardian/discussion-rendering/pull/479
- https://github.com/guardian/image-rendering/pull/253
I opened this PR as a draft so we're ready to go, but looks like it that the build doesn't need these PRs merged after all 🤷‍♂️ .. possibly because nothing is conflicting in our codebase between v3 and v6 🎉 Therefore I'm publishing this PR to unblock the team.

LIVE-1740: Update @guardian/types to 6.0.0

---

src/server/csp.ts

Instagram embeds were previously broken in Editions. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/114043130-ed082500-987d-11eb-96bc-3c9a2db1d6bf.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/114043181-f72a2380-987d-11eb-8544-d93c6cde6581.png" width="300px" /> |

LIVE-2132: fix editions instagram

---

src/server/csp.ts

@JamieB-gu commented on a previously merged PR (https://github.com/guardian/apps-rendering/pull/1250) with a suggestion of using the same `frame-src` script rather than a new one, this PR implements that suggestion.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/114043130-ed082500-987d-11eb-96bc-3c9a2db1d6bf.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/114043181-f72a2380-987d-11eb-8544-d93c6cde6581.png" width="300px" /> |

LIVE-2132: use same frame-src script 

---

src/components/embed.tsx
src/renderer.test.ts
src/renderer.ts

Removing atoms and embeds as part of Editions embed fixes.
- remove Editions audio atom
- remove Editions callout
- remove Editions quiz atom
- remove Editions Spotify embed
- remove Editions chart atom

Live 1182 remove editions embeds

---

src/__snapshots__/storyshots.test.ts.snap
src/components/body.tsx
src/components/byline.tsx
src/components/comment/article.tsx
src/components/editions/article/article.stories.tsx
src/components/editions/article/index.tsx
src/components/editions/header/index.tsx
src/components/editions/headline/index.tsx
src/components/editions/standfirst/index.tsx
src/components/headline.tsx
src/components/metadata.tsx
src/components/standfirst.tsx
src/fixtures/item.ts
src/item.ts
src/renderer.ts

Letter articles are not currently supported in Editions.
Also AR currently renders letters as comments and this separates the two types of articles
Because the Live App designs don't distinguish between the two, we expect Design.Comment and Design.Letter to apply the same styles. However, the existing code only knows to check for Design.Comment to apply said styles - any pieces that are now parsed as Design.Letter will fall through these checks. This means that Design.Letter pieces will likely have incorrect styles applied to them on the Live Apps.
- Created letter head component
- added Letter styling to nested Header components for Editions
- Derived Letter type from tags
- Added handling for letter to apps rendering
paired with @abeddow91 
**NOTE**: We are awaiting the update to …

Live 993 letter header

---

package-lock.json

Keeps our dependencies up-to-date.
- Bumped lodash to 4.17.21

Bump Lodash To 4.17.21

---

package-lock.json
package.json
webpack.config.ts

We have introduced webpack 5 in https://github.com/guardian/apps-rendering/pull/1215 
Webpack 5 strips away any automatic nodejs polyfills, including Buffer (you can see the list of node libs for browser [here](https://github.com/webpack/node-libs-browser)). 
Bridget (and more technically Thrift) relies on Buffer, hence webpack 5 broke features like following authors or launching the lightbox. We need to manually polyfill node libs that we want now, so I'm introducing `feross/buffer` which is the same buffer polyfill webpack v4 was using.
- add `buffer` as a dependency
- update webpack config with `resolve.alias` and the Provide plugin.

LIVE-2208: fix bridget client / server

---

src/components/embed.tsx
src/server/csp.ts
src/server/editionsPage.tsx
src/server/page.tsx

We're looking to include additional atoms and embeds in Editions where possible. This PR brings together the AR and ER approaches to CSP and allows us to render `interactive` atoms.
See this article for an example:
http://localhost:8080/world/2020/jun/10/uk-coronavirus-lockdown-20000-lives-boris-johnson-neil-ferguson?editions
- Use `meta` component for Editions header
- share `csp` component between editions and AR
- add additional fields (rules?) to csp functions 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/114376267-6012e380-9b7d-11eb-8c8c-82c2869d57e8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/114376318-6c973c00-9b7d-11eb-9325-dae406519d71.png" width="300px" /> |

LIVE-2148: interactive atoms

---

src/atoms.test.ts
src/atoms.ts

Timeline atoms weren't rendering in either Editions Rendering or Apps Rendering. 
This PR removes the check for timeline `events` that blocked the atom from rendering **when a user had inputted all data as a description**  - this seems to be the standard way timeline atoms are used.
https://www.theguardian.com/world/2018/jun/18/yemen-crisis-saudi-coalition-demands-houthis-unconditional-withdrawal-from-port
- Remove check for timeline events
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/114437391-66757f80-9bbe-11eb-8fe7-6a23ac06e025.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/114437286-404fdf80-9bbe-11eb-8ed4-7ab09704041d.png" width="300px" /> |

LIVE-2135: remove check for timeline events

---

package-lock.json
package.json

Picks up changes from https://github.com/guardian/node-riffraff-artifact/pull/24.
@AWare in theory there should be no impact on the consumer, it's just internal changes to the tests?
- Bumped `node-riffraff-artifact` to 0.2.0

Bump `node-riffraff-artifact` To 0.2.0

---

webpack.config.ts

Bridget calls were not working (lightbox, follow etc...) because of Webpack 5 stopped polyfilling some libs like Buffer (https://github.com/guardian/apps-rendering/pull/1249)
That problem was fixed in the mentioned PR, however the prod configuration wasn't providing the Buffer alias, so I've updated it, thinking I hit the jackpot with that one.. alas no .. it turned out eventually that none of our JS was running because webpack 5 was prefixing our asset location with "auto" (a bug that took me hours to get to 😑). If you look at any current AR article in prod you'll see that in the html at the bottom the script tag looks something like this:
```html
<script src="/assets/autoarticle.39866c4a7d757b6f43ac.js"></script>
```
Adding the `publicPath: ''` to the webpack config solves it .. what a …

Webpack 5 —  The Sequel 🕸📦

---

config/cloudformation.yaml

Adds the Wazuh Security Group to our instances
Use this command to test the service is active and running:
```ssm cmd -c "service wazuh-agent status | grep Active && journalctl -u wazuh-agent | grep -E \"(Valid|error)\"" -t app,stage,stack -p <janus_profile>```
You should see something similar to:
```========= i-040399xxxxxxx =========
STDOUT:
Active: active (running) since Tue 2021-02-09 12:16:06 UTC; 6 days ago
Feb 09 12:15:58 ip-10-248-48-90 authenticate-with-wazuh-manager.sh[1060]: 2021/02/09 12:15:58 agent-auth: INFO: Valid key created. Finished.
STDERR:
========= i-01fc71000xxxxxx =========
STDOUT:
Active: active (running) since Mon 2021-02-15 11:20:29 UTC; 6h ago
Feb 15 11:20:21 ip-10-248-48-147 authenticate-with-wazuh-manager.sh[1068]: 2021/02/15 11:20:21 agent-auth: INFO: Valid …
```

Add Wazuh Security Service

---

package-lock.json
package.json
src/client/article.ts
src/client/nativeCommunication.ts
src/native/nativeApi.ts

We need to send targeting params to the native apps on init. 
Bridget was updated to 1.9.0 to use the new service (https://github.com/guardian/bridget/pull/72)
- Bump to Bridget 1.9.0
- Create the analytics Bridget client
- Use the client to send targeting params on init

LIVE-2179: Send targeting params on init

---

src/components/calloutForm.tsx

While testing the callout submissions in AR we found that we were using the campaign id for the form id but the form id that is stored in formstack is the campaign -> fields -> formId
related to this ticket: https://theguardian.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=LIVE&modal=detail&selectedIssue=LIVE-282
- the value for the form was changed to use the campaign fields formId

LIVE-282 - callout submission form id corrected

---

package-lock.json
package.json
src/__snapshots__/storyshots.test.ts.snap
src/client/article.ts
src/components/footerContent.tsx
src/native/nativeApi.ts

At present the 'privacy settings' and 'privacy policy' in the article footers are links. We would like these to call Bridget functions, which the native layer can then use to open the appropriate settings section.
[JIRA ticket](https://theguardian.atlassian.net/browse/LIVE-2183)
- create the Navigation bridget client
- add dom element ids to the footer link
- trigger bridget calls on link click
- Bump Bridget to `1.10.0` from https://github.com/guardian/bridget/pull/73 
iOS PR https://github.com/guardian/ios-live/pull/5660

LIVE-2183: Bridget footer links 🦶🔗

---

src/relatedContent.test.ts
src/relatedContent.ts

We want the related content items in SSR articles to open in a native view, since there's already a built-in guardian link parser that will open the item in a native view controller, we can use this as we go into prod. in the future we will need to do something about it (Bridget probably), as this means all related items in an SSR article will open up in the legacy templates.
| before | after |
| -- | -- |
| ![2021-04-26 15 17 42](https://user-images.githubusercontent.com/12860328/116098539-14932600-a6a3-11eb-9e18-48ae4e3adcb7.gif) | ![2021-04-26 15 20 55](https://user-images.githubusercontent.com/12860328/116098619-207ee800-a6a3-11eb-9372-e82eabb3919d.gif) |

LIVE-2348: Prefix related item link with theguardian.com

---

src/components/editions/avatar/index.tsx
src/components/editions/byline/index.tsx

Sometimes comment pieces are missing a `contributor` which causes the template not to load, this PR adds a conditional to check for this.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/116425810-7afe7c80-a83a-11eb-9228-758192caab65.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/116426195-cf096100-a83a-11eb-90ec-389092953fa4.png" width="300px" /> |

LIVE-2138: add conditional

---

src/components/editions/article/index.tsx

Recipe article types were being used by production but not included in Editions Rendering. This PR adds `Design.Recipe` to the list of rendered articles to fix that.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/116437580-7e4b3580-a845-11eb-997c-01bc98b63a83.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/116437627-8b682480-a845-11eb-9a86-59db42d99547.png" width="300px" /> |

LIVE-2138: add recipe article type to Editions as standard template

---

src/__snapshots__/storyshots.test.ts.snap
src/capi.test.ts
src/capi.ts
src/components/editions/article/article.stories.tsx
src/components/editions/article/index.tsx
src/components/editions/headerMedia/index.tsx
src/components/footballScores.tsx
src/components/standard/article.tsx
src/components/teamScore.tsx
src/fixtures/item.ts
src/server/footballContent.ts
src/server/server.ts

When developing, we were missing football match report data from the CAPI response as that data is provided separately from PA. 
This PR adds a  'show-references' parameter to the CAPI request to return football club and competition ids, which we can then parse into a new api request to PA, which provides us with match data for the corresponding teams.
We then pass that response into the apps rendering flow with the rest of the content.
We then use the new football scores data to populate a `FootballScores` component that lives in the Editions article header.
* for Editions styles need updating to match new Editions designs (😖 ) but this should provide all necessary functionality.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/116441589-7d1c …

Live 2351 football scores

---

src/client/article.ts
src/components/shared/card.tsx
src/relatedContent.test.ts
src/relatedContent.ts

Follow on from #1277. Those changes actually only added the prefix when running locally, because they modified the mocked CAPI response. In PROD/CODE MAPI is setting the link URL.
That said, I think it makes more sense for AR to control the link `href` in any case, since it's a rendering concern. Therefore I've updated MAPI to pass through the content `id` instead (https://github.com/guardian/mobile-apps-api/pull/1707), and made changes in this PR to build the URL from that.
- Passed through the content id for related content
- Built full URL, from id, in the component

Use Dotcom For Related Item Links

---

src/client/article.ts
src/client/nativeCommunication.ts

Paired with @jordanterry on this work.
Some changes to page layout were not being reported to the native layers, which meant ad positions weren't being updated.
Although articles in the live apps are rendered in webviews (via apps-rendering), ads are actually native elements that are rendered on top of the webview itself. AR includes empty placeholders in the page, and reports the location of these placeholders to the native layers, so they know where to place the ads. Sometimes, if the page layout changes, AR has to re-send these locations so that the native layers can update the positions to match.
We've noticed that, occasionally, ads on the Android app are misaligned. @jordanterry discovered that this seems to happen on articles that include rich links, although it's not always …

Fix Ad Slots On Pages With Rich Links

---

src/components/editions/article/article.stories.tsx

Chromatic's visual diff is repeatedly reporting changes to the article components. However this difference is actually down to small changes in how images are rendered between screenshots.
It's possible to reduce the sensitivity of this visual diff using the [`diffThreshold` parameter](https://www.chromatic.com/docs/threshold) (as seen in https://github.com/guardian/image-rendering/pull/137), which is what this PR does.
- Updated the `diffThreshold` for the article stories to make the visual diff less sensitive

Raised Chromatic Diff Threshold For Article Stories

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/footballScores/footballScores.stories.tsx
src/components/editions/footballScores/index.tsx
src/components/editions/headerMedia/index.tsx
src/components/editions/teamScore/index.tsx
src/components/genericEmbed.tsx

We've recently added the `FootballScores` component to the Editions match report header. This PR creates new Editions specific `FootballScores` components in order to accommodate the different layouts.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/117038494-9ae0e500-acff-11eb-8445-e2635745e628.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/117038540-a8966a80-acff-11eb-8b40-717261eaad8c.png" width="300px" /> |

LIVE-1249: update layout to match new designs

---

src/components/shared/bylineCard.tsx

`position: absolute` [needs](https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute) a positioned ancestor.
This was broken in Safari (although weirdly not in Chrome or FF).
- Set `position: relative` to fix `position: absolute` bug
| --- | --- |
| ![before](https://user-images.githubusercontent.com/53781962/117312505-00a6ab80-ae7d-11eb-8ea6-6a871c1a2822.jpg) | ![after](https://user-images.githubusercontent.com/53781962/117312514-02706f00-ae7d-11eb-8a67-9b8670accdc3.jpg) |

Fix Comment Cards In Related Content

---

src/components/shared/bylineCard.tsx

An oversight in #1284 meant that "Comment" variations of the related content cards weren't updated to use dotcom links (because they live in a separate component). This remedies that.
- Also use dotcom links for comment cards

Use Dotcom Links For Related Comment Cards

---

src/components/shared/relatedContent.tsx

If there isn't any related content then we don't want to show the "Related content" header, because there won't be anything below it.
- Don't render the related content element if the list of content is empty
| --- | --- |
| ![before](https://user-images.githubusercontent.com/53781962/117292267-e7dfcb00-ae67-11eb-977a-90a54b01029d.jpg) | ![after](https://user-images.githubusercontent.com/53781962/117292276-ea422500-ae67-11eb-8a1f-366de0c0731a.jpg) |

Hide Empty Related Content

---

src/components/embed.tsx
src/components/embedWrapper.tsx
src/components/genericEmbed.tsx
src/embed.ts

Editions was rendering email-signups as generic embeds. We don't want email-signups in Editions but we need to keep generic embeds - this PR separates out email signups into their own embed type so we can mute them in Editions.
- add `EmailSignup` type to `Embeds`
- parse generic embed html to check if iframe `data-component` attribute contains `email-embed`
- mute `EmailSignup` embeds in Editions.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/117332347-9f3c0800-ae8f-11eb-998a-eb679d7bbecb.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/117332399-b24ed800-ae8f-11eb-8402-bb0acc91517c.png" width="300px" /> |

LIVE-2368: add new EmailSignup embed type

---

src/__snapshots__/storyshots.test.ts.snap
src/components/embed.tsx
src/components/embedWrapper.tsx
src/components/genericEmbed.tsx
src/embed.ts

`TikTok` embeds were lacking a distinct type and always rendered as `Generic` embeds. This PR parses `generic` embeds and separates `TikTok` embeds into their own newly created type.
- create new `TikTok` embed type
- parse `Generic` embed types
- block embed overlays on `TikTok` embed type
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/117798985-93629400-b249-11eb-8eba-6ccbf371deb5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/117799017-9eb5bf80-b249-11eb-9f34-47a54c82465a.png" width="300px" /> |

LIVE-2395: add tiktok to embed types 

---

package.json
webpack.config.ts

They're not doing anything any more. As of #1228 we're using the [TypeScript compiler](https://github.com/guardian/apps-rendering/blob/dddeb4ae1f85fa1ec16f31cb8d9ed2d89605707d/tsconfig.json#L9) to handle our React and Emotion transpilation steps. Therefore there's no need to also do this with Babel.
For more information see [the `tsconfig` docs](https://www.typescriptlang.org/tsconfig#jsx), these [other `tsconfig` docs](https://www.typescriptlang.org/tsconfig/#jsxImportSource), and the [React blog post](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) on the new JSX transform.
Thanks to @tjmw for helping me discover this! 🙈
- Removed `@babel/preset-react` usage from webpack
- Removed `@babel/preset-react` and `@emotion/babel-plugin` from deps

Stop Using Babel React Transforms

---

src/lib.ts

@joecowton1 pointed out that having multiple variations of the `pipe` function (`pipe2`, `pipe3` etc.) can be confusing. As a result I've refactored to make a single variadic `pipe` function instead ("variadic" means that it takes a variable number of arguments). I believe this solution was also suggested a while back by @alexduf but I never got around to implementing it.
This change is achieved by making use of [TypeScript's support for overloaded functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads). The `fp-ts` library was a helpful reference point here for figuring out suitable type signatures, as they have some [similar functions](https://gcanti.github.io/fp-ts/modules/function.ts.html#pipe) in their API.
I've also kept `pipe2` and `pipe3` …

Variadic `pipe`

---

src/capi.ts
src/embed.ts

Ideally we'd like all `Instagram` embeds to render as structured `Instagram` embeds regardless of whether they're inputted as `Generic` embeds or structured embeds. This PR extracts the Instagram post id from a generic embed and creates a structured embed.
Two questions:
- These new embeds don't pass CSP on AR for some reason - why? From what I can tell the embed is exactly as it should be.
- the `parseGenericInstagram` function is currently returning an empty string to appease the `Instagram` type expectation - is there a better way of doing this?
- add condition to parse `Instagram` embeds separate from `Generic` embeds
- extract `id` from generic embed `html` field
- map to new structured `Instagram` embed
- running apps rendering go to …

LIVE-2148: map generic instagram to structured instagram embeds

---

src/components/comment/cutout.tsx

The Contributor name (link) is not clickable and therefore does not take you to the full list of articles by that contributor.
Currently the `Cutout` component is in front of the contributor link. 
Potentially the may have slipped through the testing net due to testing in localhost browser in full/wide view, where the cutout image background would not cover the contributor name/link.
- Modified `imageStyles` for `Cutout` component to include `pointer-events:none`
To test ensure that in localhost the browser is set to Responsive and iPhone of Samsung
Please note: the cutout image covers part of the contributors name, see screenshot:
As you can see the background of covers contributor link in `responsive` view mode (how it renders in the app)
| Default Browser | Responsive Browser |
| --- | …

LIVE-2449 - Fix dead contributor link

---

.github/dependabot.yml

Using dependabot to keep GH Actions up-to-date.
- Added dependabot for GH Actions

Add Dependabot For GH Actions

---

src/server/editionsPage.tsx

Remove the duplicate style declaration within the editions article template.

LIVE-2526 : Remove duplicate styles

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/standfirst/index.tsx

Fixes incorrect font styling on `analysis` standfirst.

LIVE-2550: fix standfirst font

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headline/index.tsx

Remove Editions custom font weight 400 from `interview` headline inline with design updates

Remove custom font-weight on interview headline

---

src/server/editionsPage.tsx

Editions have a JS file that lives within an asset/js folder, this PR just updates the path to reflect that.
From: `editions.js`
To: `assets/js/editions.js`

Fix: updated editions.js path

---

src/server/editionsPage.tsx

Fonts were broken when working on editions locally.
- Add switch to use different font path locally
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/121225846-d84a0c80-c881-11eb-8022-e86c248de9af.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/121225893-e1d37480-c881-11eb-930b-75d617893e1f.png" width="300px" /> |

LIVE-2568: add switch for fonts dev vs prod

---

src/components/editions/byline/index.tsx

Immersive articles had incorrect share icon colours.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/122440497-86496b00-cf94-11eb-94e2-5a8034f7c39b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/122440539-906b6980-cf94-11eb-8fc1-dcc61c9f42e4.png" width="300px" /> |

LIVE-2538: change icon colour settings

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headerMedia/index.tsx

Header media images for Immersive / Interview templates where rendering at the wrong height. 
- add fixed height for mobile images
- add image sizes to media queries
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/122429425-affd9480-cf8a-11eb-8495-1e3bb57d14a3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/122429499-bbe95680-cf8a-11eb-85dd-21c851adc83c.png" width="300px" /> |

LIVE-2606: add fixed heights

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headline/index.tsx
src/components/editions/standfirst/index.tsx

Update styling in line with new `Gallery` designs.
- Add right border for tablet
- Update font styling on `headline` and `standfirst`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/122819064-d8aac480-d2d1-11eb-8b27-f57cea93650e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/122818035-98971200-d2d0-11eb-818d-d817fbb03c98.png" width="300px" /> |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/122819207-0abc2680-d2d2-11eb-9021-c6ae017f5608.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/20416599/122818021-946af480-d2d0-11eb-970f-a69311327f06.png" width="300px" /> |
| --- | --- |
| <img …

Update gallery styles

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headerMedia/index.tsx

Full width images were too long on mobile and poor resolution.
This PR changes the image size we load initially to bring it into line with Apps-Rendering. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/122916189-88c11180-d354-11eb-9e1b-108ce067e683.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/122916138-78109b80-d354-11eb-99fe-50e03955623b.png" width="300px" /> |

LIVE-2637: change image sizes

---

config/cloudformation.yaml

This PR updates the public subnets used for the apps-rendering `load balancer` & `auto scaling group`. 
The steps to prepare the env for this change is as followed:
1- remove one subnet that is not used from load balancer and auto scaling group, then update availability zone in auto scaling group to match the subnets and update stack in AWS
2- manually increase desired capacity in auto scaling group to 2 (to create new instance in the new subnet)
3- run command to terminate the instance with old subnet: aws --profile mobile autoscaling terminate-instance-in-auto-scaling-group --should-decrement-desired-capacity --region eu-west-1 --instance-id i-0babb7a85d0aab8a5
4- When old subnet is not in use any more, remove the old subnet from cloud formation and update stack
5- add the remaining new …

Live 2628 move apps rendering to public subnet

---

src/client/article.ts
src/components/follow.tsx
src/components/followStatus.tsx
webpack.config.ts

To prevent `image-rendering` being bundled client-side, as discussed in https://github.com/guardian/apps-rendering/pull/1353#discussion_r658676804.
- Remove webpack `resolveOptions` config for crypto
- Imported `FollowStatus` from new file in client bundle
- Extracted `FollowStatus` from `follow.tsx`
- Simplified `follow.tsx`
- Added `followStatus.tsx`

Extract `FollowStatus`

---

src/components/editions/article/index.tsx

We were missing dropcaps on Editions.
- add styles
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/123664695-7ac93000-d82f-11eb-9db5-d4e6ee9ac090.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/123664767-8ddc0000-d82f-11eb-9dae-18bd1e671338.png" width="300px" /> |

LIVE-2666: add dropcaps to editions body

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/placeholder/index.tsx
src/components/editions/placeholder/placeholder.stories.tsx
src/components/editions/utils/useOnlineStatus.tsx
src/components/editions/video/index.tsx

If a user is offline (and the header video is not already cached), the user will see an error message.
This PR creates a hook to check the online status based on this approach: https://levelup.gitconnected.com/useonlinestatus-a-react-hook-to-know-when-your-app-is-offline-2d06e4e536a
It also creates a placeholder component. It currently uses an inline svg, there is an open PR to add the correct icon to Source after which we should import the SVG from there: https://github.com/guardian/source/pull/840
- create `useOnlineStatus` hook
- create `Placeholder` component
- render placeholder in `video` component if offline
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/123988429-ecd07f00-d9bf-11eb-98e1-1a0a0f2387b3.png" width="300px" /> | <img …

Live 2632 offline header videos

---

src/__snapshots__/storyshots.test.ts.snap
src/components/follow.tsx
src/components/followStatus.tsx

https://theguardian.atlassian.net/browse/LIVE-2679
There were two reasons for this to happen, a) the viewbox was missing so the svg elements didn't know what to scale towards. b) the button min-height didn't accommodate the height of the svg itself.
- Add min height to the follow button (Same height as the svg)
- add the svg viewbox
| --- | --- |
| <img src="https://user-images.githubusercontent.com/12860328/124439526-6fb35a00-dd71-11eb-88c8-794ced3fcf25.png " width="100px" /> | <img src="https://user-images.githubusercontent.com/12860328/124439561-79d55880-dd71-11eb-928c-41839f0958a5.png" width="100px" /> |

LIVE-2679: Fix follow icon cropping

---

src/__snapshots__/storyshots.test.ts.snap
src/components/list.stories.tsx
src/components/list.tsx
src/components/listItem.stories.tsx
src/components/listItem.tsx
src/renderer.ts
src/storybookHelpers.ts

On-going work to tidy up the renderer file. This time I'm pulling a couple of components out into their own files and creating stories for them.
- Extracted `ul` and `li` from renderer into `List` and `ListItem`
- Added a storybook helper for selecting `Design`
- Added stories for `List` and `ListItem`
- Removed liveblog styling for `ListItem`

Extract Lists From Renderer

---

src/components/editions/standfirst/index.tsx
src/renderer.ts

Production `Standfirst` overrides weren't appearing on ER. The Editions `Standfirst` component doesn't use all of the nodes that Apps use and because of this it was accidentally filtering out the overrides, which can be text elements and are not currently accounted for.
This PR refactors the `Standfirst` render logic to explicitly filter out unwanted nodes if it's an Editions article before using the standard `Standfirst` render logic allowing text elements to flow correctly.  
Big thanks to @JamieB-gu for his help and influence!
- Convert the `noLinkStandfirst` function to a filter for better readability and clearer intention
- Update param names
| --- | --- |

LIVE-2738-Trail-Override 

---

src/client/nativeCommunication.ts
src/styles.ts

This PR prepares for square ads format once enabled. Only for first ad in an article.
- prepare a boolean flag to turn on square ads
- `.ad-slot-square` styles.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/12860328/124645187-0aec2280-de8b-11eb-8bcb-2533ffe123a3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/12860328/124645229-16d7e480-de8b-11eb-9681-467e4d62fd99.png" width="300px" /> |

LIVE-2566: Prepare for square ads

---

src/__snapshots__/storyshots.test.ts.snap
src/client/editions.ts
src/components/editions/headerMedia/index.tsx

We we're seeing the desired behaviour from the `useOnlineStatus` hook when templates were rendered.
- Hydrate `Video` component
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/123988429-ecd07f00-d9bf-11eb-98e1-1a0a0f2387b3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/123988543-04a80300-d9c0-11eb-8cba-862fbc3675d5.png" width="300px" /> |

LIVE-2708: hydrate editions video component

---

config/cloudformation.yaml

This PR sets removes the public IPv4 address from the EC2 instances. This change would resolve the relevant security issue in AWS security Hub.
Find more info in https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-9-remediation
Deployed and tested in code

LIVE-2065 - Set AssociatePublicIpAddress to false

---

src/server/editionsPage.tsx
src/server/server.ts

We need to override article theme styles based on which fronts container they live in. From the perspective of Editions Rendering this means we need to be able to pass a parameter containing the `theme` value from Editions backend, and use that to override the existing article theme value.
- get `themeOverride` from query params
- pass value through to article `item` level

LIVE-2788: use params to override theme

---

src/server/server.ts

We use a query param to override the Theme which comes as a string. As such, we need to switch on type string rather than int.

LIVE-2788 : Theme Override

---

src/components/editions/utils/useOnlineStatus.tsx

The previous incarnation of the `useOnlineStatus` hook was proving slow and ineffective. This version simplifies it.
- simplify `useOnlineStatus` hook

LIVE-2708: simplify onlineStatusHook

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/series/index.tsx

Apps rendering doesn't currently support the `GT Guardian Titlepiece` font which was being used in the series/kicker component. This meant the font was falling back to Georgia instead. As a temporary fix, this PR replaces the `GT` with  `GH Guardian Headline`.  
Changing to this font also brings us inline with Source's font sizes (we were overriding these before to make GT smaller than Source wanted) but this is something for Design to decide if we want to stick with this longer term. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/125833596-7317e7b8-5047-4da2-a63e-639aff1c4f17.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/125833153-879918e6-05db-4897-b869-7c771fefba45.png" width="300px" /> |

Replace GT with GH as Editions doesn't support GT

---

src/__snapshots__/storyshots.test.ts.snap
src/components/richLink.tsx

Currently using the scaling slider to scale up articles results in the text around rich links becoming large and hard to read. We'd like to push rich links to full width beyond a certain scaling threshold to prevent this. One way to achieve this is to use a `rem`-based breakpoint, below which they become full-width.
- Added a `rem`-based breakpoint for `mobileMedium`, below which rich links are full width
| light mode | dark mode |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/12860328/125801460-f4243ab8-5e26-44e9-af33-847e7f6e7d82.png" width="300" /> | <img src="https://user-images.githubusercontent.com/12860328/125801553-5e6b3a58-3c4f-4498-a106-a485730f5135.png" width="300" /> |

Rich Link For Narrow Breakpoints

---

src/server/editionsPage.tsx
src/server/server.ts

Fonts and JS were loading incorrectly on `https://mobile.guardianapis.com/`.
- add `EditionsEnv` enum

LIVE-2836: update asset paths for fonts and js

---

src/server/editionsPage.tsx

The previous commit https://github.com/guardian/apps-rendering/pull/1404 broke the asset paths for Editions. This commit reverts those changes.

LIVE-2836: revert changes which break asset path

---

package.json

The [`browserslist` field](https://github.com/browserslist/browserslist) in `package.json` is used by a number of build tools to determine which browsers to target with their build output. You specify a list of browsers here, and that list is used to determine which features, polyfills, workarounds etc. to include.
We support four apps in Apps-Rendering:
- iOS Live App
- Android Live App
- iOS Editions App
- Android Editions App
Our `browserslist` is determined by the oldest versions of iOS and Android supported by these apps. This PR updates our configuration to match the oldest versions currently supported.
- Bump minimum iOS version from 11 to 12.

Minimum Supported iOS Version Is 12

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/article/article.stories.tsx
src/components/embedWrapper.stories.tsx

Chromatic kept on asking to approve false positive changes that were a result of chromatic's quality threshold, this PR changes the tolerance to 0.4 as that was the closest tolerance I found that wouldn't give false positives.
This PR also addresses the fact the instagram embed diff kept on appearing because the post was quite popular and the likes amount kept on changing. I've chosen a post that is a lot less popular, so hopefully this won't happen as often, however it will happen from time to time.
- Change chromatic diff tolerance to 0.4
- Change the instagram post id
| **0 tolerance** |
| --- |
| <img src="https://user-images.githubusercontent.com/12860328/127180829-c3710e35-0ae8-4f2d-bca3-68d31f67eac7.png" width="400px" /> |
| **0.3 tolerance** |
| --- |
| <img …

Chromatic tweaks

---

src/components/body.tsx
src/components/byline.tsx
src/components/comment/article.tsx
src/components/headerVideo.tsx
src/components/headline.tsx
src/components/img.ts
src/components/metadata.tsx
src/components/richLink.tsx
src/components/standfirst.tsx
src/components/tags.tsx
src/editorialPalette.ts
src/item.ts
src/renderer.ts
src/server/page.tsx
src/styles.ts

Editorial articles were rendering incorrectly because they were being parsed as a Comment. Whilst this is ok for AR, as they share designs, ER visually distinguishes between Editorial and Comment.  
In investigating this, a bug was discovered whereby Letter and Editorial were not always styled the same as Comment (which they should be). This PR fixes this too. 
- Move Editorial above Comment in parser to style Editorial differently in ER.
- Add Editorial and Letter where Comment styling is being applied in AR only. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/127509437-07efde06-3930-41d8-b3f8-59854210b2f5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/127509570-7f72b283-2f65-4fa3-a316-78e6ded9b6d6.png …

LIVE 2857 & 2864:  Editorial template

---

src/components/meta.tsx
src/server/editionsPage.tsx

Users on Editions want to be able to pinch and zoom on articles. This was previously disabled for all articles. This PR adds a metatag to allow zooming on editions articles only.

LIVE-2860 :  Pinch and Zoom

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/article/article.stories.tsx
src/components/editions/byline/byline.stories.tsx
src/components/editions/byline/index.tsx
src/components/editions/standfirst/index.tsx
src/components/editions/standfirst/standfirst.stories.tsx
src/fixtures/item.ts
src/item.ts

We have repeated user feedback from users trying to share articles and the button doing nothing. This PR copies the logic from Mallard so a share icon will not be rendered when there is not weburl present.
- add `shareIcon` checkbox to relevant stories
- add `showShareIcon` logic to `standfirst` and `byeline`
- add min-height to byeline to fix height when icon is not there
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/127832442-716dd20d-eb57-41fc-9c29-cdb8b8834af7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/127832499-50d5ad22-7652-4ad1-bdd5-2e7bcf4a1e5d.png" width="300px" /> |

LIVE-2875: hide shareIcon if no webUrl

---

src/parser.md
src/parser.test.ts
src/parser.ts

A module for parsing `unknown` values into other TypeScript types. It's generic enough to work for any `unknown` value, but is probably most useful for parsing JSON. It attempts to simplify the parsing process by abstracting the repetitive manual checks behind a declarative-style API, based on parser combinators.
For more details see the included [`parser.md` file](https://github.com/guardian/apps-rendering/blob/12c9ba1baeeb2541c37a318c945c98e70fe5493b/src/parser.md) (I think this module is self-contained enough to justify its own README).
I'd like to try incubating this in AR for a while to see if we find it useful for managing some of our parsing needs (e.g. JSON). If it does prove useful we can lift it up into a library for use in other projects (e.g. `mobile-purchases`).
- Added the …

Unknown Parser

---

src/components/editions/headline/index.tsx

Styles were wrong on comment articles.
- add check for avatar image to headline component
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/128216445-2c292c26-8f4a-4651-aeb1-c2e37b12bc15.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/128216505-78aab53e-2cfe-4f2c-af11-f97439ef9213.png" width="300px" /> |

LIVE-2892: remove headline padding when no avatar

---

src/server/editionsPage.tsx
src/styles.ts

Fixed a runtime error in the AR client script.
- Stopped importing `appIdentity` into `styles` module
- Editions preview fonts now take s3 path as an argument

Fix AR Client Script

---

package-lock.json
package.json
src/__snapshots__/storyshots.test.ts.snap
src/components/body.tsx
src/components/editions/article/article.stories.tsx
src/components/editions/article/index.tsx
src/components/editions/header/index.tsx
src/fixtures/item.ts
src/item.ts

Following a [discussion](https://github.com/guardian/types/pull/164) about how to parse the Corrections and Clarifications article, it was added as a new design type. 
This PR adds the correction type and renders it on Editions and Live and replaces [1417](https://github.com/guardian/apps-rendering/pull/1417)
- Bump @guardian/types to 8.0.0
- Add Design.Correction
- Add Design.Correction header to Editions without lines or byline components. 
- Render Design.Correction as standard article on Live Apps.
- Add Design.Correction to Storybook 
| <img src="https://user-images.githubusercontent.com/20416599/127520242-1e07002b-90c1-4486-8e7c-942cb79d41ae.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/127520229-b096763c-dfa0-48c3-ab5f-c3693f …

LIVE-2859 : Add Corrections and Clarifications Design 

---

src/components/editions/headline/index.tsx

Reverts guardian/apps-rendering#1430

Revert "LIVE-2892: remove headline padding when no avatar"

---

src/parser.ts

There were some docs missing for the `oneOf` function introduced in #1384. This adds those docs.
- Added docs for the oneOf parser function

Docs For `oneOf`

---

src/server/server.ts

We weren't handling `Promise` rejection correctly, which caused requests to hang on error.
We had a recent bug in Editions, which we traced back to a hanging request in the group of requests the Editions backend makes to AR. I believe this issue would also have an impact on the live apps, although perhaps with less severe consequences.
As seen in the temporary fix in #1436, it was triggered by a crash in the rendering code. However, that should have resulted in a rapid 500 response rather than a hanging request.
I believe what happened was that the crash caused a `Promise` to be rejected, and we weren't handling that rejection. As a result, the code path that catches errors and sends an Express response was not hit, and so the request stayed open indefinitely.
I suspect we didn't realise …

Correctly `await` Promises In Express

---

src/renderer.ts

Added support for subscript and superscript tags in body text. This will fix them on the Apps and Editions.
- Added checks for `SUB` and `SUP` in text renderer functions
Taken from [this piece](https://www.theguardian.com/science/across-the-universe/2013/sep/04/equation-alien-life-universe).
| --- | --- |
| ![sub-sup-before](https://user-images.githubusercontent.com/53781962/129036353-97c97d6c-960a-4a68-8c1f-dee9d7b1350f.jpg) | ![sub-sup-after](https://user-images.githubusercontent.com/53781962/129036401-75ed1427-5e18-44f6-9afc-08c36328ef83.jpg) |

Support For`<sub>` And `<sup>` Tags

---

package-lock.json
package.json
src/components/editions/byline/byline.stories.tsx
src/components/editions/byline/index.tsx
src/components/editions/shareIcon/index.tsx
src/components/editions/standfirst/index.tsx
src/components/editions/standfirst/standfirst.stories.tsx

Currently on Editions we're rendering shareIcons on every article without checking if that article exists. This PR adds event listeners to listen to a ping from Mallard containing the webUrl of an article on a message in the form of:
```
{kind: "ShareIcon", value: "[weburl]"}
```
if that `value` is empty we then hide the shareIcon.
- upgrade Renditions to give access to new message types and functions
- add shareIcon listeners
- remove outdated stories
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/129017972-a3b4e042-2374-4d81-a346-c2f141eeeb33.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/129018017-c42a2626-a3f6-48c3-a68e-b1a9a33263f5.png" width="300px" /> |

LIVE-2906: hide share icons without url

---

scripts/ci.sh

This PR creates a Bash script in under scripts directory that would be used by teamcity step to built the app.
Currently teamcity has been setup so that it can work both when the script exists and when the script doesn't exist. So there will be no disruption for the existing PRs builds.
It has been tested in both scenarios.
When the script doesn't exists teamcity ignores the new step and run the original step
**First step:**
**Second step:**
When the script exists teamcity ignores the original step and runs the new step using the bash script
**first step:**
**second step:**

Add CI bash script for TeamCity Build

---

config/cloudformation.yaml

This PRs updates AR loadbalancer security group to allow inbound traffic from the lambda within the same VPC.
- update cloudformation loadbalancer security rule

Add ingress security group rule for loadbalancer

---

src/components/editions/article/article.stories.tsx
src/components/editions/headline/headline.stories.tsx
src/components/editions/headline/index.tsx

Comment headline had a gap for a contributor avatar even if there was not one available. This PR fixes this bug. 
NB - Sometimes there is no contributor at all.
- Check to see that we have a contributor and that the contributor has an image available.
- Style space for the image, if it's available.
- Add no contributor option to headline and comment article stories
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/129188978-469c1b0f-4922-425c-9eb0-4b2f7df487e3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/129189179-05e48bfc-c939-4e2c-a611-a6313130cf82.png" width="300px" /> |

LIVE-2892 : Comment Headline Styling 

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/article/index.tsx
src/components/editions/galleryImage/index.tsx
src/item.ts

Now we're hiding the shareIcon when article share is not available we were getting UI bugs as if there was no byline copy. In the old Editions app we simply hid the byline component, this PR implements both the non-rendering of byline components and the hiding of the header border bottom if there is no byline.
It also fixes a minor bug where use of `h2` text was breaking the border-right on the article body.
- hide byline component if byline is not present 
- hide header border bottom if byline  is not present
- swap margin for padding on editions body `h2` tag (production use this in draft articles sometimes :( ).
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/129582475-3e84e083-c11c-4d29-990a-cb5c0de1ab94.png" width="300px" /> | <img …

LIVE-2906: hide byline

---

src/components/editions/header/index.tsx

Editions Galleries were missing a series kicker.
- add kicker
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/130074801-2b586e31-5461-4bd1-aaff-ae2b6f4fd596.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/130074889-c7bc9911-ed75-43d4-9add-e9e61c64b83c.png" width="300px" /> |

LIVE-2954: add kicker to gallery

---

package-lock.json
src/components/editions/starRating/starRating.stories.tsx
src/components/headline.stories.tsx
src/components/starRating.stories.tsx

Type errors on storybook post-repo-migration will be thrown as errors during build time, so to ensure that the build completes, we should solve the type errors now
- Update type for `radio` which is used for star rating stories

Migration Preparation - Storybook type errors

---

src/components/anchor.tsx
src/renderer.ts

Sometimes Editorial use block quotes for poetry.  We should double check we don't need these anywhere else in the body in Editions.
- Don't render `Blockquote` component on Editions
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/130213544-74200caa-5ef5-48ce-b62e-f7d695df1ecf.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/130213586-71ca61f7-544f-4a6e-9ac8-7bc2e3174529.png" width="300px" /> |

LIVE-2961: hide quote marks on editions

---

src/styles.ts

Some of the editions fonts had the wrong names so they were not rendering in app.

LIVE-2984 : Update Font Names for Editions

---

src/__snapshots__/storyshots.test.ts.snap
src/components/editions/headline/index.tsx

Reverts guardian/apps-rendering#1462 as the designs don't work with font scaling.

Revert "LIVE-2976: fix styling"

---

README.md

This PR updates readme to announce that this repo is not active any more and it's content has been moved to a mono repo https://github.com/guardian/dotcom-rendering

update readme to inform repo is archived
