guardian/apps-rendering

.github/workflows/snyk.yml
Add GitHub action using Snyk to detect vulnerabilities before merging into master.
It will fail for any vulnerability detected but we do have the option to only fail on severe vulnerabilities. I would suggest we see how we go with this first.
I've deleted the GitHub integration in Snyk.io so the last 2 checks shouldn't run in future pull requests.
=> Create snyk action

artifact.json, config/cloudformation.yaml, package-lock.json, package.json, riff-raff.yaml, src/server/server.ts
To host the app on AWS
- Package the app for riff-raff
- Build it and package it via team city
- Deploy the app via riff-raff (except the auto scaling group)
- force the port to 9000
- add a simple healthcheck for the load balancer to pick
=> Deploy on AWS

src/capi.ts, src/components/news/article.tsx, src/components/news/articleHeadline.tsx, src/components/shared/articleBody.tsx
Add specific analysis tone styles.
- Analysis styles in `articleHeadline`
- Analysis classifier in `capi`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/70537165-eec1bb80-1b57-11ea-879c-4783adcedf19.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/70537761-e6b64b80-1b58-11ea-85e2-4afb11309fb1.png" width="300px" /> |
=> analysis styles

src/server/server.ts
When developing locally, whenever we make client-side requests we would like them to go to MAPI. This PR uses the express development server to proxy these requests on to MAPI CODE. This means the client-side code doesn't have to worry about where it's running; it can behave the same as it would in production, where MAPI will be on the same domain as the webview.
- Migrated articles to live under the `/dev-article` route.
- Added new catch-all route to proxy non-article requests to MAPI CODE.
=> Proxy MAPI Requests

src/server/server.ts
In #108 I implemented a method for proxying MAPI requests via our development server. This put articles and MAPI calls on different paths, which I realised would make the client-side code more complex.
This PR instead puts them on the same path and uses the `?a` query param to specify that something is an article.
- Removed the `/dev-article` path
- Implemented a query param check on `/` to decide whether to view an article or query MAPI
=> Query Param For Articles In DEV

src/components/immersive/immersiveArticle.tsx, src/components/liveblog/liveblogArticle.tsx, src/components/news/article.tsx, src/components/news/articleHeadline.tsx, src/components/opinion/opinionArticle.tsx, src/styles.ts
Some new additions have impacted the dark mode appearance
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71195744-790bcd00-2286-11ea-8efc-40c91693c145.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71195764-81640800-2286-11ea-92e0-33c6c7e5d6be.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/71195887-bbcda500-2286-11ea-93e6-412cb48b9d76.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71195908-c38d4980-2286-11ea-9c39-e0c0167d365e.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/71196319-b91f7f80-2287-11ea-8335-7556ef41f8b4.png" width="300" /> | <img …
=> dark mode styles on basic article

src/capiThriftModels.ts, src/components/immersive/immersiveStandfirst.tsx, src/components/liveblog/liveblogByline.tsx, src/components/news/articleByline.tsx, src/components/opinion/opinionHeadline.tsx, src/contentTransformations.ts
Fix an error in master.
BylineHtml can be optional, we should handle this case throughout the app.
=> Handle optional bylineHtml

src/components/immersive/immersiveArticle.tsx, src/components/immersive/immersiveStandfirst.tsx
- Remove duplicate byline that can be in the standfirst and byline fields
- Remove grey background from immersive articles
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/71720282-09b2e300-2e19-11ea-8468-d33c5cf55f73.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/71720286-120b1e00-2e19-11ea-9dac-cb90e6f5e6ab.png" width="300px" /> |
=> Remove duplicate byline

src/block.ts
- Migrate h2 styles to components
=> Header styles

src/block.ts
Error trying to access html on an undefined element.
http://localhost:8080/football/2020/jan/06/joy-of-fa-cup-osaze-urhoghide-antidote-critics?a
=> Catch undefined element

src/ads.ts, src/renderBlocks.ts
Fixes three different React key warnings for this article: http://localhost:8080/lifeandstyle/2020/jan/07/can-sun-simulator-improve-winter-mood-lethargy?a
=> Fix react key warnings

src/server/server.ts
Post endpoint to accept article data and return the rendered page.
Currently accepts JSON but future work can use Thrift.
=> Post endpoint

src/components/standard/article.tsx, src/components/standard/byline.tsx, src/components/standard/headline.tsx, src/components/standard/standfirst.tsx
I've been moving a lot of code around recently, mostly in the `Standard` article, so a follow-up refactor seemed a good idea. Also, our component files seem to have evolved to follow a common structure, so this attempts to standardise that structure somewhat.
- Organised imports
- Applied common file structure
- Simplified names
=> Tidy Standard Article

src/server/server.ts
Fixes a regression introduced in #142.
=> valid JavaScript

src/components/liveblog/block.tsx, src/components/liveblog/byline.tsx, src/renderer.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/72632916-3dc8f080-394f-11ea-836f-822e32aa5109.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72632929-44576800-394f-11ea-814b-016f69934407.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/72632938-4d483980-394f-11ea-8a91-c5bb732566bd.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72632952-5507de00-394f-11ea-92da-4945ef8cb582.png" width="300px" /> |
=> liveblog style fixes

src/components/standard/byline.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/72631428-21778480-394c-11ea-9766-a22ff5597b03.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72631405-1b81a380-394c-11ea-80a3-2df2913bcb4b.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/72631449-276d6580-394c-11ea-852c-8853aaea48a4.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72631472-2dfbdd00-394c-11ea-9f83-6ac7ac8049ba.png" width="300px" /> |
=> byline weight change

src/renderer.ts
Missing node types. We need to add the types we wish to render to this list.
=> handle more node types

src/renderer.ts
Add class so twitter script can enhance tweets.
http://localhost:8080/sport/2020/jan/21/how-nfl-running-back-justin-jackson-became-an-unexpected-star-of-the-left
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/72815269-4f1b4100-3c5e-11ea-9250-0c13ac7dcc04.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/72815285-54788b80-3c5e-11ea-994e-09ae0af14c31.png" width="300px" /> |
=> Enhance tweets

src/components/immersive/standfirst.tsx, src/components/liveblog/body.tsx, src/components/liveblog/standfirst.tsx, src/components/standard/standfirst.tsx, src/renderer.ts, src/styles.ts
UL elements weren't being rendered.
- Moved more bullet styles over to `renderer.ts`
| --- | --- |
=> Render unordered lists

src/capi.ts, src/contentTransformations.ts, src/renderer.ts, src/styles.ts
Reverts guardian/apps-rendering#163
=> Revert "Remove common styles"

src/client/article.ts, src/components/shared/follow.tsx, src/renderer.ts
Make it clearer that classnames are used in JavaScript. We might decide at some point to refactor this code into hydrated client side react components.
=> prefix classnames used in javascript

config/cloudformation.yaml
Specify correct log output directory so that stream can read logs and push them to ELK.
https://pm2.keymetrics.io/docs/usage/log-management/
=> update pm2 log output directory

.github/workflows/nodejs.yml, package-lock.json, package.json, webpack.config.js
- Client prod webpack configuration (production mode)
- Gzip resources
- Fail build if > 100KB after gzip
=> prod configuration for js

src/components/standard/byline.stories.tsx, src/components/standard/headline.stories.tsx
Some bugs introduced into our stories by #189.
- Used new types in storybook: `Item`, `Design` and `Display`
=> Fix Storybook Bugs

config/cloudformation.yaml, package-lock.json, package.json, src/client/article.ts, src/client/setup.ts, src/item.ts, src/logger/ILogger.ts, src/logger/LoggerFunctions.ts, src/logger/clientDev/index.ts, src/logger/clientProd/index.ts, src/logger/index.ts, src/logger/server/index.ts, src/server/server.ts, webpack.config.js
- To get logs in our ELK stack
- Set environment variables at the time PM2 starts
- Productionise the js bundle
- Create a logger with three implementation: clientDev, clientProd and server
- Swap the implementation based on which bundle we're building
- Use the new logger in all reasonable places instead of console.log
=> Production logs

src/ads.test.ts, src/ads.ts, src/client/article.ts, src/components/shared/page.tsx
There's a flag set in capi to hide ads, we should make sure we do.
=> don't insert ad placeholders if disabled in capi

package-lock.json, package.json
Keeping `source` up to date.
- Bumped `src-foundations` to `0.14.1`.
=> Update src-foundations To 0.14.1

src/components/immersive/series.tsx, src/components/shared/articleSeries.tsx, src/components/shared/headerImageCaption.tsx, src/components/standfirst.tsx, src/renderer.test.ts, src/renderer.ts
Style fixes. Tried to use the design system where possible.
- Font sizes
- Body side padding
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/76513670-8af8a880-644e-11ea-9105-3f03547f5649.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76513711-9c41b500-644e-11ea-8d06-ac87a8d61696.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76513733-a2379600-644e-11ea-8ee7-655dcaa5558b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76513756-a95ea400-644e-11ea-938c-5e6383bb83bf.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76513767-af548500-644e-11ea-96ff-263b5470e8c6.png" width="300px" /> | <img …
=> various style fixes

src/item.test.ts, src/item.ts, src/renderer.test.ts, src/renderer.ts
Handle Instagram elements: http://localhost:8080/film/2020/mar/12/kate-beckinsale-harvey-weinstein-rant-new-york-premiere
=> Instagram elements

package-lock.json, package.json, src/client/article.ts, src/components/shared/epic.tsx, src/native/nativeApi.ts
Splitting up the thrift client into multiple services will make it easier to use and maintain.
=> Multiple thrift clients

src/components/liveblog/block.tsx, src/components/liveblog/body.tsx, src/components/liveblog/byline.tsx, src/components/liveblog/headline.tsx, src/components/liveblog/keyEvents.tsx, src/components/liveblog/series.tsx, src/components/liveblog/standfirst.tsx, src/components/shared/articleBody.tsx, src/components/shared/headerImageCaption.tsx, src/components/shared/leftColumn.tsx, src/components/standfirst.tsx, src/renderer.ts, src/styles.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/76550603-4c80df00-648a-11ea-94af-a3f07b7115d3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76550625-54d91a00-648a-11ea-8a93-6ff22810a377.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76550644-5b679180-648a-11ea-995c-2eb4e1788402.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76550657-63bfcc80-648a-11ea-8352-d76957cf3d60.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/76550683-6cb09e00-648a-11ea-8fb3-c1f2975f4af4.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76550700-73d7ac00-648a-11ea-9a3f-6e7f23cb1a52 …
=> more style updates

src/components/bodyImageThumbnail.tsx, src/components/image.ts, src/item.test.ts, src/item.ts, src/renderer.test.ts, src/renderer.ts
New component and styles for when `role: "thumbnail"` is set.
https://www.theguardian.com/commentisfree/2020/mar/11/2020-budget-guardian-panel-verdict-rishi-sunak
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/76542561-1721c480-647d-11ea-9e37-f69eeef3aed5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/76542579-1ee16900-647d-11ea-8c1e-2d6fe3c43242.png" width="300px" /> |
| Wide | <img src="https://user-images.githubusercontent.com/11618797/76612168-a24d9980-6513-11ea-82f3-0143acda2a13.png" width="300px"/> |
=> thumbnail images

package.json
Catches me out every time I switch between the mobile-apps-article-templates and apps-rendering.
=> run nvm use before npm run watch

src/components/immersive/headline.tsx, src/components/liveblog/keyEvents.tsx, src/components/shared/articleBody.tsx, src/components/shared/articleSeries.tsx, src/renderer.ts, src/styles.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/77438873-43730480-6dde-11ea-88d9-13ff805a87c2.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/77438902-4ff75d00-6dde-11ea-9fbe-b7a039f2bd0e.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/77439068-81702880-6dde-11ea-92ad-321fc43e7504.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/77439103-8b922700-6dde-11ea-9c69-acfd9af9d1bb.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/77439136-95b42580-6dde-11ea-8fa3-3016aa46ed43.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/77439166-9e0c6080-6dde-11ea-8f63-5ae16a8223c1 …
=> style updates

package.json
This isn't working... so best to remove.
=> remove nvm command

src/ads.ts
Fix paragraphs not showing in production.
=> more robust is para check

src/components/audio.tsx, src/item.test.ts, src/item.ts, src/renderer.ts
- Render audio elements
- Render embed elements
| Audio | Embed |
| --- | --- |
| <img width="300" alt="Screen Shot 2020-04-01 at 16 09 11" src="https://user-images.githubusercontent.com/11618797/78153889-7ac36000-7433-11ea-801f-07c8a60e40ad.png"> | <img src="https://user-images.githubusercontent.com/11618797/78243950-9e8eb080-74dc-11ea-96a0-85f6ee3370d1.png" width="300" /> |
=> Audio and Embed elements

src/components/byline.tsx, src/components/follow.tsx, src/components/shared/articleBody.tsx, src/renderer.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78279617-b3386c00-750f-11ea-995d-4cfd1bf45865.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78279637-baf81080-750f-11ea-8202-0519e4c46a94.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/78279664-c8ad9600-750f-11ea-8bc4-0372f8ce9c30.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78279647-c1868800-750f-11ea-999d-0b8414006e5f.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/78279680-d06d3a80-750f-11ea-83c0-8f26ac8a4892.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78279700-da8f3900-750f-11ea-8576-779665c57786 …
=> comment byline styles

src/components/bodyImage.tsx, src/components/byline.tsx, src/components/follow.tsx, src/components/shared/articleBody.tsx, src/components/shared/articleSeries.tsx, src/components/shared/headerImageCaption.tsx, src/components/standfirst.tsx, src/renderer.ts
Dark mode styles.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78380309-91042400-75cb-11ea-8f62-3befc7c371f6.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78380371-aaa56b80-75cb-11ea-9e78-7ac9b3fa75ed.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/78380423-bc870e80-75cb-11ea-8eab-9813a5925372.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78380442-c4df4980-75cb-11ea-8516-95d09208567a.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/78380458-cc065780-75cb-11ea-88ce-58ebbbbb9b7c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78380483-d4f72900-75cb-11ea …
=> dark mode styles

src/components/byline.tsx, src/styles.ts
- Remove margin undeneath byline
- Add 8px padding underneath adverts
=> add padding underneath ads

src/components/video.tsx, src/item.test.ts, src/item.ts, src/renderer.ts
=> render video elements

package.json, src/client/article.ts, src/client/nativeCommunication.ts
Some errors on master, we now have a new bridget package `@guardian/bridget`
=> import new bridget package

src/components/bodyImage.tsx, src/components/bodyImageThumbnail.tsx, src/renderer.ts
Figcaptions can be optional. Happy to wait until Frankie's gallery PR is merged in as this might cause further conflicts.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/78558937-66081300-780b-11ea-8a9c-10ac0068208c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/78558958-70c2a800-780b-11ea-8cf1-a2229f33b1b3.png" width="300px" /> |
=> optional figcaption

src/renderer.test.ts, src/renderer.ts
Write a test for the renderCaption function for galleries
=> Write a test for renderCaption

src/components/byline.stories.tsx, src/components/commentCount.stories.tsx, src/components/follow.stories.tsx, src/components/headline.stories.tsx, src/components/liveblog/liveblog.stories.tsx, src/components/shared/shared.stories.tsx, src/components/standfirst.stories.tsx, src/components/starRating.stories.tsx
Stories were failing due to some old imports.
=> use display and design from format

.github/workflows/chromatic.yml, package-lock.json, package.json, src/components/dateline.stories.tsx
Run chromatic when pushing to GitHub.
Do we need the GitHub action as it looks like we've got a UI tests job running? @oliverlloyd
=> chromatic github action

src/ads.test.ts, src/ads.ts, src/styles.ts
Match current logic on apps.
This should hopefully be easier to configure if requirements change.
=> match current ad placeholder logic

src/components/headerImage.tsx, src/components/img.ts
1. set height on headerImage to avoid jumping content and sometimes incorrect ad positions
2. pass string as alt value on image element
=> use vw in height calculation

src/components/headline.stories.tsx, src/components/standfirst.stories.tsx
Reduced duplication in our stories by using the pillar selection helper.
- Used `selectPillar` from helpers
=> Reduce Storybook Duplication

src/components/byline.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/79856800-c2029800-83c4-11ea-9f4b-b2f9996b4203.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/79856825-c929a600-83c4-11ea-82a2-e7fc28024fa0.png" width="300px" /> |
=> use kicker for opinion byline

src/server/server.ts
Tidying up the server module before adding some features. Thought this was preferable to causing large diffs on more impactful changes. There shouldn't be any change in functionality.
- Tidied up the server module
=> Tidy Server Module

.github/workflows/snyk.yml
10am UTC is actually 11am BST, which is probably a bit late. Let's make this 9am UTC/GMT (10am BST).
- Changed Snyk schedule to 9am
=> Snyk Schedule At 9am

package.json, src/item.test.ts
- Add tests for `format`
- Increase test coverage minimums to 75%
=> test format type

src/components/immersive/article.tsx, src/components/shared/page.tsx
- Remove global page styles that can be applied to components
- Use design system font for immersive headlines
=> use design system font

src/components/anchor.stories.tsx
Adds a storybook component for Anchors
=> AR-18: Add anchor storybook component

src/components/bodyImage.tsx, src/components/img.ts, src/components/opinion/article.tsx, src/components/shared/articleBody.tsx, src/components/video.tsx, src/renderer.ts, src/styles.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/81327877-e1234a00-9093-11ea-849e-0c6aa6ee7214.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/81327872-e08ab380-9093-11ea-85ef-35ca90b832e0.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/81327878-e1bbe080-9093-11ea-9fa2-f0ffadc74999.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/81327881-e2547700-9093-11ea-9a47-06e195b39a4b.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/81327884-e385a400-9093-11ea-95f9-a80c24ff8b9c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/81327886-e385a400-9093-11ea-934d-4c478ee40197 …
=> dark mode colours

src/image.ts
Simple refactor pulling code into functions to make it easier to read.
- Pulled image parsing code into functions
=> Minor Image Refactor

src/components/standard/article.tsx, src/renderer.ts
=> drop caps on immersive articles

src/components/advertisementFeature/article.tsx, src/components/anchor.tsx
- Remove additional padding on header
- Use glabs green for anchors
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82074627-f66f2880-96d2-11ea-8881-65eab4bfd6fa.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82074647-ff5ffa00-96d2-11ea-8153-1822dd6ebe2c.png" width="300px" /> |
=> use glabs colour on anchors

src/bodyElement.ts, src/renderer.test.ts, src/renderer.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82432882-938de080-9a88-11ea-9609-e4b1f0238b44.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82432927-9f79a280-9a88-11ea-9231-378ca99a529e.png" width="300px" /> |
=> add alt caption for embeds

package-lock.json, package.json, src/client/article.ts, src/components/follow.tsx
https://github.com/guardian/bridget/issues/37
Pass human readable notification data for users.
I'm not sure if this has been implemented in iOS previously, but it would give us a good idea on whether it will throw an exception or crash the JS.
=> pass additional fields in notifications api

src/styles.ts
Removes unused custom `font` scheme.
=> remove custom font urls

src/components/anchor.tsx, src/components/figCaption.tsx, src/components/headline.tsx, src/components/standfirst.tsx, src/renderer.ts
- Use inverted over kicker in dark mode 
- Darken the border colour on links in dark mode
- Analysis headline dark styles
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/82895391-11039600-9f4c-11ea-9297-7c309293669f.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82895369-0812c480-9f4c-11ea-9d09-1dd790a6fb0d.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/82895435-211b7580-9f4c-11ea-8032-49983d1010d8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/82895411-19f46780-9f4c-11ea-92d8-eb8ddfb185ef.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/82895486-32fd1880-9f4c-11ea-9fd5-d5d6cef345cb.png" …
=> match current dark mode designs

src/components/byline.tsx
=> set width on comment bylines

package-lock.json, package.json, src/client/nativeCommunication.ts, src/components/shared/page.tsx
Follow up to https://github.com/guardian/bridget/pull/41
=> pass article title to native layers

src/client/article.ts
=> add spaces after all status strings

package-lock.json, package.json, src/client/article.ts
Sorry for another PR on this but there was another place where a missing space broke things so I've made them into constants.
Maybe this PR can be added to to handle the changes here https://github.com/guardian/bridget/pull/42
=> use constants for strings

src/server/csp.ts
https://www.theguardian.com/world/2020/jun/03/architect-of-sweden-coronavirus-strategy-admits-too-many-died-anders-tegnell
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/83635737-a29e8380-a59c-11ea-8420-cf327e30fc6b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83635762-a9c59180-a59c-11ea-8f3b-72c69c751233.png" width="300px" /> |
=> allow iframes from interactive url

src/components/opinion/cutout.tsx, src/server/csp.ts
- Dark mode cutout image fix
- theguardian.com, TikTok, Spotify and YouTube csp fixes
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/83860980-ebc71280-a717-11ea-9431-4848836a33a3.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83861037-013c3c80-a718-11ea-85af-8a3702ee07bc.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/83861076-0ac5a480-a718-11ea-8ad8-00f0c707a381.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/83861102-15803980-a718-11ea-8c3e-ac5e721fefff.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/83861405-76a80d00-a718-11ea-80c2-2abfbd30167d.PNG" width="300px" /> | <img …
=> more csp fixes

src/server/csp.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84015685-20cfa100-a974-11ea-93ce-537b8df84ff7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84015717-2b8a3600-a974-11ea-82a6-c33e36c6e0cc.png" width="300px" /> |
=> allow instagram scripts

src/components/video.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84038456-df50ed00-a997-11ea-8b1c-327daa9b7db7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84038500-f0016300-a997-11ea-9a56-3aff1d7eaf08.png" width="300px" /> |
=> add top and bottom margin to videos

package-lock.json, package.json, src/client/nativeCommunication.ts, src/native/nativeApi.ts
- Bumped bridget version to use correctly named service
- Calls friction screen when hide ad buttons are pressed
=> launch friction screen on ad click

src/components/liveblog/headline.tsx, src/components/liveblog/keyEvents.tsx, src/components/liveblog/metadata.tsx, src/components/liveblog/series.tsx, src/components/shared/leftColumn.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/84154723-5d2bfb80-aa5f-11ea-88b0-37bd78b96705.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84154747-65843680-aa5f-11ea-8dd6-50b7989fb1ee.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/84154775-6ddc7180-aa5f-11ea-8d54-af9d5f0f3181.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/84154805-759c1600-aa5f-11ea-812d-2f7bd482e6e8.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/84166055-4fc93e00-aa6c-11ea-9c9b-8e7cf7c556f5.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/84166082-56f04c00-aa6c-11ea-80d0-9ca0edd49151.p …
=> key event button styles

src/client/nativeCommunication.ts, src/components/headerImage.tsx
The majority of the page is image, which makes it very hard to scroll down and see the content. Trying to launches the gallery slideshow https://gu.com/us-news/2020/jun/10/george-floyd-protests-what-happens-next
=> Use click over touchstart

src/client/nativeCommunication.ts
We currently pass in low quality images for the gallery view.
This should pass the selected src from the Image srcset.
=> use the current src for image

src/client/article.ts, src/client/metrics.test.ts, src/client/metrics.ts, src/client/setup.ts
Making use of some of the [`Performance` APIs](https://developer.mozilla.org/en-US/docs/Web/API/Performance) available in the browser to check how our pages perform. For now this just logs to the console so that we can use it when developing.
**Note:** You will only see the "paint" metrics in Chrome, but you should see font metrics in all modern browsers.
- Added a `metrics` module
- Included metrics within `setup` module
- Added tests for `metrics` module
=> Performance Metrics

src/server/csp.ts
https://www.theguardian.com/stage/2020/jun/17/cultural-catastrophe-uk-theatre-faces-ruin-amid-coronavirus-crisis
=> enable scribd in csp

api-models/thrift/src/main/thrift/appsRendering.thrift
The intention of the type is clearer: It's a request going from MAPI to AR
=> Rename struct to RenderingRequest

README.md, package-lock.json, package.json, src/server/decoders.ts, src/server/server.ts
This makes use of the apps-rendering models, particularly the `RenderingRequest` type.
- Import the TS library
- Make use of the rendering request when parsing the client request. This changes the type received by the server.
=> Pass more data from MAPI

src/capi.test.ts, src/capi.ts
Star rating weren't showing for reviews because we weren't requesting the data.
=> add star rating to list of fields requested from capi

src/server/liveblogResponse.ts, src/server/server.ts
This was mocking requests from the old liveblog endpoint.
=> remove old liveblog mock

src/server/page.tsx
This page should never be seen... but if it is, it should have our standard side padding
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/85415176-e9144c00-b564-11ea-8b6b-b52c0c68af80.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/85415214-f3364a80-b564-11ea-9940-877b0dcb6308.png" width="300px" /> |
=> add padding to format not implemented paragraph

src/client/nativeCommunication.ts
[JIRA ticket](https://theguardian.atlassian.net/browse/GLA-2117?atlOrigin=eyJpIjoiNjMyMzVlNzY3YWFmNDBhMjliMjYwMjczNDBmYTQwOTIiLCJwIjoiaiJ9)
- observe `html` mutations instead of `body`
- fliter mutations to `style` only.
| --- | --- |
| ![2020-06-24 09 22 08](https://user-images.githubusercontent.com/12860328/85521530-48716b00-b5fc-11ea-9c22-75b1fad0350f.gif) | ![2020-06-24 09 20 21](https://user-images.githubusercontent.com/12860328/85521560-5626f080-b5fc-11ea-9998-e3bed35bb125.gif)|
=> GLA-2118: update adverts when font resize

src/components/shared/keyline.tsx
Use a lighter keyline in liveblog dark mode
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/85761696-eb180f80-b70a-11ea-9fd3-2f70814c1e9b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/85761740-f703d180-b70a-11ea-97d2-b4e15a02dbc9.png" width="300px" /> |
=> refactor keyline styles

package-lock.json, package.json, src/client/nativeCommunication.ts, src/components/img.ts
Fix for GLA-2121 where some images have an incorrect ratio in the slideshow/lightbox view.
=> Pass image height and width to client

src/components/headerVideo.tsx, src/components/media/article.tsx, src/server/page.tsx
- `darkModeCss` wasn't working inside a string
- dark HeaderVideo background colour on media articles
- Change body colour on media pages
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/86376180-86b2fe00-bc7e-11ea-857a-06754b8f60bf.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/86376202-903c6600-bc7e-11ea-8aeb-215cd9dfdffa.png" width="300px" /> |
=> Media article background colours

src/capi.test.ts, src/capi.ts, src/components/commentCount.stories.tsx, src/components/commentCount.tsx, src/components/metadata.tsx, src/fixtures/item.ts, src/item.ts, src/server/server.ts
=> Render comment count

src/components/commentCount.stories.tsx
Reverts removal in comment count PR.
=> revert count prop change removal

src/components/advertisementFeature/logo.tsx, src/renderer.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/86937826-9e372e80-c137-11ea-8d81-dd7597160cdc.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/86937871-ab541d80-c137-11ea-9e16-88977593fa5e.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/86938026-d8a0cb80-c137-11ea-9762-a0eeaaea35d6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/86938052-e1919d00-c137-11ea-8dd2-e5af88059ec4.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/86938257-24ec0b80-c138-11ea-98b7-1c0d0fc0653b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/86938279-2ddcdd00-c138-11ea-9816-00a6ec6ea843 …
=> use labs colours in standfirst and logo links

src/components/figCaption.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/87159925-ff870b00-c2b9-11ea-9ffe-e1ea58e051cc.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/87159932-01e96500-c2ba-11ea-902c-e9e068d5755a.png" width="300px" /> |
=> Figcaption link colours

src/atoms.ts, src/bodyElement.ts, src/renderer.ts
Captions not showing up in media atoms
- Captions now showing up
| --- | --- |
| <img src="https://user-images.githubusercontent.com/49187886/86810756-286a8e80-c075-11ea-8cf0-6c2da056e6de.png" width="400px" /> | <img src="https://user-images.githubusercontent.com/49187886/86811036-636cc200-c075-11ea-84eb-122a3741542f.png" width="400px" /> |
=> AR-67: Add caption to media atoms 

package-lock.json
Keeps lodash up to date.
- Bumped lodash to 4.17.19
=> Bump Lodash

src/components/byline.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/88401483-b9ee3600-cdc1-11ea-8fdb-7e85e5c59e76.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/88401497-bc509000-cdc1-11ea-8668-c788ecb447cf.png" width="300px" /> |
=> handle span tags in byline html

src/components/body.tsx, src/components/meta.tsx, src/components/scripts.tsx, src/server/page.tsx, src/server/server.ts
When walking through this code recently with @dskamiotis I realised that it's become a little tangled, and thus hard to understand for those coming to it fresh. This PR is an attempt to tidy it up a bit by splitting into smaller functions and components that do fewer things at once.
I'd like to do some further work to provide better error logging now that we're in Beta, which I hope will build on this.
- Pulled the body rendering into a component
- Pulled some of the head rendering into a component
- Put the scripts rendering into a standalone component file
- Broke down into smaller functions
=> Refactor Page

src/ads.ts, src/ads.tsx, src/client/nativeCommunication.ts, src/styles.ts
To match the new templates design.
=> new hide ads banner

src/components/advertisementFeature/article.tsx, src/components/media/article.tsx, src/components/opinion/article.tsx, src/components/standard/article.tsx, src/styles.ts
- Show related content on labs articles
- Show related content on comment articles
- Use section rather than footer tag to wrap relatedContent component
=> show related content on more article types

src/components/shared/card.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/90128107-35f2f280-dd5e-11ea-852d-1bb61148c56f.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/90128128-3ee3c400-dd5e-11ea-844f-8ed29273855e.png" width="300px" /> |
=> add styles for analysis cards

src/server/csp.ts
enable Vimeo embeds to be shown.
=> allow vimeo embeds in frames

src/components/series.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/90641923-ae0f5b80-e229-11ea-8f00-2f1c1154dc3e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/90641952-b49dd300-e229-11ea-8b90-2b4aaaaea889.png" width="300px" /> |
=> lab series styles

src/renderer.ts
Invalid CSS spotted by @dskamiotis.
- Added colon to `margin` to make CSS valid
=> Add colon to margin

src/image.test.ts, src/item.test.ts, src/renderer.test.ts
Use full guardian urls in tests.
=> remove references to gu.com

config/cloudformation.yaml
Link to the new apps-rendering runbook.
Is there any more work to get it showing as a link in gchat? @frankie297 @jacobwinch
=> link to apps-rendering runbook

config/cloudformation.yaml
Fix error deploying caused by this PR https://github.com/guardian/apps-rendering/pull/686
=> remove hyphens in cloudformation

src/components/headerImageCaption.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/92899090-6e95f280-f416-11ea-8774-64475d1cefc0.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/92899101-70f84c80-f416-11ea-8390-de7c379cc4e9.png" width="300px" /> |
=> align camera

src/components/headline.tsx
Feedback from the Beta showed the headlines sizes were very large, particularly when the font size was increased.
Setting the font-size to pixels will stop the headlines from changing size.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/92918060-000d6080-f427-11ea-9df7-48c574e266f8.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/92918119-0bf92280-f427-11ea-8b0c-ffbd4df5ecfc.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/11618797/92918172-17e4e480-f427-11ea-8c9a-95b8e55dfd3b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/92918189-1c110200-f427-11ea-9dd7-8063e9981ec2.png" width="300" /> |
| <img …
=> restrict headline sizes to pixels

src/client/article.ts, src/client/setup.ts
The bottom of interactives can be cut off. They are currently set to 500px in height.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/93117212-652ab580-f6b6-11ea-83f5-ee25347f069e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/93117241-71af0e00-f6b6-11ea-91d3-485e39a4464e.png" width="300px" /> |
=> resize interactives

.github/workflows/nodejs.yml, .storybook/pushFonts.sh
Rename uses of master branch to `main`
=> rename default branch to main

src/components/shared/card.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/94907349-ec8a6e00-0497-11eb-928d-ac65574cf32a.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/94907367-f4e2a900-0497-11eb-95a2-feaa92b5fe3c.png" width="300px" /> |
=> remove analysis padding on cards

src/components/shared/card.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/94906597-a7197100-0496-11eb-8bc5-4ad94e0416fd.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/94906611-aed91580-0496-11eb-9cad-767ca24a5ed9.png" width="300px" /> |
=> background colour for missing card images

src/client/article.ts, src/components/shared/epic.tsx, src/components/standard/article.tsx, src/native/thrift/nativeConnection.ts, src/server/csp.ts, src/styles.ts
Resolves a race condition issue where sometimes epics haven't been fetched natively.
=> poll insert epics

src/server/csp.ts
https://mobile.guardianapis.com/rendered-items/culture/2020/oct/05/why-is-dreams-by-fleetwood-mac-back-in-the-charts-and-why-is-everyone-skateboarding-along-to-it
=> new tiktok url

package-lock.json
Keeps `node-forge` up-to-date.
- Bumped `node-forge` to `0.10.0`.
=> Bump node-forge To 0.10.0

src/components/standard/article.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/95189445-c3cee500-07c5-11eb-8dd4-a4f69f9afd96.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/95189469-caf5f300-07c5-11eb-9b5c-ebbb2ee856e0.png" width="300px" /> |
=> only apply dropcap styles to immediate children

.github/workflows/screenshots.yml
I made a silly mistake with https://github.com/guardian/apps-rendering/pull/796.
Don't say I didn't [warn you](https://github.com/guardian/apps-rendering/pull/796#discussion_r500994700) @JamieB-gu!
=> Don't search for comment on main

.github/workflows/screenshots.yml
Because [this change](https://github.com/guardian/apps-rendering/pull/797) didn't work as expected.
=> Attempt to fix screenshots workflow

.github/workflows/nodejs.yml
This should help us to catch conflicts after merging to `main`. See: https://theguardian.atlassian.net/browse/LIVE-352
=> Run validation workflow against main

src/components/shared/epic.tsx, src/components/standard/article.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/95482517-2078fe00-0986-11eb-9693-3f8f5d02a18c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/95482583-371f5500-0986-11eb-8d8d-ee3a3cda688b.png" width="300px" /> |
=> keep epic the same size as article body

config/.eslintrc.js, package.json, src/bodyElement.ts, src/capi.ts, src/client/article.ts, src/components/body.tsx, src/components/headerImageCaption.tsx, src/components/immersiveCaption.tsx, src/components/liveblog/block.tsx, src/components/liveblog/body.tsx, src/components/liveblog/liveblog.stories.tsx, src/components/liveblog/metadata.tsx, src/components/media/article.tsx, src/components/series.tsx, src/components/shared/logo.tsx, src/components/shared/relatedContent.tsx, src/components/shared/shared.stories.tsx, src/components/shared/tags.test.tsx, src/date.ts, src/image.ts, src/liveBlock.ts, src/native/thrift/protocols.ts, src/renderer.ts, src/server/decoders.ts, src/styles.ts, webpack.config.ts
Added a 4-space indent rule to ESLint. Makes the codebase more consistent and also saves conversations and developer time during PR review.
More details on the rule [here](https://eslint.org/docs/rules/indent).
**Note:** The _only_ thing that should have changed across all files (except `.eslintrc.js` and `package.json`) is indentation. GitHub seems to be having trouble displaying this clearly in the diff in some cases (e.g. `bodyElement.ts`) - it might be worth checking it using another diff tool (for example, VSCode represents this more clearly for me).
- Set ESLint 'error' for indent of 4 spaces
- Set indent rule for switch...case
- Added npm script for ESLint auto-fix
- Fixed errors caused by this new rule
=> Enforce 4-Space Indentation

src/components/shared/epic.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/95853466-626ebf00-0d4d-11eb-9fa5-67d23d6c3488.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/95853525-7b777000-0d4d-11eb-86c8-fdd538f57fbe.png" width="300px" /> |
=> dark mode epics

src/components/meta.tsx, src/server/page.tsx, src/server/server.ts
Refactor only. Moving the `DOCTYPE` declaration to the `page.tsx` file where we build our HTML document, and moving the `meta[charset]` tag to the `Meta` component.
- Moved `DOCTYPE` to `page.tsx`
- Moved `meta[charset]` to `Meta`
=> Move DOCTYPE And Charset

src/components/meta.tsx
SEO might not be the most important feature for us, but I still think it's a good idea to have a meta description.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/96242858-ddc5b000-0f9b-11eb-85d9-2e8bcbfa4150.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/96242876-e4ecbe00-0f9b-11eb-8646-eb2d69b75e4a.png" width="300px" /> |
=> include meta description

config/.eslintrc.js, src/capi.ts, src/components/bullet.tsx, src/components/byline.tsx, src/components/dateline.stories.tsx, src/components/headerImage.tsx, src/components/immersiveCaption.tsx, src/components/pullquote.tsx, src/components/shared/bylineCard.tsx, src/components/shared/card.tsx, src/components/shared/logo.tsx, src/headerMedia.tsx, src/native/thrift/nativeConnection.ts, src/native/thrift/protocols.ts, src/server/server.ts, src/video.ts
Allows ESLint to check for and auto-fix trailing spaces. Docs [here](https://eslint.org/docs/rules/no-trailing-spaces).
- Added the `no-trailing-spaces` rule to ESLint
- Fixed all trailing spaces errors
=> No Trailing Spaces

package-lock.json, src/components/shared/card.tsx
Fix an accessibility issue flagged by Chrome's lighthouse audit. General refactoring and renaming of variables.
Source also advises against using this colour on dark backgrounds https://theguardian.design/2a1e5182b/p/1377a6-tokens/b/293ddb
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/96269317-242e0580-0fc2-11eb-900a-d7eb2d5d44e7.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/96269347-2c864080-0fc2-11eb-9775-66318b03091b.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/96269381-3445e500-0fc2-11eb-877c-6ad7defc154e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/96269416-4031a700-0fc2-11eb-9db7-222ba7d2a639.png" width="300px" /> …
=> better card contrast

src/server/csp.ts
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/96566140-1aa3e680-12bd-11eb-8dee-65b914cb79a3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/96566163-21caf480-12bd-11eb-9999-10c34d2ca6be.png" width="300px" /> |
=> enable facebook in csp

src/client/article.ts, src/components/shared/epic.tsx
the width of the epics is a bit too small so there's more space to the right compared to the left. It should take up the whole width
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/96609192-28c02a00-12f2-11eb-9ae1-d6c97a4c7da0.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/96609226-31b0fb80-12f2-11eb-84fe-747c5db9298c.png" width="300px" /> |
=> Full width Epic

src/client/article.ts, src/components/dateline.tsx, src/date.ts
Show times in user's timezones.
| Before | After UK | After US Pacific | After US Eastern |
| --- | --- | --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/97605611-c27c8b00-1a06-11eb-8423-7e0cc94b51b5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/97605628-c8726c00-1a06-11eb-97c7-acd7f88c18f8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/97608506-58fe7b80-1a0a-11eb-84e1-c215c80bcbb0.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/97608579-703d6900-1a0a-11eb-843a-a82bd1dac356.png" width="300px" /> |
=> local dates

.husky/pre-commit, package.json
Stop installing and running Husky on CI
=> only install husky locally

src/components/byline.tsx, src/components/img.ts, src/renderer.ts
Clear the console, ensure react stays performant and renders correctly.
There's a couple more warnings that have been fixed separately on the rich link branch. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/98847769-ab975900-2448-11eb-8acf-104b9bccd9ad.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/98847789-b3ef9400-2448-11eb-805d-5f1eef8d2243.png" width="300px" /> |
=> add keys to react components

package-lock.json, src/components/shared/footer.tsx
render content using isCcpa
- Change 1
- Change 2
| --- | --- |
=> render content using isCcpa

src/components/comment/article.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/99250105-122ec500-2803-11eb-8489-753d1a783de6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/99250148-1f4bb400-2803-11eb-8113-3a8cb8d3b98a.png" width="300px" /> |
=> opinion background

src/client/article.ts, src/components/richLink.tsx, src/lib.ts, src/server/server.ts
Additional changes to enable https://github.com/guardian/apps-rendering/pull/929
=> fetch from rendered item endpoint

src/client/article.ts
This bridget function hasn't been implemented yet in iOS, causing the iOS code to hang inside the bridget functon when debugging.
Commenting this code out for the time being to avoid any possible memory leaks for beta users.
=> stop calling unimplemented bridget function

.github/workflows/screenshots.yml
=> add screenshots for multiple article types

package-lock.json, package.json
Upgraded to react v17, this is required for the upgrading to JSX Transform.
Doing this a separate pull to ensure the safe construction of the process.
=> upgraded to react v17

package-lock.json
Keeping dependencies up to date.
- Bumped y18n to 4.0.1
=> Bump y18n To 4.0.1

package-lock.json
Keeping dependencies up-to-date.
- Bumped node-notifier to 8.0.1
=> Bump node-notifier To 8.0.1

src/components/anchor.tsx, src/styles.test.ts, src/themeStyles.ts
Make links colour palette 300
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19835654/103887705-6fe0de80-50db-11eb-86df-d2541aa9aef0.png" width="600px" /> | <img src="https://user-images.githubusercontent.com/19835654/103887735-7e2efa80-50db-11eb-90fe-cc867d59252b.png" width="600px" /> |
Paired with @joecowton1
=> Make links colour palette 300

.github/workflows/screenshots.yml
Make use of the lovely screenshot workflow to add some editions articles. For now I only added:
- Standard
- Opinion
- Review
=> Editions screenshots in CI

package-lock.json, src/components/comment/article.tsx, src/components/headerImageCaption.tsx, src/components/liveEventLink.tsx, src/components/richLink.stories.tsx, src/components/richLink.tsx, src/styles.test.ts, src/styles.ts
Upgrading basePx to remSpace for consistency across the Apps Rendering code base and inline with Source  
- Deleted imports of basePX
- Deleted basePx function with constant BASE_PADDING
- Added remSpace to styles
Paired with @joecowton1
=> replaced basePx with remSpace

src/components/editions/article.tsx, src/components/editions/header.tsx, src/components/editions/headerImage.tsx, src/components/editions/headline.tsx, src/components/editions/standfirst.tsx, src/components/editions/starRating.tsx, src/components/editions/styles.ts
Updates styling to reflect the Review format designs
- Adds Review-specific styling to Header and Headline (LIVE-1414)
- Adds editions star rating component (LIVE-1394)
- Separates Showcase specific styling from Body styling
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/104940214-537d5580-59a9-11eb-807a-43b2a7e644e4.png" width="300px" /> | <img  src="https://user-images.githubusercontent.com/20416599/104939540-72c7b300-59a8-11eb-9b45-958d47088411.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/104940225-5710dc80-59a9-11eb-8fbd-fbdc06ef9041.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/104939613-8d019100-59a8-11eb-8ea8-c9dd45ca8b8f.png" width="300px" /> |
| <img …
=> Feat: Live 986 - Review Article Template

src/components/editions/headline.tsx
This PR adds in breakpoint font styles for the Review template
- Add breakpoint font styles in the Headline component for mobile, mobile medium, and tablet
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/105081895-ba267000-5a8a-11eb-95be-d623fe4b31ce.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105081916-c01c5100-5a8a-11eb-9f0e-71f4f136d6a2.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/105081902-bd216080-5a8a-11eb-9d19-58b334866b8e.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105081912-bf83ba80-5a8a-11eb-8399-57646251fda1.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/105081907-be528d …
=> Add Review-specific headline font styling

src/components/editions/article.tsx, src/components/editions/byline.tsx, src/components/editions/series.tsx, src/components/editions/standfirst.tsx
Style Showcase Standfirst and update layout to match new Figma designs:
https://www.figma.com/file/AgfOrrLI78asahmA3Z9Env/AUS%2FUS-xtra-designs?node-id=3555%3A1651
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105511557-ec70e100-5cc7-11eb-99d2-ef2660db2cd2.png" width="300px" />  | <img src="https://user-images.githubusercontent.com/77005274/105511597-fa266680-5cc7-11eb-9d79-4c369a2edef2.png" width="300px" /> |
=> LIVE-1385: updating spacing and font styles

src/components/editions/byline.tsx, src/components/editions/standfirst.tsx
Add padding to the Byline for Interview designs.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/105522511-41672400-5cd5-11eb-89ef-1c5c492217c3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/105522685-73788600-5cd5-11eb-8987-7041c3428800.png" width="300px" /> |
=> Live 1455: Interview Byline

src/components/editions/byline.tsx, src/components/editions/headline.tsx, src/components/editions/standfirst.tsx
Updating Analysis template styles.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105696496-545b3d80-5efb-11eb-97e0-de22c1e9e5b3.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/105696532-6046ff80-5efb-11eb-8ad9-adb9d1c1517d.png" /> |
=> LIVE-1412: update analysis standfirst and byline spacing

src/server/server.ts
Add support for **editions** query parameter in **serveArticlePost** method
Original Jira Ticket - https://theguardian.atlassian.net/browse/LIVE-1446
=> support editions query param

src/components/editions/standfirst.tsx, src/components/editions/styles.ts
Adds header background colour and standfirst text styles.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105703964-eec07e80-5f05-11eb-89a9-0998df22640b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/105703984-f7b15000-5f05-11eb-8f60-8fe083a49fe0.png" width="300px" /> |
=> Live 1402 comment standfirst

package-lock.json, package.json, src/client/editions.ts, src/components/editions/headerImage.tsx
Follow up to this [Renditions PR](https://github.com/guardian/renditions/pull/3)
=> LIVE-1000: Editions-Rendering Lightbox Message

src/components/editions/avatar.tsx, src/components/editions/byline.tsx, src/components/editions/header.tsx, src/components/editions/headline.tsx, src/components/editions/standfirst.tsx
Adds Avatar to Comment template.
- Create Editions specific Avatar component
- Add Avatar to Byline component as optional extra 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/105844140-a621c780-5fd0-11eb-95b5-18eae78983d6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/105844165-b0dc5c80-5fd0-11eb-846e-2625de74ec5c.png" width="300px" /> |
=> LIVE-1402: add editions specific avatar component

package-lock.json, src/components/editions/headline.tsx
Adds quote SVG to headline.
For screenshots see generated Editions Comment image below.
=> Live 1401 headline quote styles 

src/components/editions/header.tsx, src/components/editions/lines.tsx
Updates Lines styling for Interview template
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/106134855-0777a100-615f-11eb-99d4-db827c3cd7f8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106134376-5bce5100-615e-11eb-9046-a490b9722a49.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/106134901-18281700-615f-11eb-89ea-dc0fe0463e4a.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106134387-5ffa6e80-615e-11eb-8c7c-83c537022422.png" width="300px" /> |
=> Add margin styles to lines

README.md
Raises awareness that the linter can fix problems automatically.
- Document the `lint:fix` command
=> Document The lint:fix Command

src/components/editions/byline.tsx, src/components/editions/header.tsx
This updates the byline styling for the interview template.
- Adds styling to byline
- Add share icon to byline on interview
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/106147305-9db3c300-616f-11eb-96b9-e581b4c9e319.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/106150074-dc974800-6172-11eb-8d68-c97bd457fa91.png" width="300px" /> |
=> Live 1408: Interview byline

.github/workflows/screenshots.yml
Add screenshots into the github workflow for Editions templates that are complete/in progress.
- Adds screenshots for Interview, Analysis, Showcase, Immersive and Gallery.
=> Update screenshots for Editions templates

src/components/editions/article.tsx
Only render finished templates.
=> LIVE-1472: only render finished templates

src/components/editions/styles.ts
Forgot to fix these on previous PR 🤦
=> FIX: remove unused deps

src/components/editions/headerMedia.tsx, src/components/editions/headline.tsx, src/components/editions/series.tsx
Moves Kicker to headline component. Changes in this PR had gotten lost somehow.
=> LIVE-1480: move series kicker to sit on headline

src/components/editions/series/index.tsx, src/components/editions/series/series.stories.tsx
Add Storybook coverage throughout Editions components.
- Add Series stories
- Move Series component to Series folder and rename.
=> LIVE-1577: add series stories

src/components/editions/headerImageCaption.tsx, src/components/editions/headerMedia/headerMedia.stories.tsx, src/components/editions/headerMedia/index.tsx
Adds stories for `HeaderMedia` component.
- move component to new folder and rename
- add stories
=> LIVE-1574: add stories for headerMedia component

src/components/editions/byline/byline.stories.tsx, src/components/editions/byline/index.tsx, src/components/editions/header.tsx
Creates `Byline` stories and refactors component to drive all template specific styling from `format` in keeping with other components.
- Add stories
- Remove styling props 
- Drive all styles from `format` values
=> Live 1571 byline storybook

.storybook/addons.js, .storybook/config.js, .storybook/main.js, .storybook/preview.js, package-lock.json, package.json, src/components/editions/article/article.stories.tsx
Adds viewports to Storybook for Small Mobile, Mobile, Tablet and Tablet Landscape.
This allows us to view any breakpoint at the click of a button - its already highlighted a few small layout bugs that will need addressing.
- Update storybook config and add addon
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/107765306-7a6d4400-6d29-11eb-840e-77fb972b1c9d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/107765330-878a3300-6d29-11eb-89d8-da7b9739791d.png" width="300px" /> |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/107765603-10a16a00-6d2a-11eb-8c72-9e9cc22d5645.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/107765642- …
=> LIVE-1665: add viewports (with addon-essentials) to storybook 

src/__snapshots__/storyshots.test.ts.snap
Just a couple of missing storyshots (gallery image and star rating).
=> Gallery Image and Star Rating Storyshots

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/article.stories.tsx, src/components/editions/article/index.tsx, src/components/editions/byline/index.tsx, src/components/editions/header/index.tsx
Fixes a few minor styling bugs thrown up by adding viewports in Storybook
- Add missing display type to Showcase story
- Remove article borders and padding on mobile / phablet
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/108087490-68640c00-706f-11eb-97b0-e6f1af9e692d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/108087558-79ad1880-706f-11eb-93ca-fdd3e63ece8e.png" width="300px" /> |
=> LIVE-1706: fix minor breakpoint related issues

package-lock.json, package.json
Found via the npm audit security report:
More info:
| | |
| --- | --- |
| High | Server-Side Request Forgery |
| Package | axios |
| Dependency of | chromatic [dev] |
| Path | chromatic > @chromaui/localtunnel > axios |
| More info | https://npmjs.com/advisories/1594 |
=> Update chromatic dependency [high severity]

config/cloudformation.yaml, riff-raff.yaml
Reverts guardian/apps-rendering#1132
Ready for when we need to revert back to old instance
=> Revert "Add Graviton 2 ARM instance type"

src/contributer.test.ts, src/contributor.ts
Subtask of the [increase coverage ticket](https://theguardian.atlassian.net/browse/LIVE-1684)
| | Before | After |
| - | ------ | ----- |
| Statements | 60.82%  | 61.06% (+0.24%)|
| Branches | 55.72% | 55.72% (0%)| 
| Functions | 55.67% | 56.54% (+0.87%) |
| Lines | 60.09% | 60.29% (+0.2%) |
=> LIVE-1695: contributor.ts test

src/__snapshots__/storyshots.test.ts.snap, src/fixtures/item.ts
Adds enum lookups to mock data rather than using raw numbers.
=> LIVE-1785: use enum lookups in mock data

src/__snapshots__/storyshots.test.ts.snap
=> FIX: update snapshots

src/__snapshots__/storyshots.test.ts.snap
Jest is being weird about updating our snapshots (see #1191). Let's see if updating them again settles it down.
- Updated snapshots
=> Update Snapshots To Use Guide Atoms

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/article.stories.tsx, src/components/editions/article/index.tsx, src/components/editions/header/index.tsx, src/fixtures/item.ts
Production feedback has flagged that the `Editorial` designs are not being reflected.
- Add Editorial story
- add `if` case for `Design.GuardianView`
- add `Design.GuardianView` to article rendering list
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/109800181-ca4a7700-7c14-11eb-9ab0-01fcddd98309.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/109800240-d7676600-7c14-11eb-9424-b0586c99b305.png" width="300px" /> |
=> LIVE-1834: add GuardianView / Editorial article type

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/article.stories.tsx
A lint error has sneaked into main. And snapshots needed updating.
=> Fix main's lint error and snapshots

src/video.test.ts
subtask of [increase coverage ticket](https://theguardian.atlassian.net/browse/LIVE-1684)
| | Before | After |
| - | ------ | ----- |
| Statements | 60.54%  | 61.67% (+0.24%)|
| Branches | 55.09% | 57.6% (0%)| 
| Functions | 56.74% | 57.8% (+0.87%) |
| Lines | 59.73% | 60.82% (+0.2%) |
=> LIVE-1692: video.ts test

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/standfirst/index.tsx
This is a fix for a styling bug that positions the share button below the standfirst text.
- Change 1
- Change 2
| Before | After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/110359843-ec3d6280-8035-11eb-9b89-f26794e48320.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/110359858-efd0e980-8035-11eb-8fd3-dba151286ee3.png" width="300px" /> |
=> Fix: Standfirst Spacing

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/headerImageCaption.tsx, src/components/editions/headerMedia/index.tsx
~This PR lifts the class name top the parent component of header media so that we can trigger a lightbox on click~
This PR removes the pointer event from the image caption and adds it to summary to unblock the image component.
- Disable caption pointer event to unblock image
- Disable dark mode as editions does not currently support dark mode
=> LIVE-1880 : Header Media Lightbox

package-lock.json
Update vulnerable packages with `npm audit fix`.
=> Vulnerable packages update (from npm audit)

config/cloudformation.yaml, riff-raff.yaml
Reverts guardian/apps-rendering#1181
Merge when we want to upgrade to new instance type
=> Revert "Revert "Add Graviton 2 ARM instance type""

package-lock.json
Keeps dependencies up-to-date.
- Bumped postcss to 8.3.0
=> Bumped `postcss` To `8.3.0`

src/server/editionsPage.tsx
We have a margin we don't need on the Editions Rendering templates.
- Remove margin
=> LIVE-2490: remove margin

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/article.stories.tsx, src/components/editions/header/index.tsx
Adds kicker to `analysis` article header.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/121027009-8a100d00-c79e-11eb-8677-13ee3368cec5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/121027155-a4e28180-c79e-11eb-81cd-8e8807ef8981.png" width="300px" /> |
=> LIVE-2535: add series to analysis header

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/standfirst/index.tsx
The Editions Comment Standfirst had the wrong font color, weight and size. This PR amends the Standfirst inline with designs.
=> LIVE-2560 : Comment Standfirst : Update font colour, weight and size

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/header/index.tsx
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/122909155-ce79dc00-d34c-11eb-98d1-8acda670b5eb.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/122909354-06811f00-d34d-11eb-9790-64f31fc36612.png" width="300px" /> |
=> Add padding to Letter

src/__snapshots__/storyshots.test.ts.snap, src/components/richLink.tsx, src/server/server.ts
https://theguardian.atlassian.net/browse/LIVE-2641
=> LIVE-2641: rich links

src/__snapshots__/storyshots.test.ts.snap, src/components/tags.tsx
https://theguardian.atlassian.net/browse/LIVE-2640
- Tags spacing and tags container spacing.
=> LIVE-2640: Tags 

src/server/csp.ts
This is a mistake
- remove duplicate entry
No UI changes.
=> LIVE-2706: remove duplicate CSP entry

config/cloudformation.yaml
This PR moves apps-rendering instances (auto scaling group) to private subnets
=> LIVE-2628 - Move asg to private subnets

src/components/body.tsx, src/components/editions/article/index.tsx, src/item.ts
Add the new Obituary design type to the parser and handle type in article rendering for Editions and Apps.
=> LIVE-2703 : Add Design.Obituary

src/server/server.ts
Reinstating missing functionality.
=> LIVE-2788: reinstate missing params

src/__snapshots__/storyshots.test.ts.snap, src/components/headerImage.tsx, src/components/headline.tsx, src/components/series.tsx
Fixing some changes design requested with vertical spacing in header component.
https://www.figma.com/file/SL8IPGVP1FqFBkE7lMTI5l/apps-rendering-details?node-id=214%3A12939
| Before (without series tag) | After (without series tag) |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19835654/126494230-48ebf002-9475-4690-b909-ea3696eb05a9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/19835654/126494313-468c69ba-e7be-467e-af6b-1aea05413110.png" width="300px" /> |
| Before (with series tag) | After (with series tag) |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19835654/126494720-769395fb-d940-4761-86e7-906e378c53a6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/19835654/126494784-06630c73-ed9 …
=> LIVE-2629: Fix vertical margins in the header

package-lock.json
Keeping dependencies up-to-date.
- Used `npm audit` to bump some dependencies
=> Bump Dependencies Via `npm audit`

config/cloudformation.yaml
=> Removed unused key for ingress rules

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/index.tsx, src/components/editions/galleryImage/index.tsx, src/item.ts
Reverts guardian/apps-rendering#1451
=> Revert "LIVE-2906: hide byline"

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/article/index.tsx
Adds a className to the body section so Editions client can target body text and scale font size.
=> LIVE-2973 : Add classname to body section

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/headline/index.tsx
Headline line height was incorrect.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/130768899-0ffac013-d821-49a7-9b30-cedb49d71253.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/130768949-4fb38749-f9a1-4771-b5ca-828fa9589390.png" width="300px" /> |
=> LIVE-3002: fix line height

src/__snapshots__/storyshots.test.ts.snap, src/components/editions/headline/index.tsx
We've updated analysis header styling.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/130487370-f789b812-e3aa-473b-bf4b-180ac8a959d8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/130487279-6615569b-ac8c-47d8-beb4-bcf63f9caad0.png" width="300px" /> |
=> LIVE-2976: fix styling
